local L
if setting.lang==1 or setting.lang==2 then
	L={
		"ZS JL T O I",
		"VVVVVV好玩!",
		"uid:225238922",
		"Tetralegends也很好玩!",
		"tetr.js也很好玩!",
		"Tetr.io也很好玩!",
		"Techminohaowan",
		"Techmino 好玩!",
		"STSD必死",
		"REGRET!!",
		"osu好玩!",
		"O spin Triple!",
		"Nullpomino也很好玩!",
		"Naki 可爱!",
		"Miya 可爱!",
		"Lua天下第一",
		"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
		"Let-The-Bass-Kick!",
		"l-=-1",
		"Jstris也很好玩!",
		"fin neo iso 是满足tspin条件的特殊t2的名字",
		"e^(pi*i/2)=i",
		"e^(pi*i)=-1",
		"DT炮=TSD+TST炮",
		"Cultris II也很好玩!",
		"Ctrl+W=关闭当前标签页",
		"Ctrl+Tab=切换标签页",
		"Ctrl+F=查找",
		"Ctrl+D=复制一份",
		"Ctrl+Alt+Z=查看所有qq消息",
		"Ctrl+A=全选",
		"Ctrl+鼠标滚轮=缩放",
		"COOL!!",
		"BT炮=beta炮=TCM-β炮",
		"backspace=返回上一个文件目录",
		"B2B2B2B存在吗?",
		"B2B2B???",
		"Am G F G",
		"Alt+Tab=切换窗口",
		"Alt+F4=关闭当前窗口",
		"ALLSPIN!",
		"注意到\"旋转\"到底对方块做了些什么吗?",
		"有疑问? 先看设置有没有你想要的",
		"有建议的话可以把信息反馈给作者~",
		"学会使用两个旋转键, 三个更好",
		"新人请千万记住,打好基础,不要太早学那些花里胡哨的。",
		"享受Tech的特色旋转系统!",
		"无聊翻翻设置是好习惯",
		"我的世界好玩!",
		"提前旋转等设置可以用来救命",
		"泰拉瑞亚好玩!",
		"适度游戏益脑,沉迷游戏伤身,合理安排时间,享受健康生活",
		"使用love2d引擎制作",
		"少女祈祷中",
		"扫雷好玩!",
		"请不要向对方块不感兴趣的路人推荐此游戏。",
		"请不要随意宣传,出了事都怪你们",
		"你可以从统计页面打开游戏存档目录",
		"魔方好玩!",
		"喵!",
		"免费吃鸡方块",
		"秘密数字:626",
		"每个虚拟按键都可以隐藏/显示,尺寸也可调",
		"每个块的出现方向可以自定义。",
		"没有专业美术的人,程序员审美警告",
		"没学过编曲,音乐都是自己凭感觉写的,觉得不好听就设置里关了吧",
		"联网还没做呢, 别急",
		"键位是可以自定义的。",
		"健康小贴士:玩游戏多眨眼,不然会干眼病",
		"健康小贴士:不要熬夜,真的会猝死",
		"合群了就会消失, 但是消失不代表没有意义",
		"更小的DAS和ARR拥有更高的操作上限(前提是你能控制得了)",
		"俄罗斯方块环游记也不错!",
		"调到特殊的日期也不会发生什么的",
		"低帧率会降低游戏体验",
		"戴上耳机以获得最佳体验",
		"大满贯10连击消四全清!",
		"打好块没有捷径,多练。",
		"茶娘 可爱!",
		"草(日本语)",
		"不要在上课时玩游戏!",
		"不要随意宣传,不要随意宣传,不要随意宣传",
		"不要盯着bug不放",
		"不是动画,真的在加载!",
		"别问游戏名怎么取的,问就是随便想的",
		"本游戏难度上限很高, 做好心理准备。",
		"本游戏可不是休闲游戏",
		"报时机器人:新的一天开始了",
		"626r/s",
		"40行世界纪录:15.654s",
		"4+4+4+4+2+2+1=17",
		"3.1415926535897932384",
		"26连T2来一个?",
		"20G本质是一套全新的游戏规则",
		"20连PC来一个?",
		"2+2=Miya",
		"2.7182818284590452353",
		"15puzzle好玩!",
		"11renPC!",
		"100行内23PC来一个?",
		"1, 2, ⑨!!!!!",
		"<方块研究所>有一个Nspire-CX版本!",
		"↑↑↓↓←→←→BABA",
		"\\196/",
		"(RUR'U')R'FR2U'R'U'(RUR'F')",
		-- "Z酱 可爱!",
	}
elseif setting.lang==3 then
	L={
		"ZS JL T O I",
		"You can set orientation for each block",
		"You can open saving directory from stat. page",
		"You are Grand Master",
		"wwwwww",
		"Who is diao",
		"What about 26 TSDs?",
		"What about 20 PCs?",
		"What about 23 PCs in 100 lines?",
		"Warning: Programmer Art",
		"Try to use two rotate button,three better",
		"This in not a casual game",
		"This game can be very hard,be mentally perpared",
		"Tetris journey has network battle!",
		"Tetralegends is fun!",
		"Terraria is fun!",
		"Techmino=Technique+Tetromino",
		"Techmino is so fun!",
		"Techmino has a Nspire-CX edition!",
		"Switch music off if make you awful",
		"Small DAS&ARR can make you faster,if you can control block correctly",
		"Secret num:626",
		"Rubik's cube is fun!",
		"REGRET!!",
		"Powered by love2d",
		"Playing too much = taking drugs",
		"OSU is fun!",
		"Only offline game now",
		"OHHHHHHHHHHHHHH",
		"O spin triple!",
		"Nothing will happen when some special day come",
		"Not animation,real loading!",
		"Miya:Nya!",
		"Miya so cute!",
		"Minesweeper is fun!",
		"Minecraft is fun!",
		"Lua No.1",
		"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
		"Lower fps causes lower game experience",
		"Let-The-Bass-Kick!",
		"l-=-1",
		"Is B2B2B2B possible?",
		"Initial Rotation etc. can save your life",
		"Hello world!",
		"Headphones for better experience",
		"Have you noticed what does \"rotating\" do to block?",
		"Find out what's in the setting!",
		"Enjoy Tech. Rotation System!",
		"e^(pi*i/2)=i",
		"e^(pi*i)=-1",
		"DT cannon=TSD+TST",
		"Don't look directly at the bugs!",
		"DO NOT PRESS F10",
		"Do not play game in class!",
		"Disappearing doesn't mean useless",
		"Diao so bully",
		"COOL!!",
		"Back to Back 10 combo Techrash PC!",
		"B2B2B???",
		"Any suggestions to author!",
		"Am G F G",
		"Also try VVVVVV!",
		"Also try Tetr.js!",
		"Also try Tetr.io!",
		"Also try Nullpomino!",
		"Also try Jstris!",
		"Also try Cultris II!",
		"ALLSPIN!",
		"少女祈禱中",
		"40L WR: 15.654s",
		"4+4+4+4+2+2+1=17",
		"3.1415926535897932384",
		"225238922  Bilibili cheers!",
		"20G actually is a brand new game rule",
		"2^2=Miya",
		"2.7182818284590452353",
		"15puzzle is fun!",
		"11renPC!",
		"1, 2, ⑨!!!!!",
		"↑↑↓↓←→←→BABA",
		"\\osk/",
		"\\jezevec/",
		"\"Free block game with royale mode\"",
		"(RUR'U')R'FR2U'R'U'(RUR'F')",
		":pog:",
	}
elseif setting.lang==4 then
	L={'!','@','#','$','%','^','&','*','(',')','-','=','_','+','[',']','{','}','\\','|',';',':','\'','"',',','<','.','>','/','?'}
	local s=""
	for i=1,math.random(16,26)do
		s=s..L[math.random(#L)]
	end
	return s
elseif setting.lang==5 then
	local R=math.random()
	if R<.05 then
		local time={
			--[[00]]"大半夜的在这干啥呢?不睡觉是会猝死的",
			--[[01]]"大半夜的在这干啥呢?不睡觉是会猝死的",
			--[[02]]"现在打块你是认真的?",
			--[[03]]"现在打块你是认真的?",
			--[[04]]"早起是好的,但是你不应该打块",
			--[[05]]"早起是好的,但是你不应该打块",
			--[[06]]"早饭吃好了?",
			--[[07]]"早饭吃好了?",
			--[[08]]"九点多了,没自己的事情要做?",
			--[[09]]"十点多了,没自己的事情要做?",
			--[[10]]"十一点多了,午饭有的吃么",
			--[[11]]"十二点多了,午饭有的吃么",
			--[[12]]"累了累了,现在不想说你",
			--[[13]]"累了累了,现在不想说你",
			--[[14]]"累了累了,现在不想说你",
			--[[15]]"累了累了,现在不想说你",
			--[[16]]"累了累了,现在不想说你",
			--[[17]]"晚饭吃好了?",
			--[[18]]"晚饭吃好了?",
			--[[19]]"累了累了,现在不想说你",
			--[[20]]"累了累了,现在不想说你",
			--[[21]]"好睡了,作息健康活得久",
			--[[22]]"好睡了,作息健康活得久",
			--[[23]]"大半夜的在这干啥呢?不睡觉是会猝死的",
		}
		return time[tonumber(os.date("%H"))+1]
	elseif R<.1 then
		local int=math.floor
		L={
			"平均"..int(stat.row/stat.time*60).."LPM,那可真强呢",
			"平均"..int(stat.atk/stat.time*60).."APM,好厉害哦",
			"平均"..(int(stat.atk/stat.row*10)*.1).."效,你看这数据能看么",
			"平均"..(int(stat.atk/stat.row*10)*.1).."效,我就不说你多菜了",
			"才玩了"..stat.game.."把,跟几十万局的没法比",
			"才玩了"..stat.game.."把,玩了不下几万局的人可不在少数",
			"才玩了"..int(stat.time/3600).."小时,人家总时长是你不知道多少倍",
			"才玩了"..int(stat.time/3600).."小时,别人总时长跟你都不在一个数量级",
		}
	else
		L={
			"隐形难吗?那个节目上的谁,水平那么菜也打得还行,就是你菜",
			"一口一个wtcl还不赶紧去练,你是不思进取还是不想好好说话?",
			"我一个滑铲就挖了个11renPC",
			"我曾经在极度愤怒的时候15秒消了40行",
			"天天F3F3,怕别人不知道你菜?",
			"天天卖弱,你一定把把150apm吧?",
			"天天催更催更,你咋不来帮忙开发啊,真以为作者很强催催啥都有?",
			"设置都看过一遍了吗?明明都能调还嫌这嫌那,可牛逼了您",
			"少玩点,多眨眼,到时候瞎了别怪我没提醒你",
			"人只用一只手都能玩,你呢?",
			"全隐40行全消四很难吗??",
			"没那水平别天天整什么花里胡哨的,人玩几年你想几天赶上?",
			"满口PCDT信天翁,还会点别的么?",
			"叫你多练消四不听,现在要速度没速度,spin打完地形一塌糊涂,开心了?",
			"叫你多练就多练,想着几天变神仙,当自己是谁?",
			"极限20G不是随手通?",
			"还搁这玩手机呢,作业做完了?",
			"除了雨宫太阳你还认识谁?Jonas知道吗?Ajanba听过吗?",
			"不会吧不会吧,真的还有人不能随手Tspin?",
			"别会个c4w就以为自己多强,这是基本功罢了。",
			"60lpm?拍硬降刷的吧。",
			"40行还要40多秒,就这?",
			"3pps不是人均水平?",
			"25TSD不难吧。",
			"20G很难?是个人都能玩吧。",
			"20连pc不是随手?",
			"100apm?定式刷的吧。",
			"0202年了,还在玩这种小孩子玩的游戏?",
		}
	end
end
return L[math.random(#L)]