local L
if setting.lang==1 or setting.lang==2 then
	L={
		'注意到"旋转"到底对方块做了些什么吗?',
		"(RUR'U')R'FR2U'R'U'(RUR'F')",
		"\\196/",
		"↑↑↓↓←→←→BABA",
		"1, 2, ⑨!!!!!",
		"100行内23PC来一个?",
		"11renPC!",
		"15puzzle好玩!",
		"2.7182818284590452353",
		"2+2=Miya",
		"20连PC来一个?",
		"20G本质是一套全新的游戏规则",
		"26连T2来一个?",
		"3.1415926535897932384",
		"4+4+4+4+2+2+1=17",
		"40行世界纪录:15.654s",
		"626r/s",
		"把手机调到特殊的日期也不会发生什么的(真的",
		"报时机器人:新的一天开始了",
		"本游戏可不是休闲游戏",
		"本游戏难度上限很高,做好心理准备。",
		"必须要软降才能放进去的方块一定不会判定你是非极简操作",
		"别问游戏名怎么取的,问就是随便想的",
		"不是动画,真的在加载!",
		"不要盯着bug不放",
		"不要向不感兴趣的路人推荐!!!!!!!!",
		"不要在上课时玩游戏!",
		"草(日本语)",
		"茶娘 可爱!",
		"触摸板打osu是什么体验",
		"打好块没有捷径,多练。",
		"大满贯10连击消四全清!",
		"戴上耳机以获得最佳体验",
		"单手也能玩!",
		"低帧率会降低游戏体验",
		"俄罗斯方块环游记也不错!",
		"方块默认出现的方向都是重心在下哦",
		"方块研究所 有一个Nspire-CX版本!",
		"感觉自己明明按键了但是没反应?你真的按到了吗?",
		"感谢Phigros,让我抄了一堆tips(",
		"给别人推荐本游戏的时候请记住我真的不叫铁壳米诺!!!",
		"更小的DAS和ARR拥有更高的操作上限(前提是你能控制得了)",
		"还能写些什么tip呢",
		"合群了就会消失,但是消失不代表没有意义",
		"很有精神!",
		"健康小贴士:不要熬夜,真的会猝死",
		"健康小贴士:玩游戏多眨眼,不然会干眼病",
		"键位是可以自定义的",
		"觉得移动速度太慢或太快,手感不好?快去设置调整DAS/ARR",
		"联网还没做呢,别急",
		"卖弱禁言警告",
		"没学过编曲,音乐都是自己凭感觉写的,觉得不好听就设置里关了吧",
		"没有专业美术的人,程序员审美警告",
		"每个块的出现方向可以自定义",
		"每个虚拟按键都可以隐藏/显示,尺寸也可调",
		"秘密数字:626",
		"免费吃鸡方块",
		"喵!",
		"魔方好玩!",
		"你的双手是为了你的一生服务的,而不是Techmino",
		"你可以从统计页面打开游戏存档目录",
		"请勿大力敲打设备!敲坏了就没有Techmino玩了",
		"扫雷好玩!",
		"少女祈祷中",
		"使用love2d引擎制作",
		"适度游戏益脑,沉迷游戏伤身,合理安排时间,享受健康生活",
		"术语不认识?去帮助-词典里查查吧",
		"泰拉瑞亚好玩!",
		"提前旋转等设置可以用来救命",
		"玩到一半弹出消息框?快去设置禁止弹窗",
		"为了防止误触,玩到一半重开需要长按重开键",
		"为了收集Tips一直关游戏就没意思了,要的就是惊喜",
		"为什么关卡那么少啊!-因为你前一模式成绩连D都没有达到,再加把劲吧~",
		"我的世界好玩!",
		"我们的每一条tips都很正经(确信",
		"我们是不是第一个在方块游戏做tips的?",
		"无聊翻翻设置是好习惯",
		"希望极简率没事",
		"希望你们都能喜欢Z…哦不是,喜欢Techmino",
		"享受Tech的特色旋转系统!",
		"新人请千万记住,打好基础,不要太早学那些花里胡哨的。",
		"旋转不是变形!请尽量灵活利用顺逆时针两个旋转键!",
		"学会使用两个旋转键,三个更好",
		"游戏作者40行卡27秒好几个月了...",
		"有建议的话可以把信息反馈给作者~",
		"有疑问? 先看设置有没有你想要的",
		"在?为什么半夜打块?",
		"长时间游戏状态会越来越差!玩久了记得放松一下~",
		"这里的极简判定不松不严,放心软降,小心hold!",
		"ALLSPIN!",
		"Alt+F4=关闭当前窗口",
		"Alt+Tab=切换窗口",
		"Am G F G",
		"B2B2B???",
		"B2B2B2B存在吗?",
		"backspace=返回上一个文件目录",
		"BT炮=beta炮=TCM-β炮",
		"COOL!!",
		"Ctrl+鼠标滚轮=缩放",
		"Ctrl+A=全选",
		"Ctrl+Alt+Z=查看所有qq消息",
		"Ctrl+D=复制一份",
		"Ctrl+F=查找",
		"Ctrl+Tab=切换标签页",
		"Ctrl+W=关闭当前标签页",
		"Cultris II也很好玩!",
		"DT炮=TSD+TST炮",
		"e^(pi*i)=-1",
		"e^(pi*i/2)=i",
		"fin neo iso 是满足tspin条件的特殊t2的名字",
		"Jstris也很好玩!",
		"l-=-1",
		"Let-The-Bass-Kick!",
		"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
		"Lua天下第一",
		"Miya 可爱!",
		"Naki 可爱!",
		"Nullpomino也很好玩!",
		"O spin Triple!",
		"osu好玩!",
		"Phigros好玩!",
		"REGRET!!",
		"STSD必死",
		"Techmino好玩!",
		"Techminohaowan",
		"TechOS?那是什么",
		"Tetr.io也很好玩!",
		"Tetr.js也很好玩!",
		"Tetralegends也很好玩!",
		"uid:225238922",
		"VVVVVV好玩!",
		"Xspin是个啥玩意",
		"Z块等身抱枕来一个(x",
		"ZS JL T O I",
		-- "Z酱 可爱!",
	}
elseif setting.lang==3 then
	L={
		":pog:",
		"(RUR'U')R'FR2U'R'U'(RUR'F')",
		'Free block game with royale mode"',
		"\\jezevec/\\jezevec/\\jezevec/",
		"\\osk/\\osk/\\osk/",
		"↑↑↓↓←→←→BABA",
		"1, 2, ⑨!!!!!",
		"11renPC!",
		"2.7182818284590452353",
		"2^2=Miya",
		"20G actually is a brand new game rule",
		"225238922  Bilibili cheers!",
		"3.1415926535897932384",
		"4+4+4+4+2+2+1=17",
		"40L WR: 15.654s",
		"少女祈禱中",
		"ALLSPIN!",
		"Also try 15puzzle",
		"Also try Cultris II!",
		"Also try Jstris!",
		"Also try Minecraft",
		"Also try Minesweeper",
		"Also try Nullpomino!",
		"Also try OSU",
		"Also try Phigros",
		"Also try Rubik's cube",
		"Also try Terraria",
		"Also try Tetr.io!",
		"Also try Tetr.js!",
		"Also try Tetralegends",
		"Also try VVVVVV!",
		"Am G F G",
		"Any suggestions to author!",
		"B2B2B???",
		"Back to Back 10 combo Techrash PC!",
		"COOL!!",
		"Diao so bully",
		"Disappearing doesn't mean useless",
		"Do not play game in class!",
		"Do not playing too long without having a break!",
		"Don't look directly at the bugs!",
		"DT cannon=TSD+TST",
		"e^(pi*i)=-1",
		"e^(pi*i/2)=i",
		"Enjoy Tech. Rotation System!",
		"Find out what's in the setting!",
		'Have you noticed what does "rotating" do to block?',
		"Headphones for better experience",
		"Hello world!",
		"Initial Rotation etc. can save your life",
		"Is B2B2B2B possible?",
		"l-=-1",
		"Let-The-Bass-Kick!",
		"Lower fps causes lower game experience",
		"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
		"Lua No.1",
		"Miya so cute!",
		"Miya:Nya!",
		"Not animation,real loading!",
		"Nothing will happen when some special day come",
		"O spin triple!",
		"OHHHHHHHHHHHHHH",
		"Only offline game now",
		"Powered by love2d",
		"REGRET!!",
		"Secret num:626",
		"Small DAS&ARR can make you faster,if you can control block correctly",
		"Switch music off if make you awful",
		"Techmino has a Nspire-CX edition!",
		"Techmino is so fun!",
		"Techmino=Technique+Tetromino",
		"This game can be very hard,be mentally perpared",
		"This in not a casual game",
		"Try to use two rotate button,three better",
		"Warning: Programmer Art",
		"What about 20 PCs?",
		"What about 23 PCs in 100 lines?",
		"What about 26 TSDs?",
		"Who is diao",
		"wwwwww",
		"You are Grand Master",
		"You can open saving directory from stat. page",
		"You can set orientation for each block",
		"ZS JL T O I",
	}
elseif setting.lang==4 then
	L={'!','@','#','$','%','^','&','*','(',')','-','=','_','+','[',']','{','}','\\','|',';',':','\'','"',',','<','.','>','/','?'}
	local s=""
	for i=1,math.random(16,26)do
		s=s..L[math.random(#L)]
	end
	return s
elseif setting.lang==5 then
	local R=math.random()
	if R<.05 then
		local time={
			--[[00]]"大半夜的在这干啥呢?不睡觉是会猝死的",
			--[[01]]"大半夜的在这干啥呢?不睡觉是会猝死的",
			--[[02]]"现在打块你是认真的?",
			--[[03]]"现在打块你是认真的?",
			--[[04]]"早起是好的,但是你不应该打块",
			--[[05]]"早起是好的,但是你不应该打块",
			--[[06]]"早饭吃好了?",
			--[[07]]"早饭吃好了?",
			--[[08]]"九点多了,没自己的事情要做?",
			--[[09]]"十点多了,没自己的事情要做?",
			--[[10]]"十一点多了,午饭有的吃么",
			--[[11]]"十二点多了,午饭有的吃么",
			--[[12]]"累了累了,现在不想说你",
			--[[13]]"累了累了,现在不想说你",
			--[[14]]"累了累了,现在不想说你",
			--[[15]]"累了累了,现在不想说你",
			--[[16]]"累了累了,现在不想说你",
			--[[17]]"晚饭吃好了?",
			--[[18]]"晚饭吃好了?",
			--[[19]]"累了累了,现在不想说你",
			--[[20]]"累了累了,现在不想说你",
			--[[21]]"好睡了,作息健康活得久",
			--[[22]]"好睡了,作息健康活得久",
			--[[23]]"大半夜的在这干啥呢?不睡觉是会猝死的",
		}
		return time[tonumber(os.date("%H"))+1]
	elseif R<.1 then
		local int=math.floor
		L={
			"平均"..int(stat.row/stat.time*60).."LPM,那可真强呢",
			"平均"..int(stat.atk/stat.time*60).."APM,好厉害哦",
			"平均"..(int(stat.atk/stat.row*10)*.1).."效,你看这数据能看么",
			"平均"..(int(stat.atk/stat.row*10)*.1).."效,我就不说你多菜了",
			"才玩了"..stat.game.."把,跟几十万局的没法比",
			"才玩了"..stat.game.."把,玩了不下几万局的人可不在少数",
			"才玩了"..int(stat.time/3600).."小时,人家总时长是你不知道多少倍",
			"才玩了"..int(stat.time/3600).."小时,别人总时长跟你都不在一个数量级",
		}
	else
		L={
			"0202年了,还在玩这种小孩子玩的游戏?",
			"100apm?定式刷的吧。",
			"20连pc不是随手?",
			"20G很难?是个人都能玩吧。",
			"25TSD不难吧。",
			"3pps不是人均水平?",
			"40行还要40多秒,就这?",
			"60LPM?拍硬降刷的吧。",
			"别会个c4w就以为自己多强,这是基本功罢了。",
			"不会吧不会吧,真的还有人不能随手Tspin?",
			"除了雨宫太阳你还认识谁?Jonas知道吗?Ajanba听过吗?",
			"还搁这玩手机呢,作业做完了?",
			"极限20G不是随手通?",
			"叫你多练就多练,想着几天变神仙,当自己是谁?",
			"叫你多练消四不听,现在要速度没速度,spin打完地形一塌糊涂,开心了?",
			"满口PCDT信天翁,还会点别的么?",
			"没那水平别天天整什么花里胡哨的,人玩几年你想几天赶上?",
			"全隐40行全消四很难吗??",
			"人只用一只手都能玩,你呢?",
			"少玩点,多眨眼,到时候瞎了别怪我没提醒你",
			"设置都看过一遍了吗?明明都能调还嫌这嫌那,可牛逼了您",
			"天天催更催更,你咋不来帮忙开发啊,真以为作者很强催催啥都有?",
			"天天卖弱,你一定把把150apm吧?",
			"天天F3F3,怕别人不知道你菜?",
			"我曾经在极度愤怒的时候15秒消了40行",
			"我一个滑铲就挖了个11renPC",
			"一口一个wtcl还不赶紧去练,你是不思进取还是不想好好说话?",
			"隐形难吗?那个节目上的谁,水平那么菜也打得还行,就是你菜",
		}
	end
end
return L[math.random(#L)]