function love.conf(t)
    local X=nil
    t.identity="Techmino"--The name of the save directory (string)
    t.appendidentity=X--Search files in source directory before save directory (boolean)
    t.version="11.2"
    t.console=X
    t.accelerometerjoystick=X--Enable the accelerometer on iOS and Android by exposing it as a Joystick (boolean)
    t.externalstorage=X
    t.gammacorrect=true
--	t.audio.mixwithsystem=true--Keep background music playing when opening LOVE (boolean, iOS and Android only)

    t.window.title="Techmino"
    t.window.icon="/image/icon.png"
    t.window.width=1000
    t.window.height=600
    t.window.borderless=X
    t.window.resizable=true
    t.window.minwidth=500
    t.window.minheight=300
    t.window.fullscreen=X
    t.window.fullscreentype="desktop"--Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
    t.window.vsync=0
    t.window.msaa=0--The number of samples to use with multi-sampled antialiasing (number)
    t.window.depth=nil--The number of bits per sample in the depth buffer
    t.window.stencil=nil--The number of bits per sample in the stencil buffer
    t.window.display=1--Index of the monitor to show the window in (number)
    t.window.highdpi=X--Enable high-dpi mode for the window on a Retina display (boolean)
    t.window.x=nil
    t.window.y=nil
	
    t.modules.audio=true
    t.modules.data=true
    t.modules.event=true
    t.modules.font=true
    t.modules.graphics=true
    t.modules.image=true
    t.modules.joystick=X
    t.modules.keyboard=true
    t.modules.math=true
    t.modules.mouse=true
    t.modules.physics=X
    t.modules.sound=true
    t.modules.system=true
    t.modules.thread=X
    t.modules.timer=true
    t.modules.touch=X
    t.modules.video=X
    t.modules.window=true
end