name: 'build iOS'
description: 'build iOS package'
inputs:
  name:
    required: true
    description: "Version name"
  type:
    required: true
    description: "Build type"
  APPLE_API_ID:
    required: true
    description: "API key ID"
  APPLE_API_ISSUER:
    required: true
    description: "API issuer ID"
  APPLE_API_KEY:
    required: true
    description: "API key content"
  APPLE_APP_BUILD:
    required: true
    description: "Build number"
  APPLE_APP_CHANGELOG:
    required: true
    description: "Changelog"
  APPLE_APP_ID:
    required: true
    description: "AppStore Apple ID"
  APPLE_APP_IDENTIFIER:
    required: true
    description: "Bundle ID"
  APPLE_APP_PROFILE:
    required: true
    description: "Provisioning Profile specifer"
  APPLE_KEYCHAIN_NAME:
    required: true
    description: "Temporary keychain name"
  APPLE_KEYCHAIN_PWD:
    required: true
    description: "Temporary keychain password"
  FASTLANE_DISCORD_WEBHOOK:
    required: true
    description: "Fastlane Discord webhook"
  FASTLANE_ACTION_ID:
    required: true
    description: "Fastlane Action ID"
  FASTLANE_MATCH_PWD:
    required: true
    description: "Fastlane Match description password"
  FASTLANE_MATCH_TOKEN:
    required: true
    description: "Fastlane Match Github token"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love
    - name: Checkout source codes
      uses: actions/checkout@v2
      with:
        repository: '26F-Studio/Techmino-iOS'
        path: 'Techmino-iOS'
    - name: Download CCloader
      uses: ./.github/actions/get-cc
      with:
        arch: iOS
    - name: Update source codes
      shell: bash
      run: |
        mv Techmino.love Techmino-iOS/platform/xcode
        mv libcold_clear.a Techmino-iOS/platform/xcode
        mv libCCloader.a Techmino-iOS/platform/xcode
    - name: Run fastlane
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: '${{ inputs.type }}'
        subdirectory: 'Techmino-iOS/platform/xcode'
      env:
          ACTION_ID: '${{ inputs.FASTLANE_ACTION_ID }}'
          API_ID: '${{ inputs.APPLE_API_ID }}'
          API_ISSUER: '${{ inputs.APPLE_API_ISSUER }}'
          API_KEY: '${{ inputs.APPLE_API_KEY }}'
          APP_BUILD: '${{ inputs.APPLE_APP_BUILD }}'
          APP_CHANGELOG: '${{ inputs.APPLE_APP_CHANGELOG }}'
          APP_ID: '${{ inputs.APPLE_APP_ID }}'
          APP_IDENTIFIER: '${{ inputs.APPLE_APP_IDENTIFIER }}'
          APP_PROFILE: '${{ inputs.APPLE_APP_PROFILE }}'
          APP_VERSION: '${{ inputs.name }}'
          DISCORD_WEBHOOK: '${{ inputs.FASTLANE_DISCORD_WEBHOOK }}'
          KEYCHAIN_NAME: '${{ inputs.APPLE_KEYCHAIN_NAME }}'
          KEYCHAIN_PWD: '${{ inputs.APPLE_KEYCHAIN_PWD }}'
          MATCH_PASSWORD: '${{ inputs.FASTLANE_MATCH_PWD }}'
          MATCH_TOKEN: '${{ inputs.FASTLANE_MATCH_TOKEN }}'
    - name: Move ipa
      shell: bash
      run: |
        mv Techmino-iOS/platform/xcode/Techmino.ipa Techmino.ipa
        