name: 'build iOS'
description: 'build iOS package'
inputs:
  name:
    required: true
  MACOS_CERTIFICATE:
    required: true
  MACOS_CERTIFICATE_ID:
    required: true
  MACOS_CERTIFICATE_PWD:
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love

    - name: Download template
      uses: ./.github/actions/get-unzip
      with:
        url: https://github.com/26F-Studio/Techmino-CI-template/releases/download/1.0/Techmino-iOS.zip

    - name: Download ColdClear
      uses: ./.github/actions/get-cc
      with:
        arch: iOS

    # - name: Modify template
    #   shell: bash
    #   run: |
    #     plutil -convert xml1 ./Techmino.app/info.plist
    #     python3 .github/workflows/updateVersion.py -T iOS -N ${{ inputs.name }}
    #     plutil -convert binary1 ./Techmino.app/info.plist
    #     mv Techmino.love Techmino.app
    #     mv CCloader.dylib Techmino.app
    #     chmod +x CCloader.dylib
    #     chmod +x Techmino
    #     chmod +x Techmino.love

    - name: Create and config keychain
      shell: bash
      run: |
        echo ${{ inputs.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
        security create-keychain -p Techminohaowan build.keychain
        security default-keychain -s build.keychain
        security import certificate.p12 -k build.keychain -P ${{ inputs.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
        security import certificate.p12 -k build.keychain -P ${{ inputs.MACOS_CERTIFICATE_PWD }} -T /usr/bin/xcodebuild
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k Techminohaowan build.keychain

    - name: Build project
      shell: bash
      run: |
        security unlock-keychain -p Techminohaowan build.keychain
        xcodebuild -project Techmino-iOS/platform/xcode/Techmino.xcodeproj -scheme Techmino -configuration Distribution PROVISIONING_PROFILE_SPECIFIER=${{ inputs.MACOS_CERTIFICATE_ID }}

    - name: Codesign executable
      # In secrets:
      #   - MACOS_CERTIFICATE: the *.p12 Developer ID Certificate, encoded in base64
      #   - MACOS_CERTIFICATE_PWD: The password
      shell: bash
      run: |
        security unlock-keychain -p Techminohaowan build.keychain
        /usr/bin/codesign --force --deep -s ${{ inputs.MACOS_CERTIFICATE_ID }} Techmino.app -v

    - name: Rename and Pack app
      shell: bash
      run: |
        mkdir Techmino-iOS
        mv Techmino.app Techmino-iOS/Techmino.app
