name: 'build iOS'
description: 'build iOS package'
inputs:
  name:
    required: true
  AAPPLE_DEV_ACCOUNT:
    required: true
  APPLE_DEV_PASSWORD:
    required: true
  IOS_CERTIFICATE:
    required: true
  IOS_CERTIFICATE_ID:
    required: true
  IOS_CERTIFICATE_PWD:
    required: true
  IOS_PROFILE:
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love

    - name: Checkout source codes
      uses: actions/checkout@v2
      with:
        repository: '26F-Studio/Techmino-iOS'
        path: 'Techmino-iOS'

    - name: Download CCloader
      uses: ./.github/actions/get-cc
      with:
        arch: iOS

    - name: Create and config keychain
      shell: bash
      run: |
        security create-keychain -p "" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings
        security import <(echo ${{inputs.IOS_CERTIFICATE}} | base64 --decode) \
          -f pkcs12 \
          -k build.keychain \
          -P ${{inputs.IOS_CERTIFICATE_PWD}} \
          -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

    - name: Import provisioning profile
      shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{inputs.IOS_PROFILE}}" | base64 --decode > \
          ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: Sign CCloader
      shell: bash
      run: |
        codesign --force -s ${{ inputs.MACOS_CERTIFICATE_ID }} ios.app -v

    - name: Update source codes
      shell: bash
      run: |
        mv Techmino.love Techmino-iOS/platform/xcode
        mv CCloader.dylib Techmino-iOS/platform/xcode
        python3 .github/workflows/updateVersion.py -T iOS -N ${{ inputs.name }}

    - name: Build project
      shell: bash
      run: |
        mkdir Techmino-iOS/Build
        xcodebuild -project Techmino-iOS/platform/xcode/Techmino.xcodeproj \
          -scheme Techmino \
          -configuration Distribution \
          -quiet \
          CONFIGURATION_BUILD_DIR=Build

    - name: Pack bare app
      shell: bash
      run: |
        mv Techmino-iOS/platform/xcode/Build/Techmino.app ./
        zip -r -y Techmino.zip Techmino.app