name: 'build iOS'
description: 'build iOS package'
inputs:
  name:
    required: true
  type:
    required: true
  DEVELOPER_APP_ID:
    required: true
  DEVELOPER_APP_IDENTIFIER:
    required: true
  FASTLANE_APPLE_ID:
    required: true
  MATCH_PASSWORD:
    required: true
  GIT_AUTHORIZATION:
    required: true
  PROVISIONING_PROFILE_SPECIFIER:
    required: true
  TEMP_KEYCHAIN_PASSWORD:
    required: true
  TEMP_KEYCHAIN_USER:
    required: true
  APPLE_KEY_ID:
    required: true
  APPLE_ISSUER_ID:
    required: true
  APPLE_KEY_CONTENT:
    required: true
  PROJECT_BUILD_NUMBER:
    required: true
  PILOT_CHANGE_LOG:
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love
    - name: Checkout source codes
      uses: actions/checkout@v2
      with:
        repository: '26F-Studio/Techmino-iOS'
        path: 'Techmino-iOS'
    - name: Download CCloader
      uses: ./.github/actions/get-cc
      with:
        arch: iOS
    - name: Update source codes
      shell: bash
      run: |
        mv Techmino.love Techmino-iOS/platform/xcode
        mv libcold_clear.a Techmino-iOS/platform/xcode
        mv libCCloader.a Techmino-iOS/platform/xcode
        python3 .github/workflows/updateVersion.py -T iOS -N ${{ inputs.name }}
    - name: Run fastlane
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: '${{ inputs.type }}'
        subdirectory: 'Techmino-iOS/platform/xcode'
      env:
          DEVELOPER_APP_ID: '${{ inputs.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ inputs.DEVELOPER_APP_IDENTIFIER }}'
          FASTLANE_APPLE_ID: '${{ inputs.FASTLANE_APPLE_ID }}'
          MATCH_PASSWORD: '${{ inputs.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ inputs.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ inputs.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ inputs.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ inputs.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ inputs.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ inputs.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ inputs.APPLE_KEY_CONTENT }}'
          PROJECT_BUILD_NUMBER: '${{ inputs.PROJECT_BUILD_NUMBER }}'
          PILOT_CHANGE_LOG: '${{ inputs.PILOT_CHANGE_LOG }}'
    - name: Move ipa
      shell: bash
      run: |
        mv Techmino-iOS/platform/xcode/Techmino.ipa Techmino.ipa
        