name: 'get and unzip'
description: 'cURL and then 7-zip x'
inputs:
  url:
    required: true
  dir:
    required: false
    default: '.'
  temp-file:
    required: false
    default: temp.zip
runs:
  using: "composite"
  steps:
    - run: curl -L ${{ inputs.url }} -o ${{ inputs.temp-file }}
      shell: bash
    - run: 7z x ${{ inputs.temp-file }} -o${{ inputs.dir }}
      shell: bash
