name: 'get and unzip'
description: 'cURL and then 7-zip x'
inputs:
  url:
    required: true
  dir:
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - run: curl -L ${{ inputs.url }} -o temp.zip
      shell: bash
    - run: 7z x temp.zip -o${{ inputs.dir }}
      shell: bash
