name: 'build Mac OS'
description: 'build Mac OS package'
inputs:
  cc-url:
    required: true
  name:
    required: true
  icon:
    required: true
  MACOS_CERTIFICATE:
    required: true
  MACOS_CERTIFICATE_PWD:
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love
    - name: Download template
      uses: ./.github/actions/get-unzip
      with:
        url: https://github.com/26F-Studio/Techmino/releases/download/v0.15.1/Techmino.app.zip
    - name: Download ColdClear
      uses: ./.github/actions/get-unzip
      with:
        url: ${{ inputs.cc-url }}
    - name: Modify template
      shell: bash
      run: |
        python3 .github/workflows/updateVersion.py -T macOS -N ${{ inputs.name }}
        mv Techmino.love Techmino.app/Contents/Resources
        mv CCloader.dylib Techmino.app/Contents/Frameworks
        mv ${{ inputs.icon }} Techmino.app/Contents/Resources/iconfile.icns
    - name: Codesign executable
      # In secrets:
      #   - MACOS_CERTIFICATE: the *.p12 Developer ID Certificate, encoded in base64
      #   - MACOS_CERTIFICATE_PWD: The password
      shell: bash
      run: |
        echo ${{ inputs.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
        security create-keychain -p Techminohaowan build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p Techminohaowan build.keychain
        security import certificate.p12 -k build.keychain -P ${{ inputs.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k Techminohaowan build.keychain
        /usr/bin/codesign --force --deep -s 79B81FC5EA155243C973B5417B0996501F00EF55 Techmino.app -v
