name: 'build Mac OS'
description: 'build Mac OS package'
inputs:
  name:
    required: true
  icon:
    required: true
  TEMP_KEYCHAIN_PASSWORD:
    required: true
  TEMP_KEYCHAIN_USER:
    required: true
  APPLE_KEY_ID:
    required: true
  APPLE_ISSUER_ID:
    required: true
  APPLE_KEY_CONTENT:
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/build-love
    - name: Checkout template
      uses: actions/checkout@v2
      with:
        repository: '26F-Studio/Techmino-macOS'
        path: 'Techmino-macOS'
    - name: Download ColdClear
      uses: ./.github/actions/get-cc
      with:
        arch: macOS
    - name: Run fastlane
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'sign'
        subdirectory: 'Techmino-macOS'
      env:
          TEMP_KEYCHAIN_PASSWORD: '${{ inputs.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ inputs.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ inputs.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ inputs.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ inputs.APPLE_KEY_CONTENT }}'
    - name: Modify template
      shell: bash
      run: |
        python3 .github/workflows/updateVersion.py -T macOS -N ${{ inputs.name }}
        mv Techmino.love Techmino.app/Contents/Resources
        mv CCloader.dylib Techmino.app/Contents/Frameworks
        mv ${{ inputs.icon }} Techmino.app/Contents/Resources/iconfile.icns
    - name: Codesign executable
    
      # In secrets:
      #   - MACOS_CERTIFICATE: the *.p12 Developer ID Certificate, encoded in base64
      #   - MACOS_CERTIFICATE_PWD: The password
      shell: bash
      run: |
        security unlock-keychain -p ${{ inputs.TEMP_KEYCHAIN_PASSWORD }} ${{ inputs.TEMP_KEYCHAIN_USER }}.keychain
        /usr/bin/codesign --force --deep -s ${{ inputs.MACOS_CERTIFICATE_ID }} Techmino.app -v
        security delete-keychain build.keychain
