local langList={
	{
		back="返回",
		anykey="按任意键继续",
		newVersion="感谢更新!更新内容如下",
		httpTimeout="网络连接超时!",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		holdR="长按以重新开始",

		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain="剩余 $1 名玩家",
		cmb={nil,"1 Combo","2 Combo","3 Combo","4 Combo","5 Combo","6 Combo","7 Combo","8 Combo","9 Combo","10 Combo!","11 Combo!","12 Combo!","13 Combo!","14 Combo!","15 Combo!","16 Combo!","17 Combo!","18 Combo!","19 Combo!","MEGACMB"},
		block=nil,spin="-spin ",
		clear={"single","double","triple","Techrash","Techrach+"},
		mini="Mini",b2b="B2B ",b3b="B2B2B ",
		PC="Perfect Clear",HPC="Half Clear",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage="关卡 $1",
		great="Great!",
		awesome="Awesome.",
		almost="Almost!",
		continue="Continue.",
		maxspeed="最高速度",
		speedup="速度加快",
		missionFailed="非任务消除",

		win="胜利",
		finish="完成",
		gameover="游戏结束",
		pause="暂停",
		pauseCount="暂停统计",
		finesse_ap="All Perfect",
		finesse_fc="Full Combo",

		snapLevelName={"无吸附","10px吸附","20px吸附","40px吸附","60px吸附","80px吸附"},
		page="页面:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		ai_mission="不能同时开启AI和自定义任务",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",
		switchSpawnSFX="请开启方块出生音效",
		getRank="本局评级:",
		ranks={"D","C","B","A","S"},

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		pasteSuccess="粘贴成功",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		getNoticeFail="拉取公告失败",
		getVersionFail="检测新版本失败",
		versionIsNew="游戏已是最新版本",
		versionIsOld="最新版本$1可以下载了!",
		registerSuccessed="注册成功!",
		registerFailed="注册失败",
		netErrorCode="网络错误码",
		noUsername="请填写用户名",
		noPassword="请填写密码",
		diffPassword="两次密码不一致",
		errorMsg="Techmino遭受了雷击,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"Spin:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"ADPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spin0~3",
			clear="clear1~4",
			"游戏运行次数:",
			"游戏局数:",
			"游戏时间:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"满贯/大满贯:",
			"全/半清:",
			"多余操作/极简率:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"使用LOVE2D引擎",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1127702001进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序: MrZ, FinnTenzor",
			"美术: MrZ, (T0722, Gnyar)",
			"音乐: MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM 测试: 思竣",
			"英文文案: User670 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear [MinusKelvin]
			json.lua [rxi]
			profile.lua [itraykov]
			simple-love-lights [dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1127702001",
		WidgetText={
			main={
				play="开始",
				custom="自定义",
				qplay="快速开始",
				stat="统计信息",
				help="帮助",
				setting="设置",
				lang="言/A",
				music="音乐室",
				account="账户",
				sound="音效室",
				minigame="小游戏",
				quit="退出",
			},
			mode={
				start="开始",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				title="游戏设置",
				graphic="←画面设置",
				sound="声音设置→",

				ctrl="控制设置",
				key="键位设置",
				touch="触屏设置",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				appLock="软件锁(密码626)",
				calc="软件锁",
			},
			setting_video={
				title="画面设置",
				sound="←声音设置",
				game="游戏设置→",

				block="方块可见",
				ghost="阴影透明度",
				center="旋转中心透明度",

				smooth="平滑下落",
				grid="网格",
				bagLine="包分界线",

				lockFX="锁定特效等级",
				dropFX="下落特效等级",
				moveFX="移动特效等级",
				clearFX="消除特效等级",
				shakeFX="晃动特效等级",
				atkFX="攻击特效等级",
				frame="绘制帧率",

				text="消行文本",
				score="分数动画",
				warn="死亡预警",
				highCam="超屏视野",
				nextPos="生成预览",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
			},
			setting_sound={
				title="声音设置",
				game="←游戏设置",
				graphic="画面设置→",

				sfx="音效",
				stereo="立体声",
				spawn="方块生成",
				bgm="音乐",
				vib="振动",
				voc="语音",
			},
			setting_control={
				title="控制设置",
				preview="预览",

				das="DAS",arr="ARR",
				sddas="软降DAS",sdarr="软降ARR",
				ihs="提前Hold",
				irs="提前旋转",
				ims="提前移动",
				reset="重置",
			},
			setting_key={
				keyboard="键盘",
				joystick="手柄",
				help="方向键选择/翻页,回车/空格修改,esc返回",
			},
			setting_skin={
				title="外观设置",
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="重置配色",
				faceR="重置方向",
			},
			setting_touch={
				default="默认组合",
				snap="吸附",
				option="选项",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="顺时针旋转:",	b4="逆时针旋转:",
				b5=	"180°旋转:",b6="硬降:",		b7="软降:",			b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				norm="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
			},
			setting_trackSetting={
				VKDodge="自动避让",
			},
			customGame={
				title="自定义游戏",
				subTitle="基本",
				defSeq="默认序列",
				noMsn="无任务",

				drop="下落延迟",
				lock="锁定延迟",
				wait="出块等待",
				fall="消行延迟",

				bg="背景",
				bgm="音乐",

				copy="复制场地+序列+任务",
				paste="粘贴场地+序列+任务",
				clear="开始-消除",
				puzzle="开始-拼图",

				advance="更多设置(A)",
				field="场地编辑(F)",
				sequence="序列编辑(S)",
				mission="任务编辑(M)",
			},
			custom_advance={
				title="自定义游戏",
				subTitle="高级",

				next="Next",hold="Hold",oncehold="Hold一次",
				block="方块可见",
				ghost="阴影透明度",
				center="中心透明度",
				bagLine="包分界线",
				highCam="超屏视野",
				nextPos="生成预览",
				bone="骨块",

				mindas="最小DAS",
				minarr="最小ARR",
				minsdarr="最小软降ARR",
				noTele="禁止瞬移",
				ospin="O-spin",
				target="目标行数",
				visible="能见度",
				freshLimit="锁延刷新限制",
				easyFresh="普通刷新锁延",
				fineKill="强制极简",
				opponent="对手",
				life="命数",
				pushSpeed="上涨速度",
			},
			custom_field={
				title="自定义游戏",
				subTitle="场地",

				b12="[  ]",
				any="不定",
				space="×",
				copy="复制",
				paste="粘贴",
				clear="清除",
				pushLine="增加一行(K)",
				delLine="消除行(L)",
				demo="不显示×",
			},
			custom_sequence={
				title="自定义游戏",
				subTitle="序列",

				sequence="序列",

				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
			},
			custom_mission={
				title="自定义游戏",
				subTitle="任务",

				_1="1",_2="2",_3="3",_4="4",
				any1="any1",any2="any2",any3="any3",any4="any4",
				PC="PC",
				Z1="Z1",S1="S1",J1="J1",L1="L1",T1="T1",O1="O1",I1="I1",
				Z2="Z2",S2="S2",J2="J2",L2="L2",T2="T2",O2="O2",I2="I2",
				Z3="Z3",S3="S3",J3="J3",L3="L3",T3="T3",O3="O3",I3="I3",
				O4="O4",I4="I4",
				left="←",right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				mission="强制任务",
			},
			music={
				title="音乐室",
				arrow="→",
				now="正在播放:",

				bgm="BGM",
				up="↑",
				play="播放",
				down="↓",
			},
			help={
				dict="小Z词典",
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
			},
			dict={
				title="小Z方块词典",
				keyboard="键盘",
				link="打开链接",
				up="↑",
				down="↓",
			},
			staff={
			},
			stat={
				path="打开存储目录",
			},
			login={
				title="登录/注册",
				username="用户名",
				email="邮箱",
				code="邀请码",
				password="密码",
				password2="确认密码",
			},
			account={
				title="账户",
			},
			sound={
				title="音效室",
				move="移动",
				lock="锁定",
				drop="硬降",
				fall="行落下",
				rotate="旋转",
				rotatekick="旋转进洞",
				hold="Hold",
				prerotate="提前旋转",
				prehold="提前Hold",

				_1="消1",
				_2="消2",
				_3="消3",
				_4="消4",
				spin0="spin 0",
				spin1="spin 1",
				spin2="spin 2",
				spin3="spin 3",

				z0="Z-spin",
				z1="Z-spin 1",
				z2="Z-spin 2",
				z3="Z-spin 3",
				s0="S-spin",
				s1="S-spin 1",
				s2="S-spin 2",
				s3="S-spin 3",

				j0="J-spin",
				j1="J-spin 1",
				j2="J-spin 2",
				j3="J-spin 3",
				l0="L-spin",
				l1="L-spin 1",
				l2="L-spin 2",
				l3="L-spin 3",

				t0="T-spin",
				t1="T-spin 1",
				t2="T-spin 2",
				t3="T-spin 3",
				o0="O-spin",
				o1="O-spin 1",
				o2="O-spin 2",
				o3="O-spin 3",

				i0="I-spin",
				i1="I-spin 1",
				i2="I-spin 2",
				i3="I-spin 3",

				mini="Mini",
				b2b="B2B",
				b3b="B3B",
				pc="PC",
			},
			minigame={
				p15="15 Puzzle",
				schulte_G="舒尔特方格",
				pong="Pong",
			},
			p15={
				reset="打乱",
				color="颜色",
				blind="盲打",
				slide="滑动操作",
				pathVis="路径显示",
				revKB="键盘反向",
			},
			schulte_G={
				reset="重来",
				rank="尺寸",
				blind="盲打",
				disappear="消失",
				tapFX="点击动画",
			},
			pong={
				reset="重置",
			},
			debug={
				copyLog="复制日志",
				scrInfo="输出屏幕信息",
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10L",		"消除10行"},
			["sprint_20"]=			{"竞速",		"20L",		"消除20行"},
			["sprint_40"]=			{"竞速",		"40L",		"消除40行"},
			["dig_10"]=				{"挖掘",		"10L",		"挖掘10行"},
			["dig_40"]=				{"挖掘",		"40L",		"挖掘40行"},
			["dig_100"]=			{"挖掘",		"100L",		"挖掘100行"},
			["dig_400"]=			{"挖掘",		"400L",		"挖掘400行"},
			["dig_1000"]=			{"挖掘",		"1000L",	"挖掘1000行"},
			["sprint_100"]=			{"竞速",		"100L",		"消除100行"},
			["sprint_400"]=			{"竞速",		"400L",		"消除400行"},
			["sprint_1000"]=		{"竞速",		"1000L",	"消除1000行"},
			["drought_normal"]=		{"干旱",		"100L",		"你I没了"},
			["drought_lunatic"]=	{"干旱",		"100L",		"后 妈 发 牌"},
			["marathon_normal"]=	{"马拉松",		"普通",		"200行加速马拉松"},
			["marathon_hard"]=		{"马拉松",		"困难",		"200行高速马拉松"},
			["marathon_ultimate"]=	{"马拉松",		"极限",		"禁止0连击单消之外的任何操作"},
			["solo_1"]=				{"单挑",		"简单",		"打败AI"},
			["solo_2"]=				{"单挑",		"普通",		"打败AI"},
			["solo_3"]=				{"单挑",		"困难",		"打败AI"},
			["solo_4"]=				{"单挑",		"疯狂",		"打败AI"},
			["solo_5"]=				{"单挑",		"极限",		"打败AI"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"49人混战,活到最后"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"49人混战,活到最后"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"49人混战,活到最后"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"99人混战,活到最后"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"99人混战,活到最后"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"99人混战,活到最后"},
			["round_1"]=			{"回合制",		"简单",		"下棋模式"},
			["round_2"]=			{"回合制",		"普通",		"下棋模式"},
			["round_3"]=			{"回合制",		"困难",		"下棋模式"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋模式"},
			["round_5"]=			{"回合制",		"极限",		"下棋模式"},
			["master_beginner"]=	{"大师",		"疯狂",		"20G初心者练习"},
			["master_advance"]=		{"大师",		"极限",		"上级者20G挑战"},
			["master_final"]=		{"大师",		"终点",		"究极20G:无法触及的终点"},
			["GM"]=					{"宗师",		"GM",		"成为方块大师"},
			["blind_easy"]=			{"隐形",		"半隐",		"不强大脑"},
			["blind_normal"]=		{"隐形",		"全隐",		"挺强大脑"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"很强大脑"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"最强大脑"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"高速经典"},
			["survivor_easy"]=		{"生存",		"简单",		"你能存活多久?"},
			["survivor_normal"]=	{"生存",		"普通",		"你能存活多久?"},
			["survivor_hard"]=		{"生存",		"困难",		"你能存活多久?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"你能存活多久?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"你能存活多久?"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"C4W练习",		"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"C4W练习",		"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"简易PC题库,熟悉全清定式的组合"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"简易PC题库,熟悉全清定式的组合"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷PC"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷PC"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷PC"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal2"]=		{"科研",		"普通+",	"仅允许spin与PC"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard2"]=			{"科研",		"困难+",	"仅允许spin与PC"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic2"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse2"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"TSD挑战",		"简单",		"你能连续做几个TSD?"},
			["tsd_hard"]=			{"TSD挑战",		"困难",		"你能连续做几个TSD?"},
			["tsd_ultimate"]=		{"TSD挑战",		"极限",		"你能连续做几个TSD?"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"在两分钟内尽可能拿到最多的分数"},
			["infinite"]=			{"无尽",		"",			"沙盒"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"挖呀挖呀挖"},
			["custom_clear"]=		{"自定义",		"普通",		"画点什么然后把它消除!"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"画点什么然后把它拼出来吧!"},
			["sprintFix"]=			{"竞速",		"无移动",	"这是可能的。"},
			["sprintLock"]=			{"竞速",		"无旋转",	"这不可能。"},
			["sprintPenta"]=		{"竞速",		"五连块",	"伤脑筋十八块"},
			["sprintMPH"]=			{"竞速",		"MPH",		"纯随机\n无预览\n无暂存"},
		},
		getTip={
			'注意到"旋转"到底对方块做了些什么吗?',
			"(RUR'U')R'FR2U'R'U'(RUR'F')",
			"↑↑↓↓←→←→BA",
			"1, 2, ⑨!!!!!",
			"100行内23PC来一个?",
			"11renPC!",
			"15puzzle好玩!",
			"2.7182818284590452353",
			"2+2=Miya",
			"20连PC来一个?",
			"20G本质是一套全新的游戏规则!",
			"25种方块都能spin你敢信?",
			"26连T2来一个?",
			"3.1415926535897932384",
			"40行世界纪录:15.654s",
			"626r/s",
			"7宽三SZ架空捐了解一下",
			"把手机调到特殊的日期也不会发生什么的(真的",
			"报时机器人:新的一天开始了",
			"本游戏可不是休闲游戏。",
			"本游戏难度上限很高,做好心理准备。",
			"必须要软降才能到达的位置都会判定为极简操作",
			"别问游戏名怎么取的,问就是随便想的",
			"不是动画,真的在加载!",
			"不要盯着bug不放",
			"不要向不感兴趣的路人推荐!!!!!!!!",
			"不要在上课时玩游戏!",
			"草(日本语)",
			"茶娘 可爱!",
			"触摸板打osu是什么体验?",
			"打好块没有捷径,多练。",
			"大概还是有人会认真看tips的",
			"大满贯10连击消四全清!",
			"戴上耳机以获得最佳体验",
			"单手也能玩!",
			"低帧率会降低游戏体验",
			"俄罗斯方块环游记也不错!",
			"方块默认出现的方向都是重心在下哦",
			"方块研究所 有一个Nspire-CX版本!",
			"感觉自己明明按键了但是没反应?你真的按到了吗?",
			"感觉自己速度到上限了?试着去调下控制设置(如果没认真调过的话)",
			"感谢群友帮忙想了一大堆tips",
			"感谢Phigros,让我抄了一堆tips(",
			"给别人推荐本游戏的时候请记住我真的不叫铁壳米诺!!!",
			"更小的DAS和ARR拥有更高的操作上限(前提是你能控制得了)",
			"光敏性癫痫警告",
			"还能写些什么tip呢",
			"好好T旋,天天向上",
			"合群了就会消失,但是消失不代表没有意义",
			"很有精神!",
			"健康小贴士:不要熬夜,真的会猝死",
			"健康小贴士:玩游戏多眨眼,不然会干眼病",
			"键位是可以自定义的",
			"觉得移动速度太慢或太快,手感不好?快去设置调整DAS/ARR",
			"快去打一把100%极简看看能拿什么评价",
			"联网还没做呢,别急",
			"卖弱禁言警告",
			"没学过编曲,音乐都是自己凭感觉写的,觉得不好听就设置里关了吧",
			"每个块的出现方向可以自定义",
			"每个虚拟按键都可以隐藏/显示,尺寸也可调",
			"秘密数字:626",
			"免费吃鸡方块",
			"喵!",
			"魔方好玩!",
			"魔方也是方块(确信",
			"你的双手是为了你的一生服务的,而不是Techmino",
			"你今天的人品值是:0",
			"你今天的人品值是:26",
			"你今天的人品值是:62.6",
			"你今天的人品值是:99.626",
			"你可以从统计页面打开游戏存档目录",
			"你们考虑过Z酱的感受吗?没有!你们只考虑你自己。",
			"你准备好了吗?",
			"请不要一直看主页机器人玩",
			"请勿大力敲打设备!敲坏了就没有Techmino玩了",
			"去玩别的方块的时候记得没有Ospin!",
			"扫雷好玩!",
			"少女祈祷中",
			"适度游戏益脑,沉迷游戏伤身,合理安排时间,享受健康生活",
			"术语不认识?去帮助-词典里查查吧",
			"泰拉瑞亚好玩!",
			"提前旋转等设置可以用来救命",
			"玩到一半弹出消息框?快去设置禁止弹窗",
			"为了防止误触,玩到一半重开需要长按重开键",
			"为了收集Tips一直关游戏就没意思了,要的就是惊喜",
			"为什么关卡那么少啊!-因为你前一模式成绩连D都没有达到,再加把劲吧~",
			"我的世界好玩!",
			"我们的每一条tips都很正经(确信",
			"我们是不是第一个在方块游戏做tips的?",
			"无聊翻翻设置是好习惯",
			"希望极简率没事",
			"希望你们都能喜欢Z…哦不是,喜欢Techmino",
			"享受Tech的特色旋转系统!",
			"新人请千万记住,打好基础,不要太早学那些花里胡哨的。",
			"旋转不是变形!请尽量灵活利用顺逆时针两个旋转键!",
			"学会使用两个旋转键,三个更好",
			"学习能力很重要,无论是学校知识还是玩游戏",
			"音乐使用beepbox制作",
			"音游方块是一家(暴论",
			"应该没人会认真看tips吧?",
			"游戏使用love2d引擎制作",
			"游戏作者40行卡27秒好几个月了...",
			"有建议的话可以把信息反馈给作者~",
			"有疑问? 先看设置有没有你想要的",
			"在?为什么半夜打块?",
			"长时间游戏状态会越来越差!玩久了记得放松一下~",
			"这里的极简判定不松不严,放心软降,小心hold!",
			"ALLSPIN!",
			"Alt+F4=关闭当前窗口",
			"Alt+Tab=切换窗口",
			"Am G F G",
			"B2B2B???",
			"B2B2B2B存在吗?",
			"backspace=返回上一个文件目录",
			"BT炮=beta炮=TCM-β炮",
			"COOL!!",
			"Ctrl+鼠标滚轮=缩放",
			"Ctrl+A=全选",
			"Ctrl+Alt+Z=查看所有qq消息",
			"Ctrl+D=复制一份",
			"Ctrl+F=查找",
			"Ctrl+Tab=切换标签页",
			"Ctrl+W=关闭当前标签页",
			"Cultris II也很好玩!",
			"DT炮=TSD+TST炮",
			"e^(pi*i)=-1",
			"e^(pi*i/2)=i",
			"fin neo iso 是满足tspin条件的特殊t2的名字",
			"Jstris也很好玩!",
			"l-=-1",
			"Let-The-Bass-Kick!",
			"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
			"Lua天下第一",
			"Miya 可爱!",
			"Naki 可爱!",
			"Nullpomino也很好玩!",
			"O spin Triple!",
			"osu好玩!",
			"Phigros好玩!",
			"REGRET!!",
			"STSD必死",
			"techmino安卓下载",
			"Techmino好玩!",
			"Techmino没有抽卡没有氪金,太好玩了",
			"Techminohaowan",
			"TechOS?那是什么",
			"Tetr.io也很好玩!",
			"Tetr.js也很好玩!",
			"Tetralegends也很好玩!",
			"uid:225238922",
			"VVVVVV好玩!",
			"Xspin是个啥玩意",
			"Z酱累了,Z酱不想更新",
			"Z酱只是个写代码的,懂什么方块",
			"Z块等身抱枕来一个(x",
			"ZS JL T O I",
			-- "Z酱 可爱!",
		}
	},
	{
		back="返回",
		anykey="按任意键继续",
		newVersion="感谢更新!更新内容如下",
		httpTimeout="网络连接超时!",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		holdR="长按以重新开始",

		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain="剩余 $1 名玩家",
		cmb={nil,"1连击","2连击","3连击","4连击","5连击","6连击","7连击","8连击","9连击","10连击!","11连击!","12连击!","13连击!","14连击!","15连击!","16连击!","17连击!","18连击!","19连击!","巨型连击"},
		block=nil,spin="型回旋",
		clear={"单清","双清","三清","四清","五清"},
		mini="迷你",b2b="满贯",b3b="大满贯",
		PC="场地全清",HPC="场地半清",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage="关卡 $1",
		great="不错!",
		awesome="精彩。",
		almost="差一点!",
		continue="继续。",
		maxspeed="最高速度",
		speedup="速度加快",
		missionFailed="非任务消除",

		win="胜利",
		finish="完成",
		gameover="游戏结束",
		pause="暂停",
		pauseCount="暂停统计",
		finesse_ap="完美极简",
		finesse_fc="全连击",

		snapLevelName={"无吸附","10像素吸附","20像素吸附","40像素吸附","60像素吸附","80像素吸附"},
		page="页面:",

		ai_fixed="不能同时开启电脑玩家和固定序列",
		ai_prebag="不能同时开启电脑玩家和自定义序列",
		ai_mission="不能同时开启电脑玩家和自定义任务",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",
		switchSpawnSFX="请开启方块出生音效",
		getRank="本局评级:",
		ranks={"差","可","中","良","优"},

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		pasteSuccess="粘贴成功",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		getNoticeFail="拉取公告失败",
		getVersionFail="检测新版本失败",
		versionIsNew="游戏已是最新版本",
		versionIsOld="最新版本$1可以下载了!",
		registerSuccessed="注册成功!",
		registerFailed="注册失败",
		netErrorCode="网络错误码",
		noUsername="请填写用户名",
		noPassword="请填写密码",
		diffPassword="两次密码不一致",
		errorMsg="Techmino遭受了雷击,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"回旋:",
			"(大)满贯/全(半)清:",
			"非极简操作:",
		},
		radar={"防","守","攻","送","速","挖"},
		radarData={
			"防/分",
			"综/分",
			"攻/分",
			"送/分",
			"行/分",
			"挖/分",
		},
		stat={
			spin="回旋0~3",
			clear="消除1~4",
			"游戏运行次数:",
			"游戏局数:",
			"游戏时间:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"满贯/大满贯:",
			"全/半清:",
			"多余操作/极简率:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1127702001进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序: MrZ, FinnTenzor",
			"美术: MrZ, (T0722, Gnyar)",
			"音乐: MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM 测试: 思竣",
			"英文文案: User670 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear [MinusKelvin]
			json.lua [rxi]
			profile.lua [itraykov]
			simple-love-lights [dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1127702001",
		WidgetText={
			main={
				play="开始",
				custom="自定义",
				qplay="快速开始",
				stat="统计信息",
				help="帮助",
				setting="设置",
				lang="言/A",
				music="音乐室",
				account="账户",
				sound="音效室",
				minigame="小游戏",
				quit="退出",
			},
			mode={
				start="开始",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				title="游戏设置",

				graphic="←画面设置",
				sound="声音设置→",

				ctrl="控制设置",
				key="键位设置",
				touch="触屏设置",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				appLock="软件锁(密码626)",
				calc="软件锁",
			},
			setting_video={
				title="画面设置",

				sound="←声音设置",
				game="游戏设置→",

				block="方块可见",
				ghost="阴影透明度",
				center="旋转中心透明度",

				smooth="平滑下落",
				grid="网格",
				bagLine="包分界线",

				lockFX="锁定特效等级",
				dropFX="下落特效等级",
				moveFX="移动特效等级",
				clearFX="消除特效等级",
				shakeFX="晃动特效等级",
				atkFX="攻击特效等级",
				frame="绘制帧率",

				text="消行文本",
				score="分数动画",
				warn="死亡预警",
				highCam="超屏视野",
				nextPos="生成预览",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
			},
			setting_sound={
				title="声音设置",

				game="←游戏设置",
				graphic="画面设置→",

				sfx="音效",
				stereo="立体声",
				spawn="方块生成",
				bgm="音乐",
				vib="振动",
				voc="语音",
			},
			setting_control={
				title="控制设置",
				preview="预览",

				das="首次移动延迟",arr="移动重复延迟",
				sddas="首次软降延迟",sdarr="软降重复延迟",
				ihs="提前暂存",
				irs="提前旋转",
				ims="提前移动",
				reset="重置",
			},
			setting_key={
				keyboard="键盘",
				joystick="手柄",
				help="方向键选择/翻页,回车/空格修改,esc返回",
			},
			setting_skin={
				title="外观设置",

				prev="←",next="→",
				prev1="↑",next1="↓",spin1="转",
				prev2="↑",next2="↓",spin2="转",
				prev3="↑",next3="↓",spin3="转",
				prev4="↑",next4="↓",spin4="转",
				prev5="↑",next5="↓",spin5="转",
				prev6="↑",next6="↓",spin6="转",
				prev7="↑",next7="↓",spin7="转",
				skinR="重置配色",
				faceR="重置方向",
			},
			setting_touch={
				default="默认组合",
				snap="吸附",
				option="选项",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="顺时针旋转:",	b4="逆时针旋转:",
				b5=	"180°旋转:",b6="硬降:",		b7="软降:",			b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				norm="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
			},
			setting_trackSetting={
				VKDodge="自动避让",
			},
			customGame={
				title="自定义游戏",
				subTitle="基本",
				defSeq="默认序列",
				noMsn="无任务",

				drop="下落延迟",
				lock="锁定延迟",
				wait="出块等待",
				fall="消行延迟",

				bg="背景",
				bgm="音乐",

				copy="复制场地+序列+任务",
				paste="粘贴场地+序列+任务",
				clear="开始-消除",
				puzzle="开始-拼图",

				advance="更多设置(A)",
				field="场地编辑(F)",
				sequence="序列编辑(S)",
				mission="任务编辑(M)",
			},
			custom_advance={
				title="自定义游戏",
				subTitle="高级",

				next="预览",hold="暂存",oncehold="暂存一次",
				block="方块可见",
				ghost="阴影透明度",
				center="中心透明度",
				bagLine="包分界线",
				highCam="超屏视野",
				nextPos="生成预览",
				bone="骨块",

				mindas="最小DAS",
				minarr="最小ARR",
				minsdarr="最小软降ARR",
				noTele="禁止瞬移",
				ospin="O-spin",
				target="目标行数",
				visible="能见度",
				freshLimit="锁延刷新限制",
				easyFresh="普通刷新锁延",
				fineKill="强制极简",
				opponent="对手",
				life="命数",
				pushSpeed="上涨速度",
			},
			custom_field={
				title="自定义游戏",
				subTitle="场地",

				b12="[  ]",
				any="不定",
				space="×",
				copy="复制",
				paste="粘贴",
				clear="清除",
				pushLine="增加一行(K)",
				delLine="消除行(L)",
				demo="不显示×",
			},
			custom_sequence={
				title="自定义游戏",
				subTitle="序列",

				sequence="序列",

				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
			},
			custom_mission={
				title="自定义游戏",
				subTitle="任务",

				_1="1",_2="2",_3="3",_4="4",
				any1="any1",any2="any2",any3="any3",any4="any4",
				PC="PC",
				Z1="Z1",S1="S1",J1="J1",L1="L1",T1="T1",O1="O1",I1="I1",
				Z2="Z2",S2="S2",J2="J2",L2="L2",T2="T2",O2="O2",I2="I2",
				Z3="Z3",S3="S3",J3="J3",L3="L3",T3="T3",O3="O3",I3="I3",
				O4="O4",I4="I4",
				left="←",right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				mission="强制任务",
			},
			help={
				dict="小Z词典",
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
			},
			dict={
				title="小Z方块词典",
				keyboard="键盘",
				link="打开链接",
				up="↑",
				down="↓",
			},
			staff={
			},
			stat={
				path="打开存储目录",
			},
			music={
				title="音乐室",
				arrow="→",
				now="正在播放:",

				bgm="BGM",
				up="↑",
				play="播放",
				down="↓",
			},
			login={
				title="登录/注册",
				username="用户名",
				email="邮箱",
				code="邀请码",
				password="密码",
				password2="确认密码",
			},
			account={
				title="账户",
			},
			sound={
				title="音效室",
				move="移动",
				lock="锁定",
				drop="硬降",
				fall="行落下",
				rotate="旋转",
				rotatekick="旋转进洞",
				hold="暂存",
				prerotate="提前旋转",
				prehold="提前暂存",

				_1="消一",
				_2="消二",
				_3="消三",
				_4="消四",
				spin0="空旋转",
				spin1="旋转消一",
				spin2="旋转消二",
				spin3="旋转消三",

				z0="Z旋",
				z1="Z旋消一",
				z2="Z旋消二",
				z3="Z旋消三",
				s0="S旋",
				s1="S旋消一",
				s2="S旋消二",
				s3="S旋消三",

				j0="J旋",
				j1="J旋消一",
				j2="J旋消二",
				j3="J旋消三",
				l0="L旋",
				l1="L旋消一",
				l2="L旋消二",
				l3="L旋消三",

				t0="T旋",
				t1="T旋消一",
				t2="T旋消二",
				t3="T旋消三",
				o0="O旋",
				o1="O旋消一",
				o2="O旋消二",
				o3="O旋消三",

				i0="I旋",
				i1="I旋消一",
				i2="I旋消二",
				i3="I旋消三",

				mini="迷你",
				b2b="满贯",
				b3b="大满贯",
				pc="全清",
			},
			minigame={
				p15="15 Puzzle",
				schulte_G="舒尔特方格",
				pong="Pong",
			},
			p15={
				reset="打乱",
				color="颜色",
				blind="盲打",
				slide="滑动操作",
				pathVis="路径显示",
				revKB="键盘反向",
			},
			schulte_G={
				reset="重来",
				rank="尺寸",
				blind="盲打",
				disappear="消失",
				tapFX="点击动画",
			},
			pong={
				reset="重置",
			},
			debug={
				copyLog="复制日志",
				scrInfo="输出屏幕信息",
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10行",		"消除10行"},
			["sprint_20"]=			{"竞速",		"20行",		"消除20行"},
			["sprint_40"]=			{"竞速",		"40行",		"消除40行"},
			["dig_10"]=				{"挖掘",		"10L",		"挖掘10行"},
			["dig_40"]=				{"挖掘",		"40L",		"挖掘40行"},
			["dig_100"]=			{"挖掘",		"100L",		"挖掘100行"},
			["dig_400"]=			{"挖掘",		"400L",		"挖掘400行"},
			["dig_1000"]=			{"挖掘",		"1000L",	"挖掘1000行"},
			["sprint_100"]=			{"竞速",		"100行",	"消除100行"},
			["sprint_400"]=			{"竞速",		"400行",	"消除400行"},
			["sprint_1000"]=		{"竞速",		"1000行",	"消除1000行"},
			["drought_normal"]=		{"干旱",		"100行",	"你I没了"},
			["drought_lunatic"]=	{"干旱",		"100行",	"后 妈 发 牌"},
			["marathon_normal"]=	{"马拉松",		"普通",		"200行加速马拉松"},
			["marathon_hard"]=		{"马拉松",		"困难",		"200行高速马拉松"},
			["marathon_ultimate"]=	{"马拉松",		"极限",		"禁止0连击单消之外的任何操作"},
			["solo_1"]=				{"单挑",		"简单",		"打败机器人"},
			["solo_2"]=				{"单挑",		"普通",		"打败机器人"},
			["solo_3"]=				{"单挑",		"困难",		"打败机器人"},
			["solo_4"]=				{"单挑",		"疯狂",		"打败机器人"},
			["solo_5"]=				{"单挑",		"极限",		"打败机器人"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"49人混战,活到最后"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"49人混战,活到最后"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"49人混战,活到最后"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"99人混战,活到最后"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"99人混战,活到最后"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"99人混战,活到最后"},
			["round_1"]=			{"回合制",		"简单",		"下棋模式"},
			["round_2"]=			{"回合制",		"普通",		"下棋模式"},
			["round_3"]=			{"回合制",		"困难",		"下棋模式"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋模式"},
			["round_5"]=			{"回合制",		"极限",		"下棋模式"},
			["master_beginner"]=	{"大师",		"疯狂",		"20G初心者练习"},
			["master_advance"]=		{"大师",		"极限",		"上级者20G挑战"},
			["master_final"]=		{"大师",		"终点",		"究极20G:无法触及的终点"},
			["GM"]=					{"宗师",		"GM",		"成为方块大师"},
			["blind_easy"]=			{"隐形",		"半隐",		"不强大脑"},
			["blind_normal"]=		{"隐形",		"全隐",		"挺强大脑"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"很强大脑"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"超强大脑"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"高速经典"},
			["survivor_easy"]=		{"生存",		"简单",		"你能存活多久?"},
			["survivor_normal"]=	{"生存",		"普通",		"你能存活多久?"},
			["survivor_hard"]=		{"生存",		"困难",		"你能存活多久?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"你能存活多久?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"你能存活多久?"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"中四宽练习",	"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"中四宽练习",	"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"简易全清题库,熟悉全清定式的组合"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"简易全清题库,熟悉全清定式的组合"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷全清"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷全清"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷全清"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal2"]=		{"科研",		"普通+",	"仅允许回旋与全清"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard2"]=			{"科研",		"困难+",	"仅允许回旋与全清"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic2"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse2"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"T2挑战",		"简单",		"你能连续做几个T旋双清?"},
			["tsd_hard"]=			{"T2挑战",		"困难",		"你能连续做几个T旋双清?"},
			["tsd_ultimate"]=		{"T2挑战",		"极限",		"你能连续做几个T旋双清?"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"在两分钟内尽可能拿到最多的分数"},
			["infinite"]=			{"无尽",		"",			"沙盒"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"挖呀挖呀挖"},
			["custom_clear"]=		{"自定义",		"普通",		"画点什么然后把它消除!"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"画点什么然后把它拼出来吧!"},
			["sprintFix"]=			{"竞速",		"无移动",	"这是可能的。"},
			["sprintLock"]=			{"竞速",		"无旋转",	"这不可能。"},
			["sprintPenta"]=		{"竞速",		"五连块",	"伤脑筋十八块"},
			["sprintMPH"]=			{"竞速",		"纯净",		"纯随机\n无预览\n无暂存"},
		},
		getTip=nil,
	},
	{
		back="Back",
		anykey="Press any button",
		newVersion="Thanks for updating! Check out the updates below.",
		httpTimeout="Network connection timed out",
		marking="Game Author: MrZ_26\nIllegal recording if you can see this\nAny explanation is invalid",
		holdR="Keep holding to retry",

		atkModeName={"Random","Badges","K.O.s","Attackers"},
		royale_remain="$1 Players Remaining",
		cmb={nil,"1 Combo","2 Combo","3 Combo","4 Combo","5 Combo","6 Combo","7 Combo","8 Combo","9 Combo","10 Combo!","11 Combo!","12 Combo!","13 Combo!","14 Combo!!","15 Combo!!","16 Combo!!","17 Combo!!!","18 Combo!!!","19 Combo!!!","MEGACMB"},
		block=nil,spin="-Spin ",
		clear={"Single","Double","Triple","Techrash","Techrash+"},
		mini="Mini",b2b="B2B ",b3b="B2B2B ",
		PC="Perfect Clear",HPC="Clear",
		hold="HOLD",next="NEXT",
		replaying="[Replay]",

		stage="Stage $1",
		great="Great!",
		awesome="Awesome!",
		almost="Almost!",
		continue="Keep going!",
		maxspeed="Max speed!",
		speedup="Speed up!",
		missionFailed="Wrong Clear",

		win="You Win!",
		finish="Finish",
		gameover="Game Over",
		pause="Pause",
		pauseCount="Pauses",
		finesse_ap="All Perfect",
		finesse_fc="Full Combo",

		snapLevelName={"Free pos","Snap-10","Snap-20","Snap-40","Snap-60","Snap-80"},
		page="Page:",

		ai_fixed="The AI is incompatible with fixed sequences.",
		ai_prebag="The AI is incompatible with custom sequences.",
		ai_mission="The AI is incompatible with custom missions.",
		settingSaved="Settings Saved",
		settingSavingError="Failed to save settings:",
		keyMapSaved="Key settings saved",
		keyMapSavingError="Failed to save key settings:",
		VKSaved="Virtual keys saved",
		VKSavingError="Failed to save virtual key configuration:",
		statSavingError="Failed to save statistics:",
		unlockSavingError="Failed to save unlocked content:",
		recSavingError="Failed to save record:",
		switchSpawnSFX="Switch on spawn SFX to play",
		getRank="Rank: ",
		ranks={"D","C","B","A","S"},

		needRestart="Effective after restart",
		copySuccess="Copied successfully",
		pasteSuccess="Pasted successfully",
		dataCorrupted="Data corrupted",
		VKTchW="Touch Weight",
		VKOrgW="Origin Weight",
		VKCurW="Cur. Pos. Weight",
		noScore="No Scores Yet",
		highScore="Personal Bests",
		newRecord="New Record!",
		getNoticeFail="Couldn't get announcements",
		getVersionFail="Unable to detect a new version",
		versionIsNew="You are now on the latest version.",
		versionIsOld="Version $1 is available now!",
		registerSuccessed="Registered!",
		registerFailed="Registration failed",
		netErrorCode="Network error code",
		noUsername="Please enter your username",
		noPassword="Please enter your password",
		diffPassword="Passwords don't match",
		errorMsg="An error has occurred and Techmino needs to restart.\nError info has been created, and you can send it to the author.",

		acts={
			"Move Left:","Move Right:",
			"Rotate Right:","Rotate Left:","Rotate 180°:",
			"Hard Drop:","Soft Drop:","Hold:","Function:","Restart:",
			"Instant Left:","Instant Right:","Sonic Drop:","Down 1:","Down 4:","Down 10:",
			"Left Drop:","Right Drop:","Left Zangi:","Right Zangi:",
		},
		pauseStat={
			"Time:",
			"Key/Rot./Hold:",
			"Piece:",
			"Row/Dig:",
			"Attack/DigAtk:",
			"Received:",
			"Clears:",
			"Spins:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"ADPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spins 0-3",
			clear="clears 1-4",
			"Times Launched:",
			"Play Count:",
			"Play Time:",
			"Key/Rot./Hold:",
			"Block/Row/Atk.:",
			"Recv./Res./Asc.:",
			"Dig/Dig Atk.:",
			"Eff./Dig Eff.:",
			"B2B/B3B:",
			"PC/HPC:",
			"FnsErrs./FnsRate:",
		},
		help={
			"Now you can play this - you probably do not need \"help\"?",
			"This is just an ordinary block game, not a certain one.",
			"It plays like TO/C2/KOS/TGM3 and others.",
			"",
			"You can send bug reports or suggestions to the author's testing group or email ~",
			"This is a free download available only through discord.gg/f9pUvkh",
			"The game downloaded from other sources may contain viruses,",
			"and only vibration & networking permissions are needed for mobile versions!",
			"The author is not responsible for any loss of data from modifying the game.",
		},
		staff={
			"Author: MrZ  E-mail: 1046101471@qq.com",
			"Powered by LOVE2D",
			"",
			"Program: MrZ, FinnTenzor",
			"Art: MrZ, (T0722, Gnyar)",
			"Music: MrZ, (T0722)",
			"Voice & Sound: MrZ, Miya",
			"Performance: 模电, HBM  Test: 思竣",
			"Eng Doc: User670  Web: 渣渣120",
			"",
			"Special Thanks:",
			"Flyz, Farter, 蕴空之灵,",
			"Teatube, [All test staff]",
		},
		used=[[
		Tools used:
			Beepbox
			GFIE
			Goldwave
		Libs used:
			Cold_Clear [MinusKelvin]
			json.lua [rxi]
			profile.lua [itraykov]
			simple-love-lights [dylhunn]
		]],
		support="Support author",
		group="Official QQ Group (if not hacked): 1127702001",
		WidgetText={
			main={
				play="Play",
				custom="Custom",
				qplay="Q. Play",
				stat="Statistics",
				help="Help",
				setting="Settings",
				lang="言/A",
				music="Music Room",
				account="Account",
				sound="SE Room",
				minigame="Mini Games",
				quit="Exit",
			},
			mode={
				start="Start",
			},
			play={
				pause="Pause",
			},
			pause={
				setting="Settings (S)",
				replay="Replay (P)",
				resume="Resume (esc)",
				restart="Retry (R)",
				quit="Quit (Q)",
			},
			setting_game={
				title="Game Settings",

				graphic="←Video",
				sound="Sound→",

				ctrl="Control Settings",
				key="Key Mappings",
				touch="Touch Settings",
				reTime="Start Delay",
				maxNext="Next Queue Length",
				layout="Layout",
				autoPause="Pause when focus is lost",
				swap="Key Combination (Change Atk. Mode)",
				fine="Finesse Error Sound",
				appLock="App Lock (Password: 626)",
				calc="App Lock",
			},
			setting_video={
				title="Video Settings",

				sound="←Sound",
				game="Game→",

				block="Draw Block",
				ghost="Ghost",
				center="Center",

				smooth="Smooth Drop",
				grid="Grid",
				bagLine="Bag Line",

				lockFX="Lock FX Level",
				dropFX="Drop FX Level",
				moveFX="Move FX Level",
				clearFX="Clear FX Level",
				shakeFX="Field Sway Level",
				atkFX="Atk. FX Level",
				frame="Render Frame Rate",

				text="Action Text",
				score="Score Pop-up",
				warn="Danger Alert",
				highCam="Birds-eye View",
				nextPos="Next Preview",
				fullscreen="Full Screen",
				bg="Background",
				power="Power Info",
			},
			setting_sound={
				title="Sound Settings",

				game="←Game",
				graphic="Video→",

				sfx="SFX",
				stereo="Stereo",
				spawn="Spawning",
				bgm="BGM",
				vib="Vibration",
				voc="Voice",
			},
			setting_control={
				title="Control Settings",
				preview="Preview",

				das="DAS",arr="ARR",
				sddas="Soft Drop DAS",sdarr="Soft Drop ARR",
				ihs="Initial Hold",
				irs="Initial Rotation",
				ims="Initial Movement",
				reset="Reset",
			},
			setting_key={
				keyboard="Keyboard",
				joystick="Controller",
				help="Arrow keys: select/change slot, Enter/Space: Change, Esc: Go back",
			},
			setting_skin={
				title="Layout Settings",

				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="Reset Color",
				faceR="Reset Dir.",
			},
			setting_touch={
				default="Default",
				snap="Snap",
				option="Options",
				size="Size",
			},
			setting_touchSwitch={
				b1=	"Move Left:",	b2="Move Right:",	b3="Rotate Right:",	b4="Rotate Left:",
				b5=	"Rotate 180°:",	b6="Hard Drop:",	b7="Soft Drop:",	b8="Hold:",
				b9=	"Function:",	b10="Restart Game:",		b11="Instant Left:",b12="Instant Right:",
				b13="Sonic Drop:",	b14="Down 1:",		b15="Down 4:",		b16="Down 10:",
				b17="Left Drop:",	b18="Right Drop:",	b19="Left Zangi:",	b20="Right Zangi:",
				norm="Normal",
				pro="Professional",
				hide="Show Virtual Keys",
				track="Auto Track",
				sfx="SFX",
				vib="VIB",
				icon="Icon",
				tkset="Track Settings",
				alpha="Alpha",
			},
			setting_trackSetting={
				VKDodge="Auto Dodge",
			},
			customGame={
				title="Custom Game",
				subTitle="Basic",
				defSeq="Default Seq.",
				noMsn="No missions",

				drop="Drop Delay",
				lock="Lock Delay",
				wait="Entry Delay",
				fall="Line Delay",

				bg="Background",
				bgm="Music",

				copy="Copy Field+Seq+Misn",
				paste="Paste Field+Seq+Misn",
				clear="Start-Clear",
				puzzle="Start-Puzzle",

				advance="More (A)",
				field="Edit Field (F)",
				sequence="Edit Sequence (S)",
				mission="Edit Mission (M)",
			},
			custom_advance={
				title="Custom Game",
				subTitle="Advance",

				next="Next",hold="Hold",oncehold="Hold Once",
				block="Draw Block",
				ghost="Ghost",
				center="Center",
				bagLine="Bag Line",
				highCam="Birds-eye View",
				nextPos="Next Preview",
				bone="Bone Block",

				mindas="Min. DAS",
				minarr="Min. ARR",
				minsdarr="Min. SDARR",
				noTele="No Teleportation",
				ospin="O-Spin",
				target="Target",
				visible="Visibility",
				freshLimit="Lock Reset Limit",
				easyFresh="Normal Lock Reset",
				fineKill="100% Finesse",
				opponent="Opponent",
				life="Lives",
				pushSpeed="Garbage Speed",
			},
			custom_field={
				title="Custom Game",
				subTitle="Field",

				b12="[  ]",
				any="Erase",
				space="×",
				copy="Copy",
				paste="Paste",
				clear="Clear",
				pushLine="Add Line(K)",
				delLine="Del Line(L)",
				demo="Don't Show ×",
			},
			custom_sequence={
				title="Custom Game",
				subTitle="Sequence",

				sequence="Sequence",

				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="Copy",
				paste="Paste",
			},
			custom_mission={
				title="Custom Game",
				subTitle="Mission",

				_1="1",_2="2",_3="3",_4="4",
				any1="any1",any2="any2",any3="any3",any4="any4",
				PC="PC",
				Z1="Z1",S1="S1",J1="J1",L1="L1",T1="T1",O1="O1",I1="I1",
				Z2="Z2",S2="S2",J2="J2",L2="L2",T2="T2",O2="O2",I2="I2",
				Z3="Z3",S3="S3",J3="J3",L3="L3",T3="T3",O3="O3",I3="I3",
				O4="O4",I4="I4",
				left="←",right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="Copy",
				paste="Paste",
				mission="Force mission",
			},
			help={
				dict="little Z",
				staff="Staff",
				his="History",
				qq="Author's qq",
			},
			dict={
				title="TetroDictionary",
				keyboard="Keyboard",
				link="Open URL",
				up="↑",
				down="↓",
			},
			staff={
			},
			stat={
				path="Open Data Folder",
			},
			music={
				title="Music Room",
				arrow="→",
				now="Now Playing:",

				bgm="BGM",
				up="↑",
				play="Play",
				down="↓",
			},
			login={
				title="Log in / Sign up",
				username="Username",
				email="Email address",
				code="Invitation Code",
				password="Password",
				password2="Reenter password",
			},
			account={
				title="Account",
			},
			sound={
				title="SE Room",
				move="Move",
				lock="Lock",
				drop="Drop",
				fall="Fall",
				rotate="Rotate",
				rotatekick="Rotatekick",
				hold="Hold",
				prerotate="Prerotate",
				prehold="Prehold",

				_1="Clear 1",
				_2="Clear 2",
				_3="Clear 3",
				_4="Clear 4",
				spin0="spin 0",
				spin1="spin 1",
				spin2="spin 2",
				spin3="spin 3",

				z0="Z-spin",
				z1="Z-spin 1",
				z2="Z-spin 2",
				z3="Z-spin 3",
				s0="S-spin",
				s1="S-spin 1",
				s2="S-spin 2",
				s3="S-spin 3",

				j0="J-spin",
				j1="J-spin 1",
				j2="J-spin 2",
				j3="J-spin 3",
				l0="L-spin",
				l1="L-spin 1",
				l2="L-spin 2",
				l3="L-spin 3",

				t0="T-spin",
				t1="T-spin 1",
				t2="T-spin 2",
				t3="T-spin 3",
				o0="O-spin",
				o1="O-spin 1",
				o2="O-spin 2",
				o3="O-spin 3",

				i0="I-spin",
				i1="I-spin 1",
				i2="I-spin 2",
				i3="I-spin 3",

				mini="Mini",
				b2b="B2B",
				b3b="B3B",
				pc="PC",
			},
			minigame={
				p15="15 Puzzle",
				schulte_G="Schulte Grid",
				pong="Pong",
			},
			p15={
				reset="Shuffle",
				color="Color",
				blind="Blind",
				slide="Slide",
				pathVis="Show Path",
				revKB="Reverse",
			},
			schulte_G={
				reset="Reset",
				rank="Size",
				blind="Blind",
				disappear="Hide",
				tapFX="tap FX",
			},
			pong={
				reset="Restart",
			},
			debug={
				copyLog="Copy Log",
				scrInfo="Show Screen Info",
				reset="Are you sure you want to reset?",
				reset1="Reset ranks",
				reset2="Reset data",
				reset3="Reset all",
			},
		},
		modes={
			["sprint_10"]=			{"Sprint",			"10L",			"Clear 10 lines!"},
			["sprint_20"]=			{"Sprint",			"20L",			"Clear 20 lines!"},
			["sprint_40"]=			{"Sprint",			"40L",			"Clear 40 lines!"},
			["dig_10"]=				{"Dig",				"10L",			"Dig 10 lines"},
			["dig_40"]=				{"Dig",				"40L",			"Dig 40 lines"},
			["dig_100"]=			{"Dig",				"100L",			"Dig 100 lines"},
			["dig_400"]=			{"Dig",				"400L",			"Dig 400 lines"},
			["dig_1000"]=			{"Dig",				"1000L",		"Dig 1000 lines"},
			["sprint_100"]=			{"Sprint",			"100L",			"Clear 100 lines!"},
			["sprint_400"]=			{"Sprint",			"400L",			"Clear 400 lines!"},
			["sprint_1000"]=		{"Sprint",			"1000L",		"Clear 1000 lines!"},
			["drought_normal"]=		{"Drought",			"100L",			"No I piece!"},
			["drought_lunatic"]=	{"Drought",			"100L",			"WTF"},
			["marathon_normal"]=	{"Marathon",		"NORMAL",		"200-line marathon with accelerating speed."},
			["marathon_hard"]=		{"Marathon",		"HARD",			"200-line high-speed marathon."},
			["marathon_ultimate"]=	{"Marathon",		"Ultimate",		"Regular singles without combo only"},
			["solo_1"]=				{"Battle",			"EASY",			"Defeat the AI!"},
			["solo_2"]=				{"Battle",			"NORMAL",		"Defeat the AI!"},
			["solo_3"]=				{"Battle",			"HARD",			"Defeat the AI!"},
			["solo_4"]=				{"Battle",			"LUNATIC",		"Defeat the AI!"},
			["solo_5"]=				{"Battle",			"ULTIMATE",		"Defeat the AI!"},
			["techmino49_easy"]=	{"Tech 49",			"EASY",			"49-player battle.\nThe last one standing wins."},
			["techmino49_hard"]=	{"Tech 49",			"HARD",			"49-player battle.\nThe last one standing wins."},
			["techmino49_ultimate"]={"Tech 49",			"ULTIMATE",		"49-player battle.\nThe last one standing wins."},
			["techmino99_easy"]=	{"Tech 99",			"EASY",			"99-player battle.\nThe last one standing wins."},
			["techmino99_hard"]=	{"Tech 99",			"HARD",			"99-player battle.\nThe last one standing wins."},
			["techmino99_ultimate"]={"Tech 99",			"ULTIMATE",		"99-player battle.\nThe last one standing wins."},
			["round_1"]=			{"Turn-Based",		"EASY",			"Chess mode"},
			["round_2"]=			{"Turn-Based",		"NORMAL",		"Chess mode"},
			["round_3"]=			{"Turn-Based",		"HARD",			"Chess mode"},
			["round_4"]=			{"Turn-Based",		"LUNATIC",		"Chess mode"},
			["round_5"]=			{"Turn-Based",		"ULTIMATE",		"Chess mode"},
			["master_beginner"]=	{"Master",			"LUNATIC",		"For 20G beginners."},
			["master_advance"]=		{"Master",			"ULTIMATE",		"Professional 20G challenge!"},
			["master_final"]=		{"Master",			"FINAL",		"20G: Unreachable end point!"},
			["GM"]=					{"GrandMaster",		"GM",			"To be a Grand Master, take \nthis challenge."},
			["blind_easy"]=			{"Blind",			"HALF",			"For novice players."},
			["blind_normal"]=		{"Blind",			"ALL",			"For intermediate players."},
			["blind_hard"]=			{"Blind",			"SUDDEN",		"For experienced players."},
			["blind_lunatic"]=		{"Blind",			"SUDDEN+",		"For professionals."},
			["blind_ultimate"]=		{"Blind",			"?",			"Are you ready?"},
			["blind_wtf"]=			{"Blind",			"WTF",			"You're not ready."},
			["classic_fast"]=		{"Classic",			"CTWC",			"High-speed classic mode."},
			["survivor_easy"]=		{"Survivor",		"EASY",			"How long can you survive?"},
			["survivor_normal"]=	{"Survivor",		"NORMAL",		"How long can you survive?"},
			["survivor_hard"]=		{"Survivor",		"HARD",			"How long can you survive?"},
			["survivor_lunatic"]=	{"Survivor",		"LUNATIC",		"How long can you survive?"},
			["survivor_ultimate"]=	{"Survivor",		"ULTIMATE",		"How long can you survive?"},
			["attacker_hard"]=		{"Attacker",		"HARD",			"Offensive practice!"},
			["attacker_ultimate"]=	{"Attacker",		"ULTIMATE",		"Offensive practice!"},
			["defender_normal"]=	{"Defender",		"NORMAL",		"Defensive practice!"},
			["defender_lunatic"]=	{"Defender",		"LUNATIC",		"Defensive practice!"},
			["dig_hard"]=			{"Driller",			"HARD",			"Digging practice!"},
			["dig_ultimate"]=		{"Driller",			"ULTIMATE",		"Digging practice!"},
			["bigbang"]=			{"Big Bang",		"EASY",			"All-spin tutorial!\n[Under construction]"},
			["c4wtrain_normal"]=	{"C4W Training",	"NORMAL",		"Infinite combos."},
			["c4wtrain_lunatic"]=	{"C4W Training",	"LUNATIC",		"Infinite combos."},
			["pctrain_normal"]=		{"PC Training",		"NORMAL",		"Simple Perfect Clear mode."},
			["pctrain_lunatic"]=	{"PC Training",		"LUNATIC",		"Simple Perfect Clear mode."},
			["pcchallenge_normal"]=	{"PC Challenge",	"NORMAL",		"Get PCs within 100 lines!"},
			["pcchallenge_hard"]=	{"PC Challenge",	"HARD",			"Get PCs within 100 lines!"},
			["pcchallenge_lunatic"]={"PC Challenge",	"LUNATIC",		"Get PCs within 100 lines!"},
			["tech_normal"]=		{"Tech",			"NORMAL",		"Keep the B2B chain!"},
			["tech_normal2"]=		{"Tech",			"NORMAL+",		"Spin & PC only"},
			["tech_hard"]=			{"Tech",			"HARD",			"Keep the B2B chain!"},
			["tech_hard2"]=			{"Tech",			"HARD+",		"Spin & PC only"},
			["tech_lunatic"]=		{"Tech",			"LUNATIC",		"Keep the B2B chain!"},
			["tech_lunatic2"]=		{"Tech",			"LUNATIC+",		"Spin & PC only"},
			["tech_finesse"]=		{"Tech",			"FINESSE",		"No finesse faults!"},
			["tech_finesse2"]=		{"Tech",			"FINESSE+",		"No normal clears, no finesse faults!"},
			["tsd_easy"]=			{"TSD Challenge",	"EASY",			"T-spin-doubles only!"},
			["tsd_hard"]=			{"TSD Challenge",	"HARD",			"T-spin-doubles only!"},
			["tsd_ultimate"]=		{"TSD Challenge",	"ULTIMATE",		"T-spin-doubles only!"},
			["zen"]=				{"Zen",				"200",			"200 lines without a time limit."},
			["ultra"]=				{"Ultra",			"EXTRA",		"Get the highest score within 2 min."},
			["infinite"]=			{"Infinite",		"",				"Sandbox mode."},
			["infinite_dig"]=		{"Infinite: Dig",	"",				"Dig, dig, dig."},
			["custom_clear"]=		{"Custom",			"NORMAL",		"Draw something then clear it!!"},
			["custom_puzzle"]=		{"Custom",			"PUZZLE",		"Draw something then stack it!!"},
			["sprintFix"]=			{"Sprint",			"NO LEFT/RIGHT","It's possible."},
			["sprintLock"]=			{"Sprint",			"NO ROTATIONS",	"It's impossible."},
			["sprintPenta"]=		{"Sprint",			"PENTOMINO",	"Clear 40 lines with 18 pentominoes."},
			["sprintMPH"]=			{"Sprint",			"MPH",			"Memoriyless\nPreviewless\nHoldless"},
		},
		getTip={
			'Free block game with Battle Royale mode!',
			'Have you noticed what "rotating" does do to the block?',
			":pog:",
			"(RUR'U')R'FR2U'R'U'(RUR'F')",
			"\\jezevec/\\jezevec/\\jezevec/",
			"\\osk/\\osk/\\osk/",
			"↑↑↓↓←→←→BA",
			"1, 2, ⑨!!!!!",
			"20G actually is a brand new game rule",
			"少女祈禱中",
			"ALLSPIN!",
			"Also try Cultris II!",
			"Also try Jstris!",
			"Also try Minecraft",
			"Also try Osu!",
			"Also try Phigros!",
			"Also try Terraria!",
			"Also try Tetr.io!",
			"Also try Tetr.js!",
			"Also try Tetra Legends!",
			"Also try VVVVVV!",
			"Am G F G",
			"Any suggestions? Post them in our Discord!",
			"B2B2B???",
			"Back to Back 10 combo Techrash PC!",
			"Change log in English can be found on Discord.",
			"COOL!!",
			"Decreasing DAS and ARR: faster, but harder to control.",
			"Diao so bully",
			"Don't let a small glitch ruin your entire day!",
			"Don't look directly at the bugs!",
			"Enjoy Techmino rotation system!",
			"Find out what's in the settings!",
			"Headphones recommended for better experience",
			"Hello world!",
			"Increase frame rate for better experience.",
			"Initial [insert action] system can save your life",
			"Is B2B2B2B possible?",
			"It's really loading! Not just a cutscene!",
			"Join our discord!",
			"l-=-1",
			"Let-The-Bass-Kick!",
			"LrL RlR LLr RRl RRR LLL FFF RfR RRf rFF",
			"Lua No.1",
			"Music distracting? Feel free to turn it off.",
			"No, there are no easter eggs based on your device time.",
			"O-Spin Triple!",
			"OHHHHHHHHHHHHHH",
			"Online mode planned, be patient",
			"Powered by Love2D",
			"REGRET!!",
			"Secret number: 626",
			"Sprint WR: 15.654s by VinceHD",
			"Techmino = Technique + Tetromino",
			"Techmino has a Nspire-CX edition!",
			"Techmino is so fun!",
			"TetroDictionary (Little Z) in English can be found on Discord.",
			"Try to use two rotate buttons. Even better, all three.",
			"Warning: Programmer Art",
			"What about 20 PCs?",
			"What about 23 PCs in 100 lines?",
			"What about 26 TSDs?",
			"You are Grand Master.",
			"You can open saving directory from Stats page",
			"You can set orientation for each block",
			"ZS JL T O I",
		}
	},
	{
		back="X",
		anykey="↓□↓",
		newVersion="&!!!???↓↓",
		httpTimeout="e??????x",
		marking="Game Author:MrZ_26\nIllegal recording if see this\nAny explanation invalid",
		holdR="→→→→R",

		atkModeName={"?","(  )","!","←→"},
		royale_remain="$1 ~",
		cmb={nil,"!","!!","!!!","!!!!","!!!!!","!!!!!!","!!!!!!!","!!!!!!!!","!!!!!!!!!","!!!!!!!!!!","!!!!!!!!!!!","!!!!!!!!!!!!","!!!!!!!!!!!!!","!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!!!",},
		block=nil,spin=" ~",
		clear={"1","2","3","4","5"},
		mini="v",b2b="^ ",b3b="^^ ",
		PC="#<>#",HPC="<>",
		hold="[ ]",next="→",
		replaying="[Replaying]",

		stage="::$1::",
		great="!~",
		awesome="!!~",
		almost="...!",
		continue="~~",
		maxspeed="!!!",
		speedup="~!~",
		missionFailed="-X_X-",

		win=": )",
		finish="&",
		gameover="x",
		pause="=",
		pauseCount="==",
		finesse_ap="AP",
		finesse_fc="FC",

		snapLevelName={"~","10","20","40","60","80"},
		page=":",

		ai_fixed="X!!!",
		ai_prebag="X!!!",
		ai_mission="X!!!",
		settingSaved="~~~",
		settingSavingError="x!:",
		keyMapSaved="~~~",
		keyMapSavingError="x!:",
		VKSaved="~~~",
		VKSavingError="x!:",
		statSavingError="x!:",
		unlockSavingError="x!:",
		recSavingError="x!:",
		switchSpawnSFX="Switch on spawn SFX to play",
		getRank="#:",
		ranks={"D","C","B","A","S"},

		needRestart="!!*#R#*!!",
		copySuccess="~$~",
		pasteSuccess="~v~",
		dataCorrupted="XXXXX",
		VKTchW="Tch↓",
		VKOrgW="Org↓",
		VKCurW="Cur↓",
		noScore="?_____?",
		highScore="__&:",
		newRecord="^!!!^",
		getNoticeFail="get notice failed",
		getVersionFail="get newest version failed",
		versionIsNew="You are now on the latest version.",
		versionIsOld="Version $1 is available now!",
		registerSuccessed="Register successed!",
		registerFailed="Register failed",
		netErrorCode="Network error code",
		noUsername="Input username",
		noPassword="Input password",
		diffPassword="Password don't match",
		errorMsg="An e??o? h@s occ^__ed @nd Techmino n__ds to r_st@rt.\n&**o* in#o h@$ b==n cre@ted, @nd y0u c@n $&nd it to the @uth0r.",
		acts={
			"←:","→:",
			"R→:","←R:","R↑↓:",
			"↓↓:","↓:","□←:","F:","R:",
			"|←:","→|:","↓_:","↓1:","↓4:","↓10:",
			"←↓→↓:","→↓↓:","←↓→↓:","→↓←↓:",
		},
		pauseStat={
			"~:",
			"=/''/[ ]:",
			"□:",
			"-/↓:",
			"→/↓→:",
			"←:",
			"□↓:",
			"~↓:",
			"^^/^^^/#<>#/<>:",
			"!#!X:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"ADPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="~0-3",
			clear="□1-4",
			"@:",
			"##:",
			"~:",
			"=/''/[ ]:",
			"□/-/→.:",
			"←/-↓/↑:",
			"↓/↓→.:",
			"^%/↓^%:",
			"^/^^:",
			"#<>#/<>:",
			"!#!X/%:",
		},
		help={
			"□□□□~~~, ?_?x ?",
			"□!!~~~,□□□□X",
			"□!!==*/*/*/*~",
			"",
			"bug reports/suggestions, sent to the author's testing group or email ~",
			"This is a free download available only through discord.gg/f9pUvkh",
			"The game downloaded from other sources may contain viruses,",
			"and only vibration & networking permissions are needed for mobile versions!",
			"The author is not responsible for any losses from modifying the game.",
		},
		staff={
			"Author: MrZ  E-mail: 1046101471@qq.com",
			"Powered by LOVE2D",
			"",
			"Program: MrZ, FinnTenzor",
			"Art: MrZ, (T0722, Gnyar)",
			"Music: MrZ, (T0722)",
			"Voice & Sound: MrZ, Miya",
			"Performance: 模电, HBM  Test: 思竣",
			"Eng Doc: User670  Web: 渣渣120",
			"",
			"Special Thanks:",
			"Flyz, Farter, 蕴空之灵,",
			"Teatube, [All test staff]",
		},
		used=[[
		Tools used:
			Beepbox
			GFIE
			Goldwave
		Lib used:
			Cold_Clear [MinusKelvin]
			json.lua [rxi]
			profile.lua [itraykov]
			simple-love-lights [dylhunn]
		]],
		support="Support author",
		group="Official QQ Group(if not hacked):1127702001",
		WidgetText={
			main={
				play="!!!",
				custom="_?!",
				qplay="!",
				stat="=___",
				help="???",
				setting="_?_",
				lang="言/A",
				music="~~~",
				account="Account",
				sound="=><=",
				minigame="^_^",
				quit="X",
			},
			mode={
				start="!!!",
			},
			play={
				pause="||",
			},
			pause={
				setting="_?_ (S)",
				replay="## (P)",
				resume="!! (esc)",
				restart="_→_ (R)",
				quit="X (Q)",
			},
			setting_game={
				title="%~~%",

				graphic="←Video",
				sound="Sound→",

				ctrl="=?=",
				key="=?",
				touch="_?",
				reTime="3-2-1",
				maxNext="=123",
				layout="=-=-=",
				autoPause="A||",
				swap="=+=+=",
				fine="12 X 21",
				appLock="?XX(=626)",
				calc="?XX",
			},
			setting_video={
				title="{~~}",

				sound="←Sound",
				game="Game→",

				block="==↓==",
				ghost="__↓__",
				center="+",

				smooth="~~↓~~",
				grid="#",
				bagLine="123|123",

				lockFX="↓_~",
				dropFX="↓~",
				moveFX="←→~",
				clearFX="↓↓↓~",
				shakeFX="~|~|~",
				atkFX="→→~",
				frame="|=|",

				text="ABC",
				score="+123",
				warn="!↑↑↑!",
				highCam="↑__↑",
				nextPos="???←",
				fullscreen="|←→|",
				bg="__?__",
				power="+.",
			},
			setting_sound={
				title="(~~)",

				game="←Game",
				graphic="Video→",

				sfx="#!#",
				stereo="←~→",
				spawn="#[]#",
				bgm="#~#",
				vib="=~=",
				voc="~~~",
			},
			setting_control={
				title="[~~]",
				preview="?:",

				das="x---x x x",arr="x   x-x-x",
				sddas="↓---↓ ↓ ↓",sdarr="↓   ↓-↓-↓",
				ihs="![ ]",
				irs="!''",
				ims="!←→",
				reset="R",
			},
			setting_key={
				keyboard="[##]",
				joystick="^-^",
				help="..........................",
			},
			setting_skin={
				title="%{~~}",

				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="R @%&",
				faceR="R ↑↓←→.",
			},
			setting_touch={
				default="$0",
				snap="_ _",
				option="_?",
				size="←→",
			},
			setting_touchSwitch={
				b1=	"←:",    b2="→:",   b3="R→:",   b4="←R:",
				b5=	"R↑↓:",   b6="↓↓:",   b7="↓:",     b8="□←:",
				b9=	"F:",    b10="R:",  b11="←←:",  b12="→→:",
				b13="↓_:",   b14="↓1:",  b15="↓4:",   b16="↓10:",
				b17="←↓→↓:", b18="→↓↓:", b19="←↓→↓:",b20="→↓←↓:",
				norm="-",
				pro="+",
				hide="--?",
				track="~=?",
				sfx="#!#",
				vib="=~=",
				icon="@?",
				tkset="_~=_",
				alpha="+?",
			},
			setting_trackSetting={
				VKDodge="←_→",
			},
			customGame={
				title="!@#$%^&*",
				subTitle="!!",
				defSeq="0-[123]",
				noMsn="-x-",

				drop="↓",
				lock="↓_",
				wait="→=",
				fall="↓=",

				bg="{~}",
				bgm="(~)",

				copy="Copy Field+Seq+Misn",
				paste="Paste Field+Seq+Misn",
				clear="Start-Clear",
				puzzle="Start-Puzzle",

				advance="More (A)",
				field="Edit Field (F)",
				sequence="Edit Sequence (S)",
				mission="Edit Mission (M)",
			},
			custom_advance={
				title="!@#$%^&*",
				subTitle="##",

				next="→",hold="[ ]",oncehold="[ ]*1",
				block="==↓==",
				ghost="__↓__",
				center="+",
				bagLine="123|123",
				highCam="↑__↑",
				nextPos="???←",
				bone="[]",

				mindas="mDAS",
				minarr="mARR",
				minsdarr="msdARR",
				noTele="X→→X",
				ospin="O→Any",
				target="&=",
				visible="?=",
				freshLimit="@",
				easyFresh="↓_↓_↓_",
				fineKill="12 XX 21",
				opponent="^_^",
				life="<R>",
				pushSpeed="_↑_↑_",
			},
			custom_field={
				title="!@#$%^&*",
				subTitle="!@#$%^&* [##]",

				b12="[  ]",
				any="_",
				space="×",
				copy="→__",
				paste="__→",
				clear="XXX",
				pushLine="↑↑↑↑↑(K)",
				delLine="==X==(L)",
				demo="X ×",
			},
			custom_sequence={
				title="!@#$%^&*",
				subTitle="Sequence",

				sequence="$=",

				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="→__",
				paste="__→",
			},
			custom_mission={
				title="!@#$%^&*",
				subTitle="(!)",

				_1="1",_2="2",_3="3",_4="4",
				any1="any1",any2="any2",any3="any3",any4="any4",
				PC="PC",
				Z1="Z1",S1="S1",J1="J1",L1="L1",T1="T1",O1="O1",I1="I1",
				Z2="Z2",S2="S2",J2="J2",L2="L2",T2="T2",O2="O2",I2="I2",
				Z3="Z3",S3="S3",J3="J3",L3="L3",T3="T3",O3="O3",I3="I3",
				O4="O4",I4="I4",
				left="←",right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="Copy",
				paste="Paste",
				mission="Force mission",
			},
			help={
				dict="z",
				staff="Orz",
				his="_&_",
				qq="_@_",
			},
			dict={
				title="TetroDictionary",
				keyboard="□□□",
				link="~~e>>",
				up="↑",
				down="↓",
			},
			staff={
			},
			stat={
				path="_$_",
			},
			music={
				title="(~~~~)",
				arrow="→",
				now="~:",

				bgm="#~#",
				up="↑",
				play="!!!",
				down="↓",
			},
			login={
				title="Log in / Sign up",
				username="#",
				email="@",
				code="%",
				password="*",
				password2="*",
			},
			account={
				title="@_@",
			},
			sound={
				title="SE Room",
				move="←→",
				lock="Lock",
				drop="Drop",
				fall="Fall",
				rotate="''",
				rotatekick="''_",
				hold="[ ]",
				prerotate="!''",
				prehold="![ ]",

				_1="1",
				_2="2",
				_3="3",
				_4="4",
				spin0="~0",
				spin1="~1",
				spin2="~2",
				spin3="~3",

				z0="Z ~",
				z1="Z ~ 1",
				z2="Z ~ 2",
				z3="Z ~ 3",
				s0="S ~",
				s1="S ~ 1",
				s2="S ~ 2",
				s3="S ~ 3",

				j0="J ~",
				j1="J ~ 1",
				j2="J ~ 2",
				j3="J ~ 3",
				l0="L ~",
				l1="L ~ 1",
				l2="L ~ 2",
				l3="L ~ 3",

				t0="T ~",
				t1="T ~ 1",
				t2="T ~ 2",
				t3="T ~ 3",
				o0="O ~",
				o1="O ~ 1",
				o2="O ~ 2",
				o3="O ~ 3",

				i0="I ~",
				i1="I ~ 1",
				i2="I ~ 2",
				i3="I ~ 3",

				mini="v",
				b2b="^",
				b3b="^^",
				pc="#<>#",
			},
			minigame={
				p15="15 Puzzle",
				schulte_G="Schulte Grid",
				pong="Pong",
			},
			p15={
				reset="!@#$%",
				color="~~~",
				blind="???",
				slide="~_~",
				pathVis="--==>",
				revKB="Reverse",
			},
			schulte_G={
				reset="!@#$%",
				rank="←?→",
				blind="???",
				disappear="=X=",
				tapFX="↓ !",
			},
			pong={
				reset="R",
			},
			debug={
				reset="Reset?",
				reset1="Reset rank",
				reset2="Reset data",
				reset3="Reset ALL",
			},
		},
		modes={
			["sprint_10"]=			{"Sprint",			"10L",			"Clear 10 lines!"},
			["sprint_20"]=			{"Sprint",			"20L",			"Clear 20 lines!"},
			["sprint_40"]=			{"Sprint",			"40L",			"Clear 40 lines!"},
			["dig_10"]=				{"Dig",				"10L",			"Dig 10 lines"},
			["dig_40"]=				{"Dig",				"40L",			"Dig 40 lines"},
			["dig_100"]=			{"Dig",				"100L",			"Dig 100 lines"},
			["dig_400"]=			{"Dig",				"400L",			"Dig 400 lines"},
			["dig_1000"]=			{"Dig",				"1000L",		"Dig 1000 lines"},
			["sprint_100"]=			{"Sprint",			"100L",			"Clear 100 lines!"},
			["sprint_400"]=			{"Sprint",			"400L",			"Clear 400 lines!"},
			["sprint_1000"]=		{"Sprint",			"1000L",		"Clear 1000 lines!"},
			["drought_normal"]=		{"Drought",			"100L",			"No I piece!"},
			["drought_lunatic"]=	{"Drought",			"100L",			"WTF"},
			["marathon_normal"]=	{"Marathon",		"NORMAL",		"200-line marathon with accelerating speed."},
			["marathon_hard"]=		{"Marathon",		"HARD",			"200-line high-speed marathon."},
			["marathon_ultimate"]=	{"Marathon",		"Ultimate",		"Regular singles without combo only"},
			["solo_1"]=				{"Battle",			"EASY",			"Defeat the AI!"},
			["solo_2"]=				{"Battle",			"NORMAL",		"Defeat the AI!"},
			["solo_3"]=				{"Battle",			"HARD",			"Defeat the AI!"},
			["solo_4"]=				{"Battle",			"LUNATIC",		"Defeat the AI!"},
			["solo_5"]=				{"Battle",			"ULTIMATE",		"Defeat the AI!"},
			["techmino49_easy"]=	{"Tech 49",			"EASY",			"49-player battle.\nThe last one standing wins."},
			["techmino49_hard"]=	{"Tech 49",			"HARD",			"49-player battle.\nThe last one standing wins."},
			["techmino49_ultimate"]={"Tech 49",			"ULTIMATE",		"49-player battle.\nThe last one standing wins."},
			["techmino99_easy"]=	{"Tech 99",			"EASY",			"99-player battle.\nThe last one standing wins."},
			["techmino99_hard"]=	{"Tech 99",			"HARD",			"99-player battle.\nThe last one standing wins."},
			["techmino99_ultimate"]={"Tech 99",			"ULTIMATE",		"99-player battle.\nThe last one standing wins."},
			["round_1"]=			{"Turn-Based",		"EASY",			"Chess mode"},
			["round_2"]=			{"Turn-Based",		"NORMAL",		"Chess mode"},
			["round_3"]=			{"Turn-Based",		"HARD",			"Chess mode"},
			["round_4"]=			{"Turn-Based",		"LUNATIC",		"Chess mode"},
			["round_5"]=			{"Turn-Based",		"ULTIMATE",		"Chess mode"},
			["master_beginner"]=	{"Master",			"LUNATIC",		"For 20G beginners."},
			["master_advance"]=		{"Master",			"ULTIMATE",		"Professional 20G challenge!"},
			["master_final"]=		{"Master",			"FINAL",		"20G: Unreachable end point!"},
			["GM"]=					{"GrandMaster",		"GM",			"To be Grand Master"},
			["blind_easy"]=			{"Blind",			"HALF",			"For novice players."},
			["blind_normal"]=		{"Blind",			"ALL",			"For intermediate players."},
			["blind_hard"]=			{"Blind",			"SUDDEN",		"For experienced players."},
			["blind_lunatic"]=		{"Blind",			"SUDDEN+",		"For professionals."},
			["blind_ultimate"]=		{"Blind",			"?",			"R U Ready?"},
			["blind_wtf"]=			{"Blind",			"WTF",			"i m not ready"},
			["classic_fast"]=		{"Classic",			"CTWC",			"High-speed classic mode."},
			["survivor_easy"]=		{"Survivor",		"EASY",			"How long can you survive?"},
			["survivor_normal"]=	{"Survivor",		"NORMAL",		"How long can you survive?"},
			["survivor_hard"]=		{"Survivor",		"HARD",			"How long can you survive?"},
			["survivor_lunatic"]=	{"Survivor",		"LUNATIC",		"How long can you survive?"},
			["survivor_ultimate"]=	{"Survivor",		"ULTIMATE",		"How long can you survive?"},
			["attacker_hard"]=		{"Attacker",		"HARD",			"Offensive practice!"},
			["attacker_ultimate"]=	{"Attacker",		"ULTIMATE",		"Offensive practice!"},
			["defender_normal"]=	{"Defender",		"NORMAL",		"Defensive practice!"},
			["defender_lunatic"]=	{"Defender",		"LUNATIC",		"Defensive practice!"},
			["dig_hard"]=			{"Driller",			"HARD",			"Digging practice!"},
			["dig_ultimate"]=		{"Driller",			"ULTIMATE",		"Digging practice!"},
			["bigbang"]=			{"Big Bang",		"EASY",			"All-spin tutorial!\n[Under construction]"},
			["c4wtrain_normal"]=	{"C4W Training",	"NORMAL",		"Infinite combos."},
			["c4wtrain_lunatic"]=	{"C4W Training",	"LUNATIC",		"Infinite combos."},
			["pctrain_normal"]=		{"PC Training",		"NORMAL",		"Simple Perfect Clear mode."},
			["pctrain_lunatic"]=	{"PC Training",		"LUNATIC",		"Simple Perfect Clear mode."},
			["pcchallenge_normal"]=	{"PC Challenge",	"NORMAL",		"Get PCs within 100 lines!"},
			["pcchallenge_hard"]=	{"PC Challenge",	"HARD",			"Get PCs within 100 lines!"},
			["pcchallenge_lunatic"]={"PC Challenge",	"LUNATIC",		"Get PCs within 100 lines!"},
			["tech_normal"]=		{"Tech",			"NORMAL",		"Keep the B2B chain!"},
			["tech_normal2"]=		{"Tech",			"NORMAL+",		"Spin & PC only"},
			["tech_hard"]=			{"Tech",			"HARD",			"Keep the B2B chain!"},
			["tech_hard2"]=			{"Tech",			"HARD+",		"Spin & PC only"},
			["tech_lunatic"]=		{"Tech",			"LUNATIC",		"Keep the B2B chain!"},
			["tech_lunatic2"]=		{"Tech",			"LUNATIC+",		"Spin & PC only"},
			["tech_finesse"]=		{"Tech",			"FINESSE",		"No finesse faults!"},
			["tech_finesse2"]=		{"Tech",			"FINESSE+",		"No normal clears, no finesse faults!"},
			["tsd_easy"]=			{"TSD Challenge",	"EASY",			"T-spin-doubles only!"},
			["tsd_hard"]=			{"TSD Challenge",	"HARD",			"T-spin-doubles only!"},
			["tsd_ultimate"]=		{"TSD Challenge",	"ULTIMATE",		"T-spin-doubles only!"},
			["zen"]=				{"Zen",				"200",			"200 lines without a time limit."},
			["ultra"]=				{"Ultra",			"EXTRA",		"Get the highest score within 2 min."},
			["infinite"]=			{"Infinite",		"",				"Sandbox mode."},
			["infinite_dig"]=		{"Infinite: Dig",	"",				"Dig, dig, dig."},
			["custom_clear"]=		{"Custom",			"NORMAL",		"Draw something then clear it!!"},
			["custom_puzzle"]=		{"Custom",			"PUZZLE",		"Draw something then stack it!!"},
			["sprintFix"]=			{"Sprint",			"NO LEFT/RIGHT","It's possible."},
			["sprintLock"]=			{"Sprint",			"NO ROTATIONS",	"It's impossible."},
			["sprintPenta"]=		{"Sprint",			"PENTOMINO",	"Clear 40 lines with 18 pentominoes."},
			["sprintMPH"]=			{"Sprint",			"MPH",			"Memoriyless\nPreviewless\nHoldless"},
		},
		getTip=function()
			local L={'!','@','#','$','%','^','&','*','(',')','-','=','_','+','[',']','{','}','\\','|',';',':','\'','"',',','<','.','>','/','?'}
			local s=""
			for _=1,math.random(16,26)do
				s=s..L[math.random(#L)]
			end
			return s
		end,
	},
	{
		back="返回",
		anykey="您开始了",
		newVersion="感谢更新,请看看更新了些啥",
		httpTimeout="没网或者网不好?",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		holdR="长按重开",

		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain="剩 $1 人",
		cmb={nil,"1连","2连","3连","4连","5连","6连","7连","8连","9连","10连!","11连!","12连!","13连!","14连!","15连!","16连!","17连!","18连!","19连!","MEGACMB"},
		block=nil,spin="旋",
		clear={"消一","消二","消三","消四","卧槽"},
		mini="矬",b2b="牛逼",b3b="很牛逼",
		PC="消干净了",HPC="消挺干净",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage="关卡 $1",
		great="不错的",
		awesome="您很强",
		almost="太舒服了",
		continue="您继续",
		maxspeed="速度封顶",
		speedup="速度加快",
		missionFailed="非任务消除",

		win="成了",
		finish="可以的",
		gameover="挂了",
		pause="歇会",
		pauseCount="歇多久了",
		finesse_ap="您",
		finesse_fc="全连",

		snapLevelName={"无吸附","10px吸附","20px吸附","40px吸附","60px吸附","80px吸附"},
		page="页面:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		ai_mission="不能同时开启电脑玩家和自定义任务",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",
		switchSpawnSFX="请开启方块出生音效",
		getRank="本局评级:",
		ranks={"菜","可","好","强","您"},

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		pasteSuccess="粘贴成功",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		getNoticeFail="拉取公告失败",
		getVersionFail="检测新版本失败",
		versionIsNew="游戏已是最新版本",
		versionIsOld="最新版本$1可以下载了!",
		registerSuccessed="注册成功!",
		registerFailed="注册失败",
		netErrorCode="网络错误码",
		noUsername="账号密码都填不来?",
		noPassword="账号密码都填不来?",
		diffPassword="账号密码都填不来?",
		errorMsg="Techmino遭受了雷击,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"Spin:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"ADPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spin0~3",
			clear="clear1~4",
			"开了几次:",
			"玩了几把:",
			"玩了多久:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"牛逼/很牛逼:",
			"消光/消半截:",
			"多余操作/极简率:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"使用LOVE2D引擎",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1127702001进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序: MrZ, FinnTenzor",
			"美术: MrZ, (T0722, Gnyar)",
			"音乐: MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM 测试: 思竣",
			"英文文案: User670 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear [MinusKelvin]
			json.lua [rxi]
			profile.lua [itraykov]
			simple-love-lights [dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1127702001",
		WidgetText={
			main={
				play="开始",
				custom="自定义",
				qplay="快速开始",
				stat="统计信息",
				help="帮助",
				setting="设置",
				lang="言/A",
				music="音乐室",
				account="账户",
				sound="音效室",
				minigame="小游戏",
				quit="退出",
			},
			mode={
				start="开始",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				title="游戏设置",

				graphic="←改画面",
				sound="改声音→",

				ctrl="改控制",
				key="改键位",
				touch="改触屏",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				appLock="家长锁(密码626)",
				calc="家长锁",
			},
			setting_video={
				title="改画面",

				sound="←改声音",
				game="游戏设置→",

				block="方块可见",
				ghost="阴影",
				smooth="平滑下落",

				center="中心",
				grid="网格",
				bagLine="包分界线",

				lockFX="锁定特效",
				dropFX="下落特效",
				moveFX="移动特效",
				clearFX="消除特效",
				shakeFX="晃动特效",
				atkFX="攻击特效",
				frame="绘制帧率",

				text="招式名",
				score="跳分",
				warn="死亡预警",
				highCam="拉镜",
				nextPos="生成预览",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
			},
			setting_sound={
				title="改声音",

				game="←游戏设置",
				graphic="改画面→",

				sfx="音效",
				stereo="立体声",
				spawn="出块",
				bgm="曲",
				vib="嗡嗡",
				voc="语音",
			},
			setting_control={
				title="改控制",
				preview="预览",

				das="DAS",arr="ARR",
				sddas="软降DAS",sdarr="软降ARR",
				ihs="提前Hold",
				irs="提前旋转",
				ims="提前移动",
				reset="重来",
			},
			setting_key={
				keyboard="键盘",
				joystick="手柄",
				help="方向键选择/翻页,回车/空格修改,esc返回",
			},
			setting_skin={
				title="改外观",

				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="重设配色",
				faceR="重设方向",
			},
			setting_touch={
				default="默认组合",
				snap="吸附",
				option="选项",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="右转:",		b4="左转:",
				b5=	"180°转:",	b6="硬降:",		b7="软降:",		b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				basic="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
			},
			setting_trackSetting={
				VKDodge="自动避让",
			},
			customGame={
				title="自定义游戏",
				subTitle="基本",
				defSeq="默认序列",
				noMsn="无任务",

				drop="下落延迟",
				lock="锁定延迟",
				wait="出块等待",
				fall="消行延迟",

				bg="背景",
				bgm="音乐",

				copy="复制场地+序列+任务",
				paste="粘贴场地+序列+任务",
				clear="开始-消除",
				puzzle="开始-拼图",

				advance="更多设置(A)",
				field="场地编辑(F)",
				sequence="序列编辑(S)",
				mission="任务编辑(M)",
			},
			custom_advance={
				title="自定义游戏",
				subTitle="高级",

				next="Next",hold="Hold",oncehold="Hold一次",
				block="方块可见",
				ghost="阴影透明度",
				center="中心透明度",
				bagLine="包分界线",
				highCam="超屏视野",
				nextPos="生成预览",
				bone="骨块",

				mindas="最小DAS",
				minarr="最小ARR",
				minsdarr="最小软降ARR",
				noTele="禁止瞬移",
				ospin="O-spin",
				target="目标行数",
				visible="能见度",
				freshLimit="锁延刷新限制",
				easyFresh="普通刷新锁延",
				fineKill="强制极简",
				opponent="对手",
				life="命数",
				pushSpeed="上涨速度",
			},
			custom_field={
				title="自定义游戏",
				subTitle="场地",

				b12="[  ]",
				any="不定",
				space="×",
				copy="复制",
				paste="粘贴",
				clear="清除",
				pushLine="增加一行(K)",
				delLine="消除行(L)",
				demo="不显示×",
			},
			custom_sequence={
				title="自定义游戏",
				subTitle="序列",

				sequence="序列",

				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
			},
			custom_mission={
				title="自定义游戏",
				subTitle="任务",

				_1="1",_2="2",_3="3",_4="4",
				any1="any1",any2="any2",any3="any3",any4="any4",
				PC="PC",
				Z1="Z1",S1="S1",J1="J1",L1="L1",T1="T1",O1="O1",I1="I1",
				Z2="Z2",S2="S2",J2="J2",L2="L2",T2="T2",O2="O2",I2="I2",
				Z3="Z3",S3="S3",J3="J3",L3="L3",T3="T3",O3="O3",I3="I3",
				O4="O4",I4="I4",
				left="←",right="→",
				ten="→→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				mission="强制任务",
			},
			help={
				dict="小Z词典",
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
			},
			dict={
				title="小Z方块词典",
				keyboard="键盘",
				link="看链接",
				up="↑",
				down="↓",
			},
			staff={
			},
			stat={
				path="打开存储目录",
			},
			music={
				title="音乐室",
				arrow="→",
				now="正在放:",

				bgm="歌",
				up="↑",
				play="播放",
				down="↓",
			},
			login={
				title="登录/注册",
				username="用户名",
				email="邮箱",
				code="邀请码",
				password="密码",
				password2="你觉得应该填啥",
			},
			account={
				title="账户",
			},
			sound={
				title="音效室",
				move="移动",
				lock="锁定",
				drop="硬降",
				fall="行落下",
				rotate="旋转",
				rotatekick="旋转进洞",
				hold="暂存",
				prerotate="提前旋转",
				prehold="提前暂存",

				_1="消一",
				_2="消二",
				_3="消三",
				_4="消四",
				spin0="空旋转",
				spin1="旋转消一",
				spin2="旋转消二",
				spin3="旋转消三",

				z0="Z旋",
				z1="Z旋消一",
				z2="Z旋消二",
				z3="Z旋消三",
				s0="S旋",
				s1="S旋消一",
				s2="S旋消二",
				s3="S旋消三",

				j0="J旋",
				j1="J旋消一",
				j2="J旋消二",
				j3="J旋消三",
				l0="L旋",
				l1="L旋消一",
				l2="L旋消二",
				l3="L旋消三",

				t0="T旋",
				t1="T旋消一",
				t2="T旋消二",
				t3="T旋消三",
				o0="O旋",
				o1="O旋消一",
				o2="O旋消二",
				o3="O旋消三",

				i0="I旋",
				i1="I旋消一",
				i2="I旋消二",
				i3="I旋消三",

				mini="矬",
				b2b="牛逼",
				b3b="很牛逼",
				pc="消干净了",
			},
			minigame={
				p15="15 Puzzle",
				schulte_G="舒尔特方格",
				pong="Pong",
			},
			p15={
				reset="打乱",
				color="彩",
				blind="盲",
				slide="滑动",
				pathVis="路径显示",
				revKB="键盘反向",
			},
			schulte_G={
				reset="重开",
				rank="尺寸",
				blind="盲",
				disappear="消失",
				tapFX="动画",
			},
			pong={
				reset="重置",
			},
			debug={
				copyLog="复制日志",
				scrInfo="输出屏幕信息",
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10L",		"消10行"},
			["sprint_20"]=			{"竞速",		"20L",		"消20行"},
			["sprint_40"]=			{"竞速",		"40L",		"消40行"},
			["dig_10"]=				{"挖掘",		"10L",		"挖10行"},
			["dig_40"]=				{"挖掘",		"40L",		"挖40行"},
			["dig_100"]=			{"挖掘",		"100L",		"挖100行"},
			["dig_400"]=			{"挖掘",		"400L",		"挖400行"},
			["dig_1000"]=			{"挖掘",		"1000L",	"挖1000行"},
			["sprint_100"]=			{"竞速",		"100L",		"消100行"},
			["sprint_400"]=			{"竞速",		"400L",		"消400行"},
			["sprint_1000"]=		{"竞速",		"1000L",	"消1000行"},
			["drought_normal"]=		{"干旱",		"100L",		"放轻松,简单得很"},
			["drought_lunatic"]=	{"干旱",		"100L",		"有趣的要来了"},
			["marathon_normal"]=	{"马拉松",		"普通",		"休闲模式"},
			["marathon_hard"]=		{"马拉松",		"困难",		"休闲模式"},
			["marathon_ultimate"]=	{"马拉松",		"极限",		"你再秀?"},
			["solo_1"]=				{"单挑",		"简单",		"鲨AI"},
			["solo_2"]=				{"单挑",		"普通",		"鲨AI"},
			["solo_3"]=				{"单挑",		"困难",		"鲨AI"},
			["solo_4"]=				{"单挑",		"疯狂",		"鲨AI"},
			["solo_5"]=				{"单挑",		"极限",		"鲨AI"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"这我岂不是乱鲨"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"这我岂不是乱鲨"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"你吃鸡率多少?"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"这我岂不是乱鲨"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"这我岂不是乱鲨"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"你吃鸡率多少?"},
			["round_1"]=			{"回合制",		"简单",		"下棋"},
			["round_2"]=			{"回合制",		"普通",		"下棋"},
			["round_3"]=			{"回合制",		"困难",		"下棋"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋"},
			["round_5"]=			{"回合制",		"极限",		"下棋"},
			["master_beginner"]=	{"大师",		"疯狂",		"无脑20G"},
			["master_advance"]=		{"大师",		"极限",		"简单20G"},
			["master_final"]=		{"大师",		"终点",		"究极20G:真正的游戏"},
			["GM"]=					{"宗师",		"GM",		"你行你上"},
			["blind_easy"]=			{"隐形",		"半隐",		"谁都能玩"},
			["blind_normal"]=		{"隐形",		"全隐",		"稍加练习即可"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"和上一个一样"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"这个确实挺难的"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"就这?简单"},
			["survivor_easy"]=		{"生存",		"简单",		"这都玩不下去?不会吧"},
			["survivor_normal"]=	{"生存",		"普通",		"呵呵,这都玩不过?"},
			["survivor_hard"]=		{"生存",		"困难",		"所以呢?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"然后呢?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"舒服了"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"C4W练习",		"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"C4W练习",		"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"随便打打"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"就那几个题,没难度"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷PC"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷PC"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷PC"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal2"]=		{"科研",		"普通+",	"仅允许spin与PC"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard2"]=			{"科研",		"困难+",	"仅允许spin与PC"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic2"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse2"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"TSD挑战",		"简单",		"刷T2"},
			["tsd_hard"]=			{"TSD挑战",		"困难",		"刷T2"},
			["tsd_ultimate"]=		{"TSD挑战",		"极限",		"刷T2"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"2分钟刷分"},
			["infinite"]=			{"无尽",		"",			"真的有人会玩这个?"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"闲得慌的话来挖"},
			["custom_clear"]=		{"自定义",		"普通",		"试验场"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"宁就是方块艺术家"},
			["sprintFix"]=			{"竞速",		"无移动",	"这是可能的。"},
			["sprintLock"]=			{"竞速",		"无旋转",	"这不可能。"},
			["sprintPenta"]=		{"竞速",		"五连块",	"离谱"},
			["sprintMPH"]=			{"竞速",		"纯净",		"听说你反应很快?"},
		},
		getTip={
			"0202年了,还在玩这种小孩子玩的游戏?",
			"100apm?定式刷的吧。",
			"20连pc不是随手?",
			"20G很难?是个人都能玩吧。",
			"25TSD不难吧。",
			"3pps不是人均水平?",
			"40行还要40多秒,就这?",
			"60LPM?拍硬降刷的吧。",
			"别会个c4w就以为自己多强,这是基本功罢了。",
			"不会吧不会吧,真的还有人不能随手Tspin?",
			"除了雨宫太阳你还认识谁?Jonas知道吗?Ajanba听过吗?",
			"还搁这玩手机呢,作业做完了?",
			"极限20G不是随手通?",
			"叫你多练就多练,想着几天变神仙,当自己是谁?",
			"叫你多练消四不听,现在要速度没速度,spin打完地形一塌糊涂,开心了?",
			"满口PCDT信天翁,还会点别的么?",
			"没那水平别天天整什么花里胡哨的,人玩几年你想几天赶上?",
			"全隐40行全消四很难吗??",
			"人只用一只手都能玩,你呢?",
			"少玩点,多眨眼,到时候瞎了别怪我没提醒你",
			"设置都看过一遍了吗?明明都能调还嫌这嫌那,可牛逼了您",
			"天天催更催更,你咋不来帮忙开发啊,真以为作者很强催催啥都有?",
			"天天卖弱,你一定把把150apm吧?",
			"天天F3F3,怕别人不知道你菜?",
			"我曾经在极度愤怒的时候15秒消了40行",
			"我一个滑铲就挖了个11renPC",
			"一口一个wtcl还不赶紧去练,你是不思进取还是不想好好说话?",
			"隐形难吗?那个节目上的谁,水平那么菜也打得还行,就是你菜",
		},
	},
	--Add new language here. Attention, new language won't show in-game when you add language
}
local publicText={
	block={
		"Z","S","J","L","T","O","I",
		"Z5","S5","Q","P","F","E",
		"T5","U","V","W","X",
		"J5","L5","R","Y","N","H","I5"
	},
}
local publicWidgetText={
	calculator={
		_1="1",_2="2",_3="3",
		_4="4",_5="5",_6="6",
		_7="7",_8="8",_9="9",
		_0="0",["."]=".",e="e",
		["+"]="+",["-"]="-",["*"]="*",["/"]="/",
		["<"]="<",["="]="=",
		play="-->",
	},
	lang={
		chi="中文",
		chi2="全中文",
		eng="English",
		str="?????",
		yygq="就这?",
	},
	history={
		prev="↑",
		next="↓",
	},
}
for key,list in next,publicText do
	for i=1,#langList do
		if langList[i][key]then
			local L=langList[i][key]
			for k,v in next,list do
				L[k]=v
			end
		else
			langList[i][key]=list
		end
	end
end
for key,list in next,publicWidgetText do
	for i=1,#langList do
		local WT=langList[i].WidgetText
		if WT[key]then
			local L=WT[key]
			for k,v in next,list do
				L[k]=v
			end
		else
			WT[key]=list
		end
	end
end

--set global name for all back button
local tipMeta={__call=function(L)return L[math.random(#L)]end}
--fallback to Chinese if missing text
local langMeta={__index=langList[1]}
for i=1,#langList do
	local L=langList[i]
	if type(L.getTip)=="table"then
		setmetatable(L.getTip,tipMeta)
	end
	setmetatable(langList[i],langMeta)
	for _,v in next,L.WidgetText do
		v.back=L.back
	end
end

for i=2,#langList do setmetatable(langList[i],langMeta)end

local drawableTextLoad={
	"anykey",
	"replaying",
	"next","hold",
	"win","finish","gameover","pause",

	"VKTchW","VKOrgW","VKCurW",
	"noScore","highScore",
}
local LANG={}
function LANG.getLen()
	return #langList
end
function LANG.set(l)
	text=langList[l]
	for S,L in next,Widgets do
		for _,W in next,L do
			W.text=text.WidgetText[S][W.name]
		end
	end
	for _,s in next,drawableTextLoad do
		drawableText[s]:set(text[s])
	end
	collectgarbage()
end
return LANG