local langList={
	{
		anykey="按任意键继续",
		newVersion="检测到更新!",
		newBigVersion="检测到大更新!大量存档信息已修改",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		lang="中文",
		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain=function(n)return"剩余 "..n.." 名玩家"end,
		cmb={nil,"1 Combo","2 Combo","3 Combo","4 Combo","5 Combo","6 Combo","7 Combo","8 Combo","9 Combo","10 Combo!","11 Combo!","12 Combo!","13 Combo!","14 Combo!","15 Combo!","16 Combo!","17 Combo!","18 Combo!","19 Combo!","MEGACMB"},
		block=nil,spin="-spin ",
		clear={"single","double","triple","Techrash","Techrach+"},
		mini="Mini",b2b="B2B ",b3b="B2B2B ",
		PC="Perfect Clear",HPC="Half Clear",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage=function(n)return"关卡 "..n end,
		great="Great!",
		awesome="Awesome.",
		continue="Continue.",
		maxspeed="最高速度",
		speedup="速度加快",

		win="胜利",
		finish="完成",
		gameover="游戏结束",
		pause="暂停",
		pauseCount="暂停统计",

		custom="自定义游戏",
		customOption={
			drop="下落速度:",
			lock="锁定延迟:",
			wait="放块延迟:",
			fall="消行延迟:",
			next="序列数量:",
			hold="暂存:",
			sequence="序列:",
			visible="可见性:",
			target="目标行数:",
			freshLimit="锁延刷新次数:",
			opponent="对手速度等级:",
			bg="背景:",
			bgm="背景音乐:",
		},
		customVal={
			drop={"0G","1/180G","1/60G","1/40G","1/30G","1/25G","1/20G","1/18G","1/16G","1/14G","1/12G","1/10G","1/9G","1/8G","1/7G","1/6G","1/5G","1/4G","1/3G","1/2G","1G","2G","4G","8G","20G"},
			lock={0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,40,60,180,"∞"},
			wait=nil,
			fall=nil,
			next=nil,
			hold={"开","关","无限"},
			sequence={"bag","his4","随机","循环","固定"},
			visible={"可见","半隐","全隐","瞬隐"},
			target={10,20,40,100,200,500,1000,"∞"},
			freshLimit={0,8,15,"∞"},
			opponent={"无电脑","9S Lv1","9S Lv2","9S Lv3","9S Lv4","9S Lv5","CC Lv1","CC Lv2","CC Lv3","CC Lv4","CC Lv5","CC Lv6"},
		},
		sequence="自定义序列",
		softdropdas="软降DAS:",
		softdroparr="软降ARR:",
		snapLevelName={"无吸附","10px吸附","20px吸附","40px吸附","60px吸附","80px吸附"},
		setting_game="游戏设置",
		setting_video="画面设置",
		setting_sound="声音设置",
		setting_control="控制设置",
		setting_skin="外观设置",
		preview="预览",
		keyboard="键盘",joystick="手柄",
		ctrlSetHelp="方向键选择/翻页,回车修改,esc返回",
		musicRoom="音乐室",
		nowPlaying="正在播放:",
		page="页面:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		switchSpawnSFX="请开启方块出生音效",

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		errorMsg="Techmino遇到了问题,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		load={[0]="加载完成","加载语音ing","加载音乐ing","加载音效ing","加载图片ing","加载模式ing","加载乱七八糟的东西ing"},
		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"Spin:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"OPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spin0~3",
			clear="clear1~4",
			"游戏运行次数:",
			"游戏局数:",
			"游戏时间:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"多余操作/极简率:",
			"满贯/大满贯:",
			"全/半清:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"使用LOVE2D引擎",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1080457319进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序:MrZ, FinnTenzor",
			"美术:MrZ, (Gnyar)",
			"音乐:MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM",
			"测试:思竣 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear[MinusKelvin]
			simple-love-lights[dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1080457319",
		WidgetText={
			calculator={
				_1="1",_2="2",_3="3",
				_4="4",_5="5",_6="6",
				_7="7",_8="8",_9="9",
				_0="0",["<"]="<",["="]="=",
				["+"]="+",
				["-"]="-",
				["*"]="*",
				["/"]="/",
				play="开始",
			},
			main={
				play="开始",
				setting="设置",
				music="音乐室",
				stat="统计信息",
				help="帮助",
				qplay="快速开始",
				lang="言/A",
				quit="退出",
			},
			mode={
				setting="参数(E)",
				start="开始",
				back="返回",
			},
			music={
				bgm="BGM",
				up="↑",
				play="播放",
				down="↓",
				back="返回",
			},
			custom={
				up="↑",
				down="↓",
				left="←",
				right="→",
				set1="40行(1)",
				set2="1v1(2)",
				set3="无尽(3)",
				set4="隐形(4)",
				set5="极限(5)",
				seq="高级设置(Q)",
				draw="初始场地(E)",
				back="返回",
			},
			sequence={
				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				back="返回",
			},
			draw={
				any="不定",
				space="×",
				clear="清除",
				demo="不显示×",
				copy="复制",
				paste="粘贴",
				custom="参数(E)",
				back="返回",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				graphic="←画面设置",
				sound="声音设置→",
				ctrl="控制设置",
				key="键位设置",
				touch="触屏设置",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				lock="软件锁(密码626)",
				back="返回",
			},
			setting_video={
				sound="←声音设置",
				game="游戏设置→",
				ghost="阴影",
				smooth="平滑下落",
				center="旋转中心",
				grid="网格",
				bagLine="包分界线",
				lockFX="锁定特效等级",
				dropFX="下落特效等级",
				clearFX="消除特效等级",
				shakeFX="晃动特效等级",
				atkFX="攻击特效等级",
				frame="绘制帧率",
				text="消行文本",
				warn="死亡预警",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
				back="返回",
			},
			setting_sound={
				game="←游戏设置",
				graphic="画面设置→",
				sfx="音效",
				stereo="立体声",
				spawn="方块生成",
				bgm="音乐",
				vib="振动",
				voc="语音",
				back="返回",
			},
			setting_control={
				das="DAS",arr="ARR",
				sddas="软降DAS",sdarr="软降ARR",
				ihs="提前Hold",
				irs="提前旋转",
				ims="提前移动",
				reset="重置",
				back="返回",
			},
			setting_key={
				back="返回",
			},
			setting_skin={
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="重置配色",
				faceR="重置方向",
				back="返回",
			},
			setting_touch={
				default="默认组合",
				snap=function()return text.snapLevelName[sceneTemp.snap]end,
				option="选项",
				back="返回",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="顺时针旋转:",	b4="逆时针旋转:",
				b5=	"180°旋转:",b6="硬降:",		b7="软降:",			b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				norm="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
				back="返回",
			},
			setting_trackSetting={
				VKDodge="自动避让",
				back="返回",
			},
			setting_lang={
				back="返回",
			},--LangName added later
			help={
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
				back="返回",
			},
			staff={
				back="返回",
			},
			history={
				prev="↑",
				next="↓",
				back="返回",
			},
			stat={
				path="打开存储目录",
				back="返回",
			},
			debug={
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
				back="返回",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10L",		"消除10行"},
			["sprint_20"]=			{"竞速",		"20L",		"消除20行"},
			["sprint_40"]=			{"竞速",		"40L",		"消除40行"},
			["sprint_100"]=			{"竞速",		"100L",		"消除100行"},
			["sprint_400"]=			{"竞速",		"400L",		"消除400行"},
			["sprint_1000"]=		{"竞速",		"1000L",	"消除1000行"},
			["drought_normal"]=		{"干旱",		"100L",		"你I没了"},
			["drought_lunatic"]=	{"干旱",		"100L",		"后 妈 发 牌"},
			["marathon_normal"]=	{"马拉松",		"普通",		"200行加速马拉松"},
			["marathon_hard"]=		{"马拉松",		"困难",		"200行高速马拉松"},
			["solo_1"]=				{"单挑",		"简单",		"打败AI"},
			["solo_2"]=				{"单挑",		"普通",		"打败AI"},
			["solo_3"]=				{"单挑",		"困难",		"打败AI"},
			["solo_4"]=				{"单挑",		"疯狂",		"打败AI"},
			["solo_5"]=				{"单挑",		"极限",		"打败AI"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"49人混战,活到最后"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"49人混战,活到最后"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"49人混战,活到最后"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"99人混战,活到最后"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"99人混战,活到最后"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"99人混战,活到最后"},
			["round_1"]=			{"回合制",		"简单",		"下棋模式"},
			["round_2"]=			{"回合制",		"普通",		"下棋模式"},
			["round_3"]=			{"回合制",		"困难",		"下棋模式"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋模式"},
			["round_5"]=			{"回合制",		"极限",		"下棋模式"},
			["master_beginner"]=	{"大师",		"疯狂",		"20G初心者练习"},
			["master_advance"]=		{"大师",		"极限",		"上级者20G挑战"},
			["master_final"]=		{"大师",		"终点",		"究极20G:无法触及的终点"},
			["GM"]=					{"宗师",		"GM",		"成为方块大师"},
			["blind_easy"]=			{"隐形",		"半隐",		"不强大脑"},
			["blind_normal"]=		{"隐形",		"全隐",		"挺强大脑"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"很强大脑"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"最强大脑"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"高速经典"},
			["survivor_easy"]=		{"生存",		"简单",		"你能存活多久?"},
			["survivor_normal"]=	{"生存",		"普通",		"你能存活多久?"},
			["survivor_hard"]=		{"生存",		"困难",		"你能存活多久?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"你能存活多久?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"你能存活多久?"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"C4W练习",		"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"C4W练习",		"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"简易PC题库,熟悉全清定式的组合"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"简易PC题库,熟悉全清定式的组合"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷PC"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷PC"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷PC"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal+"]=		{"科研",		"普通+",	"仅允许spin与PC"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard+"]=			{"科研",		"困难+",	"仅允许spin与PC"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic+"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse+"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"TSD挑战",		"简单",		"你能连续做几个TSD?"},
			["tsd_hard"]=			{"TSD挑战",		"困难",		"你能连续做几个TSD?"},
			["tsd_ultimate"]=		{"TSD挑战",		"极限",		"你能连续做几个TSD?"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"在两分钟内尽可能拿到最多的分数"},
			["infinite"]=			{"无尽",		"",			"沙盒"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"挖呀挖呀挖"},
			["custom_clear"]=		{"自定义",		"普通",		"画点什么然后把它消除!"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"画点什么然后把它拼出来吧!"},
			["sprintPenta"]=		{"竞速",		"五联块",	"伤脑筋十八块"},
		},
	},
	{
		anykey="按任意键继续",
		newVersion="检测到更新!",
		newBigVersion="检测到大更新!大量存档信息已修改",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		lang="全中文",
		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain=function(n)return"剩余 "..n.." 名玩家"end,
		cmb={nil,"1连击","2连击","3连击","4连击","5连击","6连击","7连击","8连击","9连击","10连击!","11连击!","12连击!","13连击!","14连击!","15连击!","16连击!","17连击!","18连击!","19连击!","巨型连击"},
		block=nil,spin="型回旋",
		clear={"单清","双清","三清","四清","五清"},
		mini="迷你",b2b="满贯",b3b="大满贯",
		PC="场地全清",HPC="场地半清",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage=function(n)return"关卡 "..n end,
		great="不错!",
		awesome="精彩。",
		continue="继续。",
		maxspeed="最高速度",
		speedup="速度加快",

		win="胜利",
		finish="完成",
		gameover="游戏结束",
		pause="暂停",
		pauseCount="暂停统计",

		custom="自定义游戏",
		customOption={
			drop="下落速度:",
			lock="锁定延迟:",
			wait="放块延迟:",
			fall="消行延迟:",
			next="序列数量:",
			hold="暂存:",
			sequence="序列:",
			visible="可见性:",
			target="目标行数:",
			freshLimit="锁延刷新次数:",
			opponent="对手速度等级:",
			bg="背景:",
			bgm="背景音乐:",
		},
		customVal={
			drop={"0G","1/180G","1/60G","1/40G","1/30G","1/25G","1/20G","1/18G","1/16G","1/14G","1/12G","1/10G","1/9G","1/8G","1/7G","1/6G","1/5G","1/4G","1/3G","1/2G","1G","2G","4G","8G","20G"},
			lock={0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,40,60,180,"∞"},
			wait=nil,
			fall=nil,
			next=nil,
			hold={"开","关","无限"},
			sequence={"bag","his4","随机","循环","固定"},
			visible={"可见","半隐","全隐","瞬隐"},
			target={10,20,40,100,200,500,1000,"∞"},
			freshLimit={0,8,15,"∞"},
			opponent={"无电脑","9S Lv1","9S Lv2","9S Lv3","9S Lv4","9S Lv5","CC Lv1","CC Lv2","CC Lv3","CC Lv4","CC Lv5","CC Lv6"},
		},
		sequence="自定义序列",
		snapLevelName={"无吸附","10像素吸附","20像素吸附","40像素吸附","60像素吸附","80像素吸附"},
		setting_game="游戏设置",
		setting_video="画面设置",
		setting_sound="声音设置",
		setting_control="控制设置",
		setting_skin="外观设置",
		preview="预览",
		keyboard="键盘",joystick="手柄",
		ctrlSetHelp="方向键选择/翻页,回车修改,esc返回",
		musicRoom="音乐室",
		nowPlaying="正在播放:",
		page="页面:",

		ai_fixed="不能同时开启电脑玩家和固定序列",
		ai_prebag="不能同时开启电脑玩家和自定义序列",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",

		ai_fixed="不能同时开启电脑玩家和固定序列",
		ai_prebag="不能同时开启电脑玩家和自定义序列",
		switchSpawnSFX="请开启方块出生音效",

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		errorMsg="Techmino遇到了问题,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		load={[0]="加载完成","正在加载语音","正在加载音乐","正在加载音效","正在加载图片","正在加载模式","正在加载乱七八糟的东西"},
		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"回旋:",
			"(大)满贯/全(半)清:",
			"非极简操作:",
		},
		radar={"防","守","攻","送","速","挖"},
		radarData={
			"防/分",
			"挡/分",
			"攻/分",
			"送/分",
			"行/分",
			"挖/分",
		},
		stat={
			spin="回旋0~3",
			clear="消除1~4",
			"游戏运行次数:",
			"游戏局数:",
			"游戏时间:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"多余操作/极简率:",
			"满贯/大满贯:",
			"全/半清:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1080457319进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序:MrZ, FinnTenzor",
			"美术:MrZ, (T0722, Gnyar)",
			"音乐:MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM",
			"测试:思竣 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear[MinusKelvin]
			simple-love-lights[dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1080457319",
		WidgetText={
			calculator={
				_1="1",_2="2",_3="3",
				_4="4",_5="5",_6="6",
				_7="7",_8="8",_9="9",
				_0="0",["<"]="<",["="]="=",
				["+"]="+",
				["-"]="-",
				["*"]="*",
				["/"]="/",
				play="开始",
			},
			main={
				play="开始",
				setting="设置",
				music="音乐室",
				stat="统计信息",
				help="帮助",
				qplay="快速开始",
				lang="言/A",
				quit="退出",
			},
			mode={
				setting="参数(E)",
				start="开始",
				back="返回",
			},
			music={
				bgm="BGM",
				up="↑",
				play="播放",
				down="↓",
				back="返回",
			},
			custom={
				up="↑",
				down="↓",
				left="←",
				right="→",
				set1="40行(1)",
				set2="1v1(2)",
				set3="无尽(3)",
				set4="隐形(4)",
				set5="极限(5)",
				seq="高级设置(Q)",
				draw="初始场地(E)",
				back="返回",
			},
			sequence={
				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				back="返回",
			},
			draw={
				any="不定",
				space="×",
				clear="清除",
				demo="不显示×",
				copy="复制",
				paste="粘贴",
				custom="参数",
				back="返回",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				graphic="←画面设置",
				sound="声音设置→",
				ctrl="控制设置",
				key="键位设置",
				touch="触屏设置",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				lock="软件锁(密码626)",
				back="返回",
			},
			setting_video={
				sound="←声音设置",
				game="游戏设置→",
				ghost="阴影",
				smooth="平滑下落",
				center="旋转中心",
				grid="网格",
				bagLine="包分界线",
				lockFX="锁定特效等级",
				dropFX="下落特效等级",
				clearFX="消除特效等级",
				shakeFX="晃动特效等级",
				atkFX="攻击特效等级",
				frame="绘制帧率",
				text="消行文本",
				warn="死亡预警",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
				back="返回",
			},
			setting_sound={
				game="←游戏设置",
				graphic="画面设置→",
				sfx="音效",
				stereo="立体声",
				spawn="方块生成",
				bgm="音乐",
				vib="振动",
				voc="语音",
				back="返回",
			},
			setting_control={
				das="首次移动延迟",arr="移动重复延迟",
				sddas="首次软降延迟",sdarr="软降重复延迟",
				ihs="提前暂存",
				irs="提前旋转",
				ims="提前移动",
				reset="重置",
				back="返回",
			},
			setting_key={
				back="返回",
			},
			setting_skin={
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="转",
				prev2="↑",next2="↓",spin2="转",
				prev3="↑",next3="↓",spin3="转",
				prev4="↑",next4="↓",spin4="转",
				prev5="↑",next5="↓",spin5="转",
				prev6="↑",next6="↓",spin6="转",
				prev7="↑",next7="↓",spin7="转",
				skinR="重置配色",
				faceR="重置方向",
				back="返回",
			},
			setting_touch={
				default="默认组合",
				snap=function()return text.snapLevelName[sceneTemp.snap]end,
				option="选项",
				back="返回",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="顺时针旋转:",	b4="逆时针旋转:",
				b5=	"180°旋转:",b6="硬降:",		b7="软降:",			b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				norm="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
				back="返回",
			},
			setting_trackSetting={
				VKDodge="自动避让",
				back="返回",
			},
			setting_lang={
				back="返回",
			},--LangName added later
			help={
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
				back="返回",
			},
			staff={
				back="返回",
			},
			history={
				prev="↑",
				next="↓",
				back="返回",
			},
			stat={
				path="打开存储目录",
				back="返回",
			},
			debug={
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
				back="返回",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10行",		"消除10行"},
			["sprint_20"]=			{"竞速",		"20行",		"消除20行"},
			["sprint_40"]=			{"竞速",		"40行",		"消除40行"},
			["sprint_100"]=			{"竞速",		"100行",	"消除100行"},
			["sprint_400"]=			{"竞速",		"400行",	"消除400行"},
			["sprint_1000"]=		{"竞速",		"1000行",	"消除1000行"},
			["drought_normal"]=		{"干旱",		"100行",	"你I没了"},
			["drought_lunatic"]=	{"干旱",		"100行",	"后 妈 发 牌"},
			["marathon_normal"]=	{"马拉松",		"普通",		"200行加速马拉松"},
			["marathon_hard"]=		{"马拉松",		"困难",		"200行高速马拉松"},
			["solo_1"]=				{"单挑",		"简单",		"打败机器人"},
			["solo_2"]=				{"单挑",		"普通",		"打败机器人"},
			["solo_3"]=				{"单挑",		"困难",		"打败机器人"},
			["solo_4"]=				{"单挑",		"疯狂",		"打败机器人"},
			["solo_5"]=				{"单挑",		"极限",		"打败机器人"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"49人混战,活到最后"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"49人混战,活到最后"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"49人混战,活到最后"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"99人混战,活到最后"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"99人混战,活到最后"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"99人混战,活到最后"},
			["round_1"]=			{"回合制",		"简单",		"下棋模式"},
			["round_2"]=			{"回合制",		"普通",		"下棋模式"},
			["round_3"]=			{"回合制",		"困难",		"下棋模式"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋模式"},
			["round_5"]=			{"回合制",		"极限",		"下棋模式"},
			["master_beginner"]=	{"大师",		"疯狂",		"20G初心者练习"},
			["master_advance"]=		{"大师",		"极限",		"上级者20G挑战"},
			["master_final"]=		{"大师",		"终点",		"究极20G:无法触及的终点"},
			["GM"]=					{"宗师",		"GM",		"成为方块大师"},
			["blind_easy"]=			{"隐形",		"半隐",		"不强大脑"},
			["blind_normal"]=		{"隐形",		"全隐",		"挺强大脑"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"很强大脑"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"超强大脑"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"高速经典"},
			["survivor_easy"]=		{"生存",		"简单",		"你能存活多久?"},
			["survivor_normal"]=	{"生存",		"普通",		"你能存活多久?"},
			["survivor_hard"]=		{"生存",		"困难",		"你能存活多久?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"你能存活多久?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"你能存活多久?"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"中四宽练习",	"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"中四宽练习",	"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"简易全清题库,熟悉全清定式的组合"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"简易全清题库,熟悉全清定式的组合"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷全清"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷全清"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷全清"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal+"]=		{"科研",		"普通+",	"仅允许回旋与全清"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard+"]=			{"科研",		"困难+",	"仅允许回旋与全清"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic+"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse+"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"T2挑战",		"简单",		"你能连续做几个T旋双清?"},
			["tsd_hard"]=			{"T2挑战",		"困难",		"你能连续做几个T旋双清?"},
			["tsd_ultimate"]=		{"T2挑战",		"极限",		"你能连续做几个T旋双清?"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"在两分钟内尽可能拿到最多的分数"},
			["infinite"]=			{"无尽",		"",			"沙盒"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"挖呀挖呀挖"},
			["custom_clear"]=		{"自定义",		"普通",		"画点什么然后把它消除!"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"画点什么然后把它拼出来吧!"},
			["sprintPenta"]=		{"竞速",		"五联块",	"伤脑筋十八块"},
		},
	},
	{
		anykey="Press any button",
		newVersion="Updating detected!",
		newBigVersion="Big updating detected! Save data altered",
		marking="Game Author:MrZ_26\nIllegal recording if see this\nAny explanation invalid",
		lang="English",
		atkModeName={"Random","Badges","K.O.s","Attackers"},
		royale_remain=function(n)return n.." Players Remaining"end,
		cmb={nil,"1 Combo","2 Combo","3 Combo","4 Combo","5 Combo","6 Combo","7 Combo","8 Combo","9 Combo","10 Combo!","11 Combo!","12 Combo!","13 Combo!","14 Combo!","15 Combo!","16 Combo!","17 Combo!","18 Combo!","19 Combo!","MEGACMB"},
		block=nil,spin="-spin ",
		clear={"single","double","triple","Techrash","Techrash+"},
		mini="Mini",b2b="B2B ",b3b="B2B2B ",
		PC="Perfect Clear",HPC="Clear",
		hold="Hold",next="Next",
		replaying="[Replaying]",

		stage=function(n)return"Stage "..n end,
		great="Great!",
		awesome="Awesome!",
		continue="Keep going!",
		maxspeed="Max speed!",
		speedup="Speed up!",

		win="Win",
		finish="Finish",
		gameover="Game Over",
		pause="Pause",
		pauseCount="Pauses:",

		custom="Custom Game",
		customOption={
			drop="Drop Speed:",
			lock="Lock Delay:",
			wait="Entry Delay:",
			fall="Line Delay:",
			next="Next Length:",
			hold="Hold:",
			sequence="Randomizer:",
			visible="Visibility:",
			target="Line Goal:",
			freshLimit="Lock Reset Limit:",
			opponent="Opponent Type:",
			bg="Background:",
			bgm="Music:",
		},
		customVal={
			drop={"0G","1/180G","1/60G","1/40G","1/30G","1/25G","1/20G","1/18G","1/16G","1/14G","1/12G","1/10G","1/9G","1/8G","1/7G","1/6G","1/5G","1/4G","1/3G","1/2G","1G","2G","4G","8G","20G"},
			lock={0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,40,60,180,"Inf"},
			wait=nil,
			fall=nil,
			next=nil,
			hold={"On","Off","Inf"},
			sequence={"bag","his4","random","loop","fixed"},
			visible={"normal","slow fade","fast fade","sudden fade"},
			target={10,20,40,100,200,500,1000,"None"},
			freshLimit={0,8,15,"Inf"},
			opponent={"None","9S Lv1","9S Lv2","9S Lv3","9S Lv4","9S Lv5","CC Lv1","CC Lv2","CC Lv3","CC Lv4","CC Lv5","CC Lv6"},
		},
		sequence="Custom Sequence",
		snapLevelName={"Free pos","Snap-10","Snap-20","Snap-40","Snap-60","Snap-80"},
		setting_game="Game settings",
		setting_video="Video settings",
		setting_sound="Sound settings",
		setting_control="Control Settings",
		setting_skin="Layout Settings",
		preview="Preview",
		keyboard="Keyboard",joystick="Controller",
		ctrlSetHelp="Arrowkey to select/change slot,Enter to change,Esc back",
		musicRoom="Music Room",
		nowPlaying="Now Playing:",
		page="Page:",

		ai_fixed="AI is incompatible with fixed sequence",
		ai_prebag="AI is incompatible with custom sequence",
		settingSaved="Settings Saved",
		settingSavingError="Failed to save settings:",
		keyMapSaved="Key settings saved",
		keyMapSavingError="Failed to save key settings:",
		VKSaved="virtual keys saved",
		VKSavingError="Failed to save virtual key:",
		statSavingError="Failed to save stat:",
		unlockSavingError="Failed to save unlock:",
		recSavingError="Failed to save record:",

		ai_fixed="AI is incompatible with fixed sequence",
		ai_prebag="AI is incompatible with custom sequence",
		switchSpawnSFX="Switch on spawn SFX to play",

		needRestart="Effective after restart",
		copySuccess="Copied successfully",
		dataCorrupted="Data corrupted",
		VKTchW="Touch Weight",
		VKOrgW="Origion Weight",
		VKCurW="Cur. Pos. Weight",
		noScore="No Scores Yet",
		highScore="Personal Bests",
		newRecord="New Record!",
		errorMsg="An error has occurred and Techmino needs to restart.\nError info has been created, and you can send it to the author.",

		acts={
			"Move Left:","Move Right:",
			"Rotate Right:","Rotate Left:","Rotate 180°:",
			"Hard Drop:","Soft Drop:","Hold:","Function:","Restart:",
			"Instant Left:","Instant Right:","Ins Down:","Down 1:","Down 4:","Down 10:",
			"Left Drop:","Right Drop:","Left Zangi:","Right Zangi:",
		},
		load={[0]="Finished","Loading voice","Loading BGM","Loading SFX","Loading images","Loading modes","Loading other things"},
		pauseStat={
			"Time:",
			"Key/Rot./Hold:",
			"Piece:",
			"Row/Dig:",
			"Attack/DigAtk:",
			"Received:",
			"Clears:",
			"Spins:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"OPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spins 0-3",
			clear="clears 1-4",
			"Times Launched:",
			"Play Count:",
			"Play Time:",
			"Key/Rot./Hold:",
			"Block/Row/Atk.:",
			"Recv./Res./Asc.:",
			"Dig/Dig Atk.:",
			"Eff./Dig Eff.:",
			"Finesse Errs./Rate:",
			"B2B/B3B:",
			"PC/HPC:",
		},
		help={
			"Now you can play this, you are probabaly do not need \"help\"?",
			"This is just an ordinary block game, not a certain one.",
			"It plays like TO/C2/KOS/TGM3 and others.",
			"",
			"bug reports/suggestions, sent to the author's testing group or email ~",
			"This is a free download available only through discord.gg/f9pUvkh",
			"The game downloaded from other sources may contain viruses,",
			"and only vibration & networking permissions are needed for mobile versions!",
			"The author is not responsible for any losses from modifying the game.",
		},
		staff={
			"Author: MrZ  E-mail: 1046101471@qq.com",
			"Powered by LOVE2D",
			"",
			"Program: MrZ, FinnTenzor",
			"Art: MrZ, (Gnyar)",
			"Music: MrZ, (T0722)",
			"Voice/ Sound: MrZ, Miya",
			"Performance: 模电 HBM",
			"Test: 思竣 Web: 渣渣120",
			"",
			"Special Thanks:",
			"Flyz, Farter, 蕴空之灵,",
			"Teatube, [All test staff]",
		},
		used="Tool used:\n\tBeepbox\n\tGFIE\n\tGoldwave\nLib used:\n\tCold_Clear[MinusKelvin]\n\tsimple-love-lights[dylhunn]",
		support="Support author",
		group="Official QQ Group(if not hacked):1080457319",
		WidgetText={
			calculator={
				_1="1",_2="2",_3="3",
				_4="4",_5="5",_6="6",
				_7="7",_8="8",_9="9",
				_0="0",["<"]="<",["="]="=",
				["+"]="+",
				["-"]="-",
				["*"]="*",
				["/"]="/",
				play="Play",
			},
			main={
				play="Play",
				setting="Settings",
				music="Music room",
				stat="Statistics",
				help="Help",
				qplay="Q. Play",
				lang="言/A",
				quit="Exit",
			},
			mode={
				setting="Settings (E)",
				start="Start",
				back="Back",
			},
			music={
				bgm="BGM",
				up="↑",
				play="Play",
				down="↓",
				back="Back",
			},
			custom={
				up="↑",
				down="↓",
				left="←",
				right="→",
				set1="40L (1)",
				set2="1v1 (2)",
				set3="Inf. (3)",
				set4="Blind (4)",
				set5="Master (5)",
				seq="Advanced(Q)",
				draw="Field Edit(E)",
				back="Back",
			},
			sequence={
				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				backsp="<X",
				reset="R",
				copy="Copy",
				paste="Paste",
				back="Back",
			},
			draw={
				any="Erase",
				space="×",
				clear="Clear",
				demo="Don't show ×",
				copy="Copy",
				paste="Paste",
				custom="Args(E)",
				back="Back",
			},
			play={
				pause="Pause",
			},
			pause={
				setting="Settings (S)",
				replay="Replay (P)",
				resume="Resume (esc)",
				restart="Retry (R)",
				quit="Quit (Q)",
			},
			setting_game={
				graphic="←Video",
				sound="Sound→",
				ctrl="Control settings",
				key="Key Mappings",
				touch="Touch Settings",
				reTime="Start Delay",
				maxNext="Next Queue Length",
				layout="Layout",
				autoPause="Pause when lose focus",
				swap="Key Combination (Change Atk. Mode)",
				fine="Finesse Error Sound",
				lock="Game Lock(pw=626)",
				back="Back",
			},
			setting_video={
				sound="←Sound",
				game="Game→",
				ghost="Ghost",
				smooth="Smooth drop",
				center="Center",
				grid="Grid",
				bagLine="Bag line",
				lockFX="Lock FX level",
				dropFX="Drop FX level",
				clearFX="Clear FX level",
				shakeFX="Field Sway level",
				atkFX="ATK. FX level",
				frame="Render Frame Rate",
				text="Action Text",
				warn="Death Alert",
				fullscreen="Full Screen",
				bg="Background",
				power="Power Info.",
				back="Back",
			},
			setting_sound={
				game="←Game",
				graphic="Video→",
				sfx="SFX",
				stereo="Stereo",
				spawn="Spawning",
				bgm="BGM",
				vib="Vibration",
				voc="Voice",
				back="Back",
			},
			setting_control={
				das="DAS",arr="ARR",
				sddas="Soft Drop DAS",sdarr="Soft Drop ARR",
				ihs="Initial Hold",
				irs="Initial Rotation",
				ims="Initial Movement",
				reset="Reset",
				back="Back",
			},
			setting_key={
				back="Back",
			},
			setting_skin={
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="Reset Color",
				faceR="Reset Dir.",
				back="Back",
			},
			setting_touch={
				default="Default",
				snap=function()return text.snapLevelName[sceneTemp.snap]end,
				option="Options",
				back="Back",
				size="Size",
			},
			setting_touchSwitch={
				b1=	"Move Left:",	b2="Move Right:",	b3="Rotate Right:",	b4="Rotate Left:",
				b5=	"Rotate 180°:",	b6="Hard Drop:",	b7="Soft Drop:",	b8="Hold:",
				b9=	"Function:",	b10="Restart:",		b11="Instant Left:",b12="Instant Right:",
				b13="Ins Down:",	b14="Down 1:",		b15="Down 4:",		b16="Down 10:",
				b17="Left Drop:",	b18="Right Drop:",	b19="Left Zangi:",	b20="Right Zangi:",
				norm="Normal",
				pro="Professioanl",
				hide="Show Virtual Key",
				track="Auto track",
				sfx="SFX",
				vib="VIB",
				icon="Icon",
				tkset="Track Settings",
				alpha="Alpha",
				back="Back",
			},
			setting_trackSetting={
				VKDodge="Auto Dodge",
				back="Back",
			},
			setting_lang={
				back="Back",
			},--LangName added later
			help={
				staff="Staff",
				his="History",
				qq="Author's qq",
				back="Back",
			},
			staff={
				back="Back",
			},
			history={
				prev="↑",
				next="↓",
				back="Back",
			},
			stat={
				path="Open Data Folder",
				back="Back",
			},
			debug={
				reset="Reset?",
				reset1="Reset rank",
				reset2="Reset data",
				reset3="Reset ALL",
				back="Back",
			},
		},
		modes={
			["sprint_10"]=			{"Sprint",			"10L",			"Clear 10 lines!"},
			["sprint_20"]=			{"Sprint",			"20L",			"Clear 20 lines!"},
			["sprint_40"]=			{"Sprint",			"40L",			"Clear 40 lines!"},
			["sprint_100"]=			{"Sprint",			"100L",			"Clear 100 lines!"},
			["sprint_400"]=			{"Sprint",			"400L",			"Clear 400 lines!"},
			["sprint_1000"]=		{"Sprint",			"1000L",		"Clear 1000 lines!"},
			["drought_normal"]=		{"Drought",			"100L",			"No I piece!"},
			["drought_lunatic"]=	{"Drought",			"100L",			"WTF"},
			["marathon_normal"]=	{"Marathon",		"NORMAL",		"200-line marathon with accelerating speed."},
			["marathon_hard"]=		{"Marathon",		"HARD",			"200-line high-speed marathon."},
			["solo_1"]=				{"Battle",			"EASY",			"Defeat the AI!"},
			["solo_2"]=				{"Battle",			"NORMAL",		"Defeat the AI!"},
			["solo_3"]=				{"Battle",			"HARD",			"Defeat the AI!"},
			["solo_4"]=				{"Battle",			"LUNATIC",		"Defeat the AI!"},
			["solo_5"]=				{"Battle",			"ULTIMATE",		"Defeat the AI!"},
			["techmino49_easy"]=	{"Tech 49",			"EASY",			"49-player battle.\nThe last one standing wins."},
			["techmino49_hard"]=	{"Tech 49",			"HARD",			"49-player battle.\nThe last one standing wins."},
			["techmino49_ultimate"]={"Tech 49",			"ULTIMATE",		"49-player battle.\nThe last one standing wins."},
			["techmino99_easy"]=	{"Tech 99",			"EASY",			"99-player battle.\nThe last one standing wins."},
			["techmino99_hard"]=	{"Tech 99",			"HARD",			"99-player battle.\nThe last one standing wins."},
			["techmino99_ultimate"]={"Tech 99",			"ULTIMATE",		"99-player battle.\nThe last one standing wins."},
			["round_1"]=			{"Turn-Based",		"EASY",			"Chess mode"},
			["round_2"]=			{"Turn-Based",		"NORMAL",		"Chess mode"},
			["round_3"]=			{"Turn-Based",		"HARD",			"Chess mode"},
			["round_4"]=			{"Turn-Based",		"LUNATIC",		"Chess mode"},
			["round_5"]=			{"Turn-Based",		"ULTIMATE",		"Chess mode"},
			["master_beginner"]=	{"Master",			"LUNATIC",		"For 20G beginners."},
			["master_advance"]=		{"Master",			"ULTIMATE",		"Professional 20G challenge!"},
			["master_final"]=		{"Master",			"FINAL",		"20G: Unreachable end point!"},
			["GM"]=					{"GrandMaster",		"GM",			"To be Grand Master"},
			["blind_easy"]=			{"Blind",			"HALF",			"For novice players."},
			["blind_normal"]=		{"Blind",			"ALL",			"For intermediate players."},
			["blind_hard"]=			{"Blind",			"SUDDEN",		"For experienced players."},
			["blind_lunatic"]=		{"Blind",			"SUDDEN+",		"For professionals."},
			["blind_ultimate"]=		{"Blind",			"?",			"R U Ready?"},
			["blind_wtf"]=			{"Blind",			"WTF",			"i m not ready"},
			["classic_fast"]=		{"Classic",			"CTWC",			"High-speed classic mode."},
			["survivor_easy"]=		{"Survivor",		"EASY",			"How long can you survive?"},
			["survivor_normal"]=	{"Survivor",		"NORMAL",		"How long can you survive?"},
			["survivor_hard"]=		{"Survivor",		"HARD",			"How long can you survive?"},
			["survivor_lunatic"]=	{"Survivor",		"LUNATIC",		"How long can you survive?"},
			["survivor_ultimate"]=	{"Survivor",		"ULTIMATE",		"How long can you survive?"},
			["attacker_hard"]=		{"Attacker",		"HARD",			"Offensive practice!"},
			["attacker_ultimate"]=	{"Attacker",		"ULTIMATE",		"Offensive practice!"},
			["defender_normal"]=	{"Defender",		"NORMAL",		"Defensive practice!"},
			["defender_lunatic"]=	{"Defender",		"LUNATIC",		"Defensive practice!"},
			["dig_hard"]=			{"Driller",			"HARD",			"Digging practice!"},
			["dig_ultimate"]=		{"Driller",			"ULTIMATE",		"Digging practice!"},
			["bigbang"]=			{"Big Bang",		"EASY",			"All-spin tutorial!\n[Under construction]"},
			["c4wtrain_normal"]=	{"C4W Training",	"NORMAL",		"Infinite combos."},
			["c4wtrain_lunatic"]=	{"C4W Training",	"LUNATIC",		"Infinite combos."},
			["pctrain_normal"]=		{"PC Training",		"NORMAL",		"Simple Perfect Clear mode."},
			["pctrain_lunatic"]=	{"PC Training",		"LUNATIC",		"Simple Perfect Clear mode."},
			["pcchallenge_normal"]=	{"PC Challenge",	"NORMAL",		"Get PCs within 100 lines!"},
			["pcchallenge_hard"]=	{"PC Challenge",	"HARD",			"Get PCs within 100 lines!"},
			["pcchallenge_lunatic"]={"PC Challenge",	"LUNATIC",		"Get PCs within 100 lines!"},
			["tech_normal"]=		{"Tech",			"NORMAL",		"Keep the B2B chain!"},
			["tech_normal+"]=		{"Tech",			"NORMAL+",		"Spin & PC only"},
			["tech_hard"]=			{"Tech",			"HARD",			"Keep the B2B chain!"},
			["tech_hard+"]=			{"Tech",			"HARD+",		"Spin & PC only"},
			["tech_lunatic"]=		{"Tech",			"LUNATIC",		"Keep the B2B chain!"},
			["tech_lunatic+"]=		{"Tech",			"LUNATIC+",		"Spin & PC only"},
			["tech_finesse"]=		{"Tech",			"FINESSE",		"No finesse faults!"},
			["tech_finesse+"]=		{"Tech",			"FINESSE+",		"No normal clears, no finesse faults!"},
			["tsd_easy"]=			{"TSD Challenge",	"EASY",			"T-spin-doubles only!"},
			["tsd_hard"]=			{"TSD Challenge",	"HARD",			"T-spin-doubles only!"},
			["tsd_ultimate"]=		{"TSD Challenge",	"ULTIMATE",		"T-spin-doubles only!"},
			["zen"]=				{"Zen",				"200",			"200 lines without a time limit."},
			["ultra"]=				{"Ultra",			"EXTRA",		"Get the highest score within 2 min."},
			["infinite"]=			{"Infinite",		"",				"Sandbox mode."},
			["infinite_dig"]=		{"Infinite: Dig",	"",				"Dig, dig, dig."},
			["custom_clear"]=		{"Custom",			"NORMAL",		"Draw something then clear it!!"},
			["custom_puzzle"]=		{"Custom",			"PUZZLE",		"Draw something then stack it!!"},
			["sprintPenta"]=		{"Sprint",			"Pentomino",	"Puzzle-18"},
		},
	},
	{
		anykey="↓□↓",
		newVersion="&!!!",
		newBigVersion="&!!!~~~",
		marking="Game Author:MrZ_26\nIllegal recording if see this\nAny explanation invalid",
		lang="?????",
		atkModeName={"?","(  )","!","←→"},
		royale_remain=function(n)return n.."~"end,
		cmb={nil,"!","!!","!!!","!!!!","!!!!!","!!!!!!","!!!!!!!","!!!!!!!!","!!!!!!!!!","!!!!!!!!!!","!!!!!!!!!!!","!!!!!!!!!!!!","!!!!!!!!!!!!!","!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!!","!!!!!!!!!!!!!!!!!!!!",},
		block=nil,spin=" ~",
		clear={"1","2","3","4","5"},
		mini="v",b2b="^ ",b3b="^^ ",
		PC="#<>#",HPC="<>",
		hold="[  ]",next="→",
		replaying="[Replaying]",

		stage=function(n)return"::"..n.."::"end,
		great="!~",
		awesome="!!~",
		continue="~~",
		maxspeed="!!!",
		speedup="~!~",

		win=": )",
		finish="&",
		gameover="x",
		pause="=",
		pauseCount="=:",

		custom="!@#$%^&*",
		customOption={
			drop="↓:",
			lock="↓_:",
			wait="→=:",
			fall="↓=:",
			next="→:",
			hold="[  ]:",
			sequence="$=:",
			visible="?=:",
			target="&=:",
			freshLimit="@:",
			opponent="^_^:",
			bg="{~}:",
			bgm="(~):",
		},
		customVal={
			drop={"0G","1/180G","1/60G","1/40G","1/30G","1/25G","1/20G","1/18G","1/16G","1/14G","1/12G","1/10G","1/9G","1/8G","1/7G","1/6G","1/5G","1/4G","1/3G","1/2G","1G","2G","4G","8G","20G"},
			lock={0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,40,60,180,"Inf"},
			wait=nil,
			fall=nil,
			next=nil,
			hold={"+","-","~"},
			sequence={"(xxx)","[....]","???","{abc}+","==="},
			visible={"=","-","_","."},
			target={10,20,40,100,200,500,1000,"x"},
			freshLimit={0,8,15,"~"},
			opponent={"x","9S Lv1","9S Lv2","9S Lv3","9S Lv4","9S Lv5","CC Lv1","CC Lv2","CC Lv3","CC Lv4","CC Lv5","CC Lv6"},
		},
		sequence="!@#$%^&*",
		snapLevelName={"~","10","20","40","60","80"},
		setting_game="%~~%",
		setting_video="{~~}",
		setting_sound="(~~)",
		setting_control="[~~]",
		setting_skin="%{~~}",
		preview="?:",
		keyboard="[##]",joystick="^-^",
		ctrlSetHelp="......",
		musicRoom="(~~~~)",
		nowPlaying="~:",
		page=":",

		ai_fixed="X!!!",
		ai_prebag="X!!!",
		settingSaved="~~~",
		settingSavingError="x!:",
		keyMapSaved="~~~",
		keyMapSavingError="x!:",
		VKSaved="~~~",
		VKSavingError="x!:",
		statSavingError="x!:",
		unlockSavingError="x!:",
		recSavingError="x!:",

		needRestart="!!*#R#*!!",
		copySuccess="~$~",
		dataCorrupted="XXXXX",
		VKTchW="Tch↓",
		VKOrgW="Org↓",
		VKCurW="Cur↓",
		noScore="?_____?",
		highScore="__&:",
		newRecord="^!!!^",
		errorMsg="An e??o? h@s occ^__ed @nd Techmino n__ds to r_st@rt.\n&**o* in#o h@$ b==n cre@ted, @nd y0u c@n $&nd it to the @uth0r.",

		acts={
			"←:","→:",
			"R→:","←R:","R↑↓:",
			"↓↓:","↓:","□←:","F:","R:",
			"|←:","→|:","↓_:","↓1:","↓4:","↓10:",
			"←↓→↓:","→↓↓:","←↓→↓:","→↓←↓:",
		},
		load={[0]="___","_vocie_","_BGM_","_SFX_","_images_","_modes_","_???_"},
		pauseStat={
			"~:",
			"=/''/[  ]:",
			"□:",
			"-/↓:",
			"→/↓→:",
			"←:",
			"□↓:",
			"~↓:",
			"^^/^^^/#<>#/<>:",
			"!#!X:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"OPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="~0-3",
			clear="□1-4",
			"@:",
			"##:",
			"~:",
			"=/''/[  ]:",
			"□/-/→.:",
			"←/-↓/↑:",
			"↓/↓→.:",
			"^%/↓^%:",
			"!#!X/%:",
			"^/^^:",
			"#<>#/<>:",
		},
		help={
			"□□□□~~~, ?_?x ?",
			"□!!~~~,□□□□X",
			"□!!==*/*/*/*~",
			"",
			"bug reports/suggestions, sent to the author's testing group or email ~",
			"This is a free download available only through discord.gg/f9pUvkh",
			"The game downloaded from other sources may contain viruses,",
			"and only vibration & networking permissions are needed for mobile versions!",
			"The author is not responsible for any losses from modifying the game.",
		},
		staff={
			"Author: MrZ  E-mail: 1046101471@qq.com",
			"Powered by LOVE2D",
			"",
			"Program: MrZ, FinnTenzor",
			"Art: MrZ, (Gnyar)",
			"Music: MrZ, (T0722)",
			"Voice/ Sound: MrZ, Miya",
			"Performance: 模电 HBM",
			"Test: 思竣 Web: 渣渣120",
			"",
			"Special Thanks:",
			"Flyz, Farter, 蕴空之灵,",
			"Teatube, [All test staff]",
		},
		used="Tool used:\n\tBeepbox\n\tGFIE\n\tGoldwave\nLib used:\n\tCold_Clear[MinusKelvin]\n\tsimple-love-lights[dylhunn]",
		support="Support author",
		group="Official QQ Group(if not hacked):1080457319",
		WidgetText={
			calculator={
				_1="1",_2="2",_3="3",
				_4="4",_5="5",_6="6",
				_7="7",_8="8",_9="9",
				_0="0",["<"]="<",["="]="=",
				["+"]="+",
				["-"]="-",
				["*"]="*",
				["/"]="/",
				play="!!!",
			},
			main={
				play="!!!",
				setting="_?_",
				music="~~~",
				stat="=___",
				help="???",
				qplay="!",
				lang="言/A",
				quit="X",
			},
			mode={
				setting="_?_ (E)",
				start="!!!",
				back="X",
			},
			music={
				bgm="#~#",
				up="↑",
				play="!!!",
				down="↓",
				back="X",
			},
			custom={
				up="↑",
				down="↓",
				left="←",
				right="→",
				set1="40L (1)",
				set2="1v1 (2)",
				set3="Inf. (3)",
				set4="Blind (4)",
				set5="Master (5)",
				seq="Advanced(Q)",
				draw="####(E)",
				back="X",
			},
			sequence={
				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				backsp="<X",
				reset="R",
				copy="→__",
				paste="__→",
				back="X",
			},
			draw={
				any="_",
				space="×",
				clear="XXX",
				demo="X ×",
				copy="→__",
				paste="__→",
				custom="_?_(E)",
				back="X",
			},
			play={
				pause="||",
			},
			pause={
				setting="_?_ (S)",
				replay="## (P)",
				resume="!! (esc)",
				restart="_→_ (R)",
				quit="X (Q)",
			},
			setting_game={
				graphic="←Video",
				sound="Sound→",
				ctrl="=?=",
				key="=?",
				touch="_?",
				reTime="3-2-1",
				maxNext="=123",
				layout="=-=-=",
				autoPause="A||",
				swap="=+=+=",
				fine="!#!X #!#",
				lock="?XX(=626)",
				back="X",
			},
			setting_video={
				sound="←Sound",
				game="Game→",
				ghost="__↓__",
				smooth="~~↓~~",
				center="+",
				grid="#",
				bagLine="123|123",
				lockFX="↓_~",
				dropFX="↓~",
				clearFX="↓↓↓~",
				shakeFX="~|~|~",
				atkFX="→→~",
				frame="|=|",
				text="ABC",
				warn="!↑↑↑!",
				fullscreen="|←→|",
				bg="__?__",
				power="+.",
				back="X",
			},
			setting_sound={
				game="←Game",
				graphic="Video→",
				sfx="#!#",
				stereo="←~→",
				spawn="#[]#",
				bgm="#~#",
				vib="=~=",
				voc="~~~",
				back="X",
			},
			setting_control={
				das="x---x x x",arr="x   x-x-x",
				sddas="↓---↓ ↓ ↓",sdarr="↓   ↓-↓-↓",
				ihs="![ ]",
				irs="!''",
				ims="!←→",
				reset="R",
				back="X",
			},
			setting_key={
				back="X",
			},
			setting_skin={
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="R @%&",
				faceR="R ↑↓←→.",
				back="X",
			},
			setting_touch={
				default="$0",
				snap=function()return text.snapLevelName[sceneTemp.snap]end,
				option="_?",
				back="X",
				size="←→",
			},
			setting_touchSwitch={
				b1=	"←:",    b2="→:",   b3="R→:",   b4="←R:",
				b5=	"R↑↓:",   b6="↓↓:",   b7="↓:",     b8="□←:",
				b9=	"F:",    b10="R:",  b11="←←:",  b12="→→:",
				b13="↓_:",   b14="↓1:",  b15="↓4:",   b16="↓10:",
				b17="←↓→↓:", b18="→↓↓:", b19="←↓→↓:",b20="→↓←↓:",
				norm="-",
				pro="+",
				hide="--?",
				track="~=?",
				sfx="#!#",
				vib="=~=",
				icon="@?",
				tkset="_~=_",
				alpha="+?",
				back="X",
			},
			setting_trackSetting={
				VKDodge="←_→",
				back="X",
			},
			setting_lang={
				back="X",
			},--LangName added later
			help={
				staff="Orz",
				his="_&_",
				qq="_@_",
				back="X",
			},
			staff={
				back="X",
			},
			history={
				prev="↑",
				next="↓",
				back="X",
			},
			stat={
				path="_$_",
				back="X",
			},
			debug={
				reset="Reset?",
				reset1="Reset rank",
				reset2="Reset data",
				reset3="Reset ALL",
				back="X",
			},
		},
		modes={
			["sprint_10"]=			{"Sprint",			"10L",			"Clear 10 lines!"},
			["sprint_20"]=			{"Sprint",			"20L",			"Clear 20 lines!"},
			["sprint_40"]=			{"Sprint",			"40L",			"Clear 40 lines!"},
			["sprint_100"]=			{"Sprint",			"100L",			"Clear 100 lines!"},
			["sprint_400"]=			{"Sprint",			"400L",			"Clear 400 lines!"},
			["sprint_1000"]=		{"Sprint",			"1000L",		"Clear 1000 lines!"},
			["drought_normal"]=		{"Drought",			"100L",			"No I piece!"},
			["drought_lunatic"]=	{"Drought",			"100L",			"WTF"},
			["marathon_normal"]=	{"Marathon",		"NORMAL",		"200-line marathon with accelerating speed."},
			["marathon_hard"]=		{"Marathon",		"HARD",			"200-line high-speed marathon."},
			["solo_1"]=				{"Battle",			"EASY",			"Defeat the AI!"},
			["solo_2"]=				{"Battle",			"NORMAL",		"Defeat the AI!"},
			["solo_3"]=				{"Battle",			"HARD",			"Defeat the AI!"},
			["solo_4"]=				{"Battle",			"LUNATIC",		"Defeat the AI!"},
			["solo_5"]=				{"Battle",			"ULTIMATE",		"Defeat the AI!"},
			["techmino49_easy"]=	{"Tech 49",			"EASY",			"49-player battle.\nThe last one standing wins."},
			["techmino49_hard"]=	{"Tech 49",			"HARD",			"49-player battle.\nThe last one standing wins."},
			["techmino49_ultimate"]={"Tech 49",			"ULTIMATE",		"49-player battle.\nThe last one standing wins."},
			["techmino99_easy"]=	{"Tech 99",			"EASY",			"99-player battle.\nThe last one standing wins."},
			["techmino99_hard"]=	{"Tech 99",			"HARD",			"99-player battle.\nThe last one standing wins."},
			["techmino99_ultimate"]={"Tech 99",			"ULTIMATE",		"99-player battle.\nThe last one standing wins."},
			["round_1"]=			{"Turn-Based",		"EASY",			"Chess mode"},
			["round_2"]=			{"Turn-Based",		"NORMAL",		"Chess mode"},
			["round_3"]=			{"Turn-Based",		"HARD",			"Chess mode"},
			["round_4"]=			{"Turn-Based",		"LUNATIC",		"Chess mode"},
			["round_5"]=			{"Turn-Based",		"ULTIMATE",		"Chess mode"},
			["master_beginner"]=	{"Master",			"LUNATIC",		"For 20G beginners."},
			["master_advance"]=		{"Master",			"ULTIMATE",		"Professional 20G challenge!"},
			["master_final"]=		{"Master",			"FINAL",		"20G: Unreachable end point!"},
			["GM"]=					{"GrandMaster",		"GM",			"To be Grand Master"},
			["blind_easy"]=			{"Blind",			"HALF",			"For novice players."},
			["blind_normal"]=		{"Blind",			"ALL",			"For intermediate players."},
			["blind_hard"]=			{"Blind",			"SUDDEN",		"For experienced players."},
			["blind_lunatic"]=		{"Blind",			"SUDDEN+",		"For professionals."},
			["blind_ultimate"]=		{"Blind",			"?",			"R U Ready?"},
			["blind_wtf"]=			{"Blind",			"WTF",			"i m not ready"},
			["classic_fast"]=		{"Classic",			"CTWC",			"High-speed classic mode."},
			["survivor_easy"]=		{"Survivor",		"EASY",			"How long can you survive?"},
			["survivor_normal"]=	{"Survivor",		"NORMAL",		"How long can you survive?"},
			["survivor_hard"]=		{"Survivor",		"HARD",			"How long can you survive?"},
			["survivor_lunatic"]=	{"Survivor",		"LUNATIC",		"How long can you survive?"},
			["survivor_ultimate"]=	{"Survivor",		"ULTIMATE",		"How long can you survive?"},
			["attacker_hard"]=		{"Attacker",		"HARD",			"Offensive practice!"},
			["attacker_ultimate"]=	{"Attacker",		"ULTIMATE",		"Offensive practice!"},
			["defender_normal"]=	{"Defender",		"NORMAL",		"Defensive practice!"},
			["defender_lunatic"]=	{"Defender",		"LUNATIC",		"Defensive practice!"},
			["dig_hard"]=			{"Driller",			"HARD",			"Digging practice!"},
			["dig_ultimate"]=		{"Driller",			"ULTIMATE",		"Digging practice!"},
			["bigbang"]=			{"Big Bang",		"EASY",			"All-spin tutorial!\n[Under construction]"},
			["c4wtrain_normal"]=	{"C4W Training",	"NORMAL",		"Infinite combos."},
			["c4wtrain_lunatic"]=	{"C4W Training",	"LUNATIC",		"Infinite combos."},
			["pctrain_normal"]=		{"PC Training",		"NORMAL",		"Simple Perfect Clear mode."},
			["pctrain_lunatic"]=	{"PC Training",		"LUNATIC",		"Simple Perfect Clear mode."},
			["pcchallenge_normal"]=	{"PC Challenge",	"NORMAL",		"Get PCs within 100 lines!"},
			["pcchallenge_hard"]=	{"PC Challenge",	"HARD",			"Get PCs within 100 lines!"},
			["pcchallenge_lunatic"]={"PC Challenge",	"LUNATIC",		"Get PCs within 100 lines!"},
			["tech_normal"]=		{"Tech",			"NORMAL",		"Keep the B2B chain!"},
			["tech_normal+"]=		{"Tech",			"NORMAL+",		"Spin & PC only"},
			["tech_hard"]=			{"Tech",			"HARD",			"Keep the B2B chain!"},
			["tech_hard+"]=			{"Tech",			"HARD+",		"Spin & PC only"},
			["tech_lunatic"]=		{"Tech",			"LUNATIC",		"Keep the B2B chain!"},
			["tech_lunatic+"]=		{"Tech",			"LUNATIC+",		"Spin & PC only"},
			["tech_finesse"]=		{"Tech",			"FINESSE",		"No finesse faults!"},
			["tech_finesse+"]=		{"Tech",			"FINESSE+",		"No normal clears, no finesse faults!"},
			["tsd_easy"]=			{"TSD Challenge",	"EASY",			"T-spin-doubles only!"},
			["tsd_hard"]=			{"TSD Challenge",	"HARD",			"T-spin-doubles only!"},
			["tsd_ultimate"]=		{"TSD Challenge",	"ULTIMATE",		"T-spin-doubles only!"},
			["zen"]=				{"Zen",				"200",			"200 lines without a time limit."},
			["ultra"]=				{"Ultra",			"EXTRA",		"Get the highest score within 2 min."},
			["infinite"]=			{"Infinite",		"",				"Sandbox mode."},
			["infinite_dig"]=		{"Infinite: Dig",	"",				"Dig, dig, dig."},
			["custom_clear"]=		{"Custom",			"NORMAL",		"Draw something then clear it!!"},
			["custom_puzzle"]=		{"Custom",			"PUZZLE",		"Draw something then stack it!!"},
			["sprintPenta"]=		{"Sprint",			"Pentomino",	"Puzzle-18"},
		},
	},
	{
		anykey="您开始了",
		newVersion="感谢更新!",
		newBigVersion="检测到大更新!大量存档信息已修改",
		marking="游戏作者:MrZ_26\n任何视频/直播不得出现此水印\n任何转述声明无效",
		lang="就这",
		atkModeName={"随机","徽章","击杀","反击"},
		royale_remain=function(n)return"剩 "..n.." 人"end,
		cmb={nil,"1连","2连","3连","4连","5连","6连","7连","8连","9连","10连!","11连!","12连!","13连!","14连!","15连!","16连!","17连!","18连!","19连!","MEGACMB"},
		block=nil,spin="旋",
		clear={"消一","消二","消三","消四","卧槽"},
		mini="矬",b2b="牛逼",b3b="很牛逼",
		PC="消干净了",HPC="消挺干净",
		hold="暂存",next="下一个",
		replaying="[回放]",

		stage=function(n)return"关卡 "..n end,
		great="不错的",
		awesome="您很强",
		continue="您继续",
		maxspeed="速度封顶",
		speedup="速度加快",

		win="成了",
		finish="可以的",
		gameover="挂了",
		pause="歇会",
		pauseCount="歇多久了",

		custom="随便玩",
		customOption={
			drop="落多快:",
			lock="锁多快:",
			wait="出多快:",
			fall="消多快:",
			next="看几个:",
			hold="暂存:",
			sequence="出啥:",
			visible="看不看得见:",
			target="要消多少:",
			freshLimit="能动几下:",
			opponent="打谁:",
			bg="背景:",
			bgm="歌:",
		},
		customVal={
			drop={"0G","1/180G","1/60G","1/40G","1/30G","1/25G","1/20G","1/18G","1/16G","1/14G","1/12G","1/10G","1/9G","1/8G","1/7G","1/6G","1/5G","1/4G","1/3G","1/2G","1G","2G","4G","8G","20G"},
			lock={0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,40,60,180,"∞"},
			wait=nil,
			fall=nil,
			next=nil,
			hold={"开","关","无限"},
			sequence={"bag","his4","乱出","循环","就那几个"},
			visible={"看得到","还行","看不到","瞎了"},
			target={10,20,40,100,200,500,1000,"∞"},
			freshLimit={0,8,15,"∞"},
			opponent={"打空气","9S Lv1","9S Lv2","9S Lv3","9S Lv4","9S Lv5","CC Lv1","CC Lv2","CC Lv3","CC Lv4","CC Lv5","CC Lv6"},
		},
		sequence="自定义序列",
		softdropdas="软降DAS:",
		softdroparr="软降ARR:",
		snapLevelName={"无吸附","10px吸附","20px吸附","40px吸附","60px吸附","80px吸附"},
		setting_game="游戏设置",
		setting_video="改画面",
		setting_sound="改声音",
		setting_control="改控制",
		setting_skin="改外观",
		preview="预览",
		keyboard="键盘",joystick="手柄",
		ctrlSetHelp="方向键选择/翻页,回车修改,esc返回",
		musicRoom="音乐室",
		nowPlaying="正在放:",
		page="页面:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		settingSaved="设置已保存",
		settingSavingError="设置保存失败:",
		keyMapSaved="键位设置已保存",
		keyMapSavingError="键位保存失败:",
		VKSaved="虚拟按键设置已保存",
		VKSavingError="虚拟按键保存失败:",
		statSavingError="统计保存失败:",
		unlockSavingError="解锁保存失败:",
		recSavingError="纪录保存失败:",

		ai_fixed="不能同时开启AI和固定序列",
		ai_prebag="不能同时开启AI和自定义序列",
		switchSpawnSFX="请开启方块出生音效",

		needRestart="重新开始以生效",
		copySuccess="已复制到剪切板",
		dataCorrupted="数据损坏",
		VKTchW="触摸点权重",
		VKOrgW="原始点权重",
		VKCurW="当前点权重",
		noScore="暂无成绩",
		highScore="最佳成绩",
		newRecord="打破纪录",
		errorMsg="Techmino遇到了问题,需要重新启动.\n我们已收集了一些错误信息,你可以向作者进行反馈.",

		acts={
			"左移:","右移:",
			"顺时针旋转:","逆时针旋转:","180°旋转:",
			"硬降:","软降:",
			"暂存:","功能键:",
			"重新开始:",
			"左瞬移:","右瞬移:","软降到底:","软降一格:","软降四格:","软降十格:",
			"落在最左:","落在最右:","列在最左:","列在最右:",
		},

		load={[0]="加载完成","加载语音ing","加载音乐ing","加载音效ing","加载图片ing","加载模式ing","加载乱七八糟的东西ing"},
		pauseStat={
			"时间:",
			"按键/旋转/暂存:",
			"落块:",
			"消行/挖掘:",
			"攻击/挖掘攻击:",
			"上涨/接收/抵消:",
			"消除:",
			"Spin:",
			"B2B/B3B/PC/HPC:",
			"Finesse:",
		},
		radar={"DEF","OFF","ATK","SEND","SPD","DIG"},
		radarData={
			"D'PM",
			"OPM",
			"APM",
			"SPM",
			"L'PM",
			"DPM",
		},
		stat={
			spin="spin0~3",
			clear="clear1~4",
			"开了几次:",
			"玩了几把:",
			"玩了多久:",
			"按键/旋转/暂存:",
			"方块/消行/攻击:",
			"接收/抵消/上涨:",
			"挖掘/挖掘攻击:",
			"效率/挖掘效率:",
			"多余操作/极简率:",
			"满贯/大满贯:",
			"全/半清:",
		},
		help={
			"既然你能玩到这个游戏,应该也不需要什么帮助吧?",
			"这只是一个普通的方块游戏,请勿称此游戏为某某某方块",
			"从TO/C2/KOS/TGM3/JS等方块获得过灵感",
			"",
			"使用LOVE2D引擎",
			"错误或者建议请附带截图发送到内测群或者作者邮箱~",
			"仅通过内测群1080457319进行免费下载/更新",
			"其他渠道获得游戏皆有被修改/加广告/植入病毒的风险,程序只申请了振动&联网权限!",
			"若由于被修改的本游戏产生的各种损失作者不负责(我怎么负责啊跟我有啥关系)",
			"请从正规途径获得最新版,游戏现为免费,不过有打赏当然感谢啦~",
		},
		staff={
			"作者:MrZ  邮箱:1046101471@qq.com",
			"使用LOVE2D引擎",
			"",
			"程序:MrZ, FinnTenzor",
			"美术:MrZ, (Gnyar)",
			"音乐:MrZ, (T0722)",
			"音效/语音: MrZ, Miya",
			"演出: 模电, HBM",
			"测试:思竣 官网: 渣渣120",
			"",
			"特别感谢:",
			"Flyz, Farter, 蕴空之灵,",
			"茶管, [所有内测人员]",
		},
		used=[[
		使用工具:
			Beepbox
			GFIE
			Goldwave
		使用库:
			Cold_Clear[MinusKelvin]
			simple-love-lights[dylhunn]
		]],
		support="支持作者",
		group="官方QQ群(如果没有被暗改的话就是这个):1080457319",
		WidgetText={
			calculator={
				_1="1",_2="2",_3="3",
				_4="4",_5="5",_6="6",
				_7="7",_8="8",_9="9",
				_0="0",["<"]="<",["="]="=",
				["+"]="+",
				["-"]="-",
				["*"]="*",
				["/"]="/",
				play="开始",
			},
			main={
				play="开始",
				setting="设置",
				music="音乐室",
				stat="统计信息",
				help="帮助",
				qplay="快速开始",
				lang="言/A",
				quit="退出",
			},
			mode={
				setting="参数(E)",
				start="开始",
				back="返回",
			},
			music={
				bgm="歌",
				up="↑",
				play="播放",
				down="↓",
				back="返回",
			},
			custom={
				up="↑",
				down="↓",
				left="←",
				right="→",
				set1="40行(1)",
				set2="1v1(2)",
				set3="无尽(3)",
				set4="隐形(4)",
				set5="极限(5)",
				seq="高级设置(Q)",
				draw="初始场地(E)",
				back="返回",
			},
			sequence={
				Z="Z",S="S",J="J",L="L",T="T",O="O",I="I",
				Z5="Z5",S5="S5",P="P",Q="Q",F="F",E="E",T5="T5",U="U",
				V="V",W="W",X="X",J5="J5",L5="L5",R="R",Y="Y",N="N",H="H",I5="I5",
				left="←",
				right="→",
				backsp="<X",
				reset="R",
				copy="复制",
				paste="粘贴",
				back="返回",
			},
			draw={
				any="不定",
				space="×",
				clear="清除",
				demo="不显示×",
				copy="复制",
				paste="粘贴",
				custom="参数(E)",
				back="返回",
			},
			play={
				pause="暂停",
			},
			pause={
				setting="设置(S)",
				replay=	"回放(P)",
				resume=	"继续(esc)",
				restart="重新开始(R)",
				quit=	"退出(Q)",
			},
			setting_game={
				graphic="←改画面",
				sound="改声音→",
				ctrl="改控制",
				key="改键位",
				touch="改触屏",
				reTime="开局等待时间",
				maxNext="最大预览数量",
				layout="外观",
				autoPause="失去焦点自动暂停",
				swap="组合键切换攻击模式",
				fine="极简操作提示音",
				lock="家长锁(密码626)",
				back="返回",
			},
			setting_video={
				sound="←改声音",
				game="游戏设置→",
				ghost="阴影",
				smooth="平滑下落",
				center="旋转中心",
				grid="网格",
				bagLine="包分界线",
				lockFX="锁定特效等级",
				dropFX="下落特效等级",
				clearFX="消除特效等级",
				shakeFX="晃动特效等级",
				atkFX="攻击特效等级",
				frame="绘制帧率",
				text="消行文本",
				warn="死亡预警",
				fullscreen="全屏",
				bg="背景",
				power="电量显示",
				back="返回",
			},
			setting_sound={
				game="←游戏设置",
				graphic="改画面→",
				sfx="音效",
				stereo="立体声",
				spawn="出块",
				bgm="曲",
				vib="嗡嗡",
				voc="语音",
				back="返回",
			},
			setting_control={
				das="DAS",arr="ARR",
				sddas="软降DAS",sdarr="软降ARR",
				ihs="提前Hold",
				irs="提前旋转",
				ims="提前移动",
				reset="重来",
				back="返回",
			},
			setting_key={
				back="返回",
			},
			setting_skin={
				prev="←",next="→",
				prev1="↑",next1="↓",spin1="R",
				prev2="↑",next2="↓",spin2="R",
				prev3="↑",next3="↓",spin3="R",
				prev4="↑",next4="↓",spin4="R",
				prev5="↑",next5="↓",spin5="R",
				prev6="↑",next6="↓",spin6="R",
				prev7="↑",next7="↓",spin7="R",
				skinR="重设配色",
				faceR="重设方向",
				back="返回",
			},
			setting_touch={
				default="默认组合",
				snap=function()return text.snapLevelName[sceneTemp.snap]end,
				option="选项",
				back="返回",
				size="大小",
			},
			setting_touchSwitch={
				b1=	"左移:",	b2="右移:",		b3="右转:",		b4="左转:",
				b5=	"180°转:",	b6="硬降:",		b7="软降:",		b8="暂存:",
				b9=	"功能键:",	b10="重新开始:",b11="左瞬移:",		b12="右瞬移:",
				b13="软降到底:",b14="软降一格:",b15="软降四格:",	b16="软降十格:",
				b17="落在最左:",b18="落在最右:",b19="列在最左:",	b20="列在最右:",
				norm="标准",
				pro="专业",
				hide="显示虚拟按键",
				track="按键自动跟踪",
				sfx="按键音效",
				vib="按键振动",
				icon="图标",
				tkset="跟踪设置",
				alpha="透明度",
				back="返回",
			},
			setting_trackSetting={
				VKDodge="自动避让",
				back="返回",
			},
			setting_lang={
				back="返回",
			},--LangName added later
			help={
				staff="制作人员",
				his="更新历史",
				qq="作者QQ",
				back="返回",
			},
			staff={
				back="返回",
			},
			history={
				prev="↑",
				next="↓",
				back="返回",
			},
			stat={
				path="打开存储目录",
				back="返回",
			},
			debug={
				reset="重置?",
				reset1="重置解锁/等级",
				reset2="重置统计",
				reset3="清空所有数据",
				back="返回",
			},
		},
		modes={
			["sprint_10"]=			{"竞速",		"10L",		"消10行"},
			["sprint_20"]=			{"竞速",		"20L",		"消20行"},
			["sprint_40"]=			{"竞速",		"40L",		"消40行"},
			["sprint_100"]=			{"竞速",		"100L",		"消100行"},
			["sprint_400"]=			{"竞速",		"400L",		"消400行"},
			["sprint_1000"]=		{"竞速",		"1000L",	"消1000行"},
			["drought_normal"]=		{"干旱",		"100L",		"哟,就不行了?"},
			["drought_lunatic"]=	{"干旱",		"100L",		"可牛逼了嗷"},
			["marathon_normal"]=	{"马拉松",		"普通",		"休闲模式"},
			["marathon_hard"]=		{"马拉松",		"困难",		"休闲模式"},
			["solo_1"]=				{"单挑",		"简单",		"鲨AI"},
			["solo_2"]=				{"单挑",		"普通",		"鲨AI"},
			["solo_3"]=				{"单挑",		"困难",		"鲨AI"},
			["solo_4"]=				{"单挑",		"疯狂",		"鲨AI"},
			["solo_5"]=				{"单挑",		"极限",		"鲨AI"},
			["techmino49_easy"]=	{"49人混战",	"简单",		"这我岂不是乱鲨"},
			["techmino49_hard"]=	{"49人混战",	"困难",		"这我岂不是乱鲨"},
			["techmino49_ultimate"]={"49人混战",	"极限",		"你吃鸡率多少?"},
			["techmino99_easy"]=	{"99人混战",	"简单",		"这我岂不是乱鲨"},
			["techmino99_hard"]=	{"99人混战",	"困难",		"这我岂不是乱鲨"},
			["techmino99_ultimate"]={"99人混战",	"极限",		"你吃鸡率多少?"},
			["round_1"]=			{"回合制",		"简单",		"下棋"},
			["round_2"]=			{"回合制",		"普通",		"下棋"},
			["round_3"]=			{"回合制",		"困难",		"下棋"},
			["round_4"]=			{"回合制",		"疯狂",		"下棋"},
			["round_5"]=			{"回合制",		"极限",		"下棋"},
			["master_beginner"]=	{"大师",		"疯狂",		"无脑20G"},
			["master_advance"]=		{"大师",		"极限",		"简单20G"},
			["master_final"]=		{"大师",		"终点",		"究极20G:拜拜了您嘞"},
			["GM"]=					{"宗师",		"GM",		"你行你上"},
			["blind_easy"]=			{"隐形",		"半隐",		"谁都能玩"},
			["blind_normal"]=		{"隐形",		"全隐",		"稍加练习即可"},
			["blind_hard"]=			{"隐形",		"瞬隐",		"和上一个一样"},
			["blind_lunatic"]=		{"隐形",		"瞬隐+",	"这个确实挺难的"},
			["blind_ultimate"]=		{"隐形",		"啊这",		"你准备好了吗"},
			["blind_wtf"]=			{"隐形",		"不会吧",	"还没准备好"},
			["classic_fast"]=		{"高速经典",	"CTWC",		"就这?简单"},
			["survivor_easy"]=		{"生存",		"简单",		"这都玩不下去?不会吧"},
			["survivor_normal"]=	{"生存",		"普通",		"呵呵,这都玩不过?"},
			["survivor_hard"]=		{"生存",		"困难",		"所以呢?"},
			["survivor_lunatic"]=	{"生存",		"疯狂",		"然后呢?"},
			["survivor_ultimate"]=	{"生存",		"极限",		"舒服了"},
			["attacker_hard"]=		{"进攻",		"困难",		"进攻练习"},
			["attacker_ultimate"]=	{"进攻",		"极限",		"进攻练习"},
			["defender_normal"]=	{"防守",		"普通",		"防守练习"},
			["defender_lunatic"]=	{"防守",		"疯狂",		"防守练习"},
			["dig_hard"]=			{"挖掘",		"困难",		"挖掘练习"},
			["dig_ultimate"]=		{"挖掘",		"极限",		"挖掘练习"},
			["bigbang"]=			{"大爆炸",		"简单",		"All-spin 入门教程\n未制作完成,落块即通"},
			["c4wtrain_normal"]=	{"C4W练习",		"普通",		"无 限 连 击"},
			["c4wtrain_lunatic"]=	{"C4W练习",		"疯狂",		"无 限 连 击"},
			["pctrain_normal"]=		{"全清训练",	"普通",		"随便打打"},
			["pctrain_lunatic"]=	{"全清训练",	"疯狂",		"就那几个题,没难度"},
			["pcchallenge_normal"]=	{"全清挑战",	"普通",		"100行内刷PC"},
			["pcchallenge_hard"]=	{"全清挑战",	"困难",		"100行内刷PC"},
			["pcchallenge_lunatic"]={"全清挑战",	"疯狂",		"100行内刷PC"},
			["tech_normal"]=		{"科研",		"普通",		"禁止断B2B"},
			["tech_normal+"]=		{"科研",		"普通+",	"仅允许spin与PC"},
			["tech_hard"]=			{"科研",		"困难",		"禁止断B2B"},
			["tech_hard+"]=			{"科研",		"困难+",	"仅允许spin与PC"},
			["tech_lunatic"]=		{"科研",		"疯狂",		"禁止断B2B"},
			["tech_lunatic+"]=		{"科研",		"疯狂+",	"仅允许spin与PC"},
			["tech_finesse"]=		{"科研",		"极简",		"强制最简操作"},
			["tech_finesse+"]=		{"科研",		"极简+",	"禁止普通消除,强制最简操作"},
			["tsd_easy"]=			{"TSD挑战",		"简单",		"刷T2"},
			["tsd_hard"]=			{"TSD挑战",		"困难",		"刷T2"},
			["tsd_ultimate"]=		{"TSD挑战",		"极限",		"刷T2"},
			["zen"]=				{"禅",			"200",		"不限时200行"},
			["ultra"]=				{"限时打分",	"挑战",		"2分钟刷分"},
			["infinite"]=			{"无尽",		"",			"真的有人会玩这个?"},
			["infinite_dig"]=		{"无尽:挖掘",	"",			"闲得慌的话来挖"},
			["custom_clear"]=		{"自定义",		"普通",		"试验场"},
			["custom_puzzle"]=		{"自定义",		"拼图",		"宁就是方块艺术家"},
			["sprintPenta"]=		{"竞速",		"五联块",	"哦哟?你急了"},
		},
	},
}
local publicText={
	block={
		"Z","S","J","L","T","O","I",
		"Z5","S5","Q","P","F","E",
		"T5","U","V","W","X",
		"J5","L5","R","Y","N","H","I5"
	},
}
for key,list in next,publicText do
	for i=1,#langList do
		if langList[i][key]then
			local L=langList[i][key]
			for k,v in next,list do
				L[k]=v
			end
		else
			langList[i][key]=list
		end
	end
end
local publicWidgetText={
	setting_lang={
		chi="中文",
		chi2="全中文",
		eng="English",
		str="?????",
		yygq="就这?",
	},
}
for key,list in next,publicWidgetText do
	for i=1,#langList do
		local WT=langList[i].WidgetText
		if WT[key]then
			local L=WT[key]
			for k,v in next,list do
				L[k]=v
			end
		else
			WT[key]=list
		end
	end
end

local gc=love.graphics
local LANG={}
local drawableTextLoad={
	"anykey",
	"replaying",
	"next","hold",
	"win","finish","gameover","pause",
	"custom","sequence",
	"setting_game",
	"setting_video",
	"setting_sound",
	"setting_sound",
	"setting_control",
	"setting_skin",
	"keyboard","joystick",
	"ctrlSetHelp",
	"musicRoom",
	"nowPlaying",
	"VKTchW","VKOrgW","VKCurW",
	"noScore",
	"highScore",
}
function LANG.getLen()
	return #langList
end
function LANG.set(l)
	text=langList[l]
	for S,L in next,Widgets do
		for N,W in next,L do
			W.text=text.WidgetText[S][W.name]
		end
	end
	for _,s in next,drawableTextLoad do
		drawableText[s]:set(text[s])
	end
	collectgarbage()
end
return LANG