name: 'Automatic Test'
description: 'Check for obvious errors.'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      submodules: 'true'
  - uses: ./.github/actions/build-love
    with:
      file-path: Techmino.love
  - name: Download love
    shell: bash
    run: |
      curl -L https://github.com/love2d/love/releases/download/11.3/love-11.3-linux-x86_64.tar.gz | tar xz
  - name: Prepare PulseAudio
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install pulseaudio pulseaudio-utils pavucontrol alsa-oss alsa-utils -y
  - name: Run automated test
    uses: GabrielBB/xvfb-action@v1
    with:
      run: |
        ./dest/love Techmino.love --test
