name: 'build Windows'
description: 'build Windows package'
inputs:
  love-url:
    required: true
  love-dir:
    required: true
  cc-url:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Download love
      uses: ./.github/actions/get-unzip
      with:
        url: ${{ inputs.love-url }}
    - name: move love
      shell: bash
      run: mv ${{ input.love-dir }} love
    - name: Download ColdClear
      uses: ./.github/actions/get-unzip
      with:
        url: ${{ inputs.cc-url }}
    - name: Download ResourceHacker
      uses: ./.github/actions/get-unzip
      with:
        url: http://www.angusj.com/resourcehacker/resource_hacker.zip
    - uses: ./.github/actions/build-love
    - name: Pack Techmino
      shell: pwsh
      run: |
        cmd /c copy /b .\love\love.exe + .\Techmino.love .\love\Techmino.exe
        del .\love\love.exe
        del .\love\lovec.exe
        del .\love\game.ico
        del .\love\love.ico
        del .\love\changes.txt
        del .\love\readme.txt
        move .\cold_clear.dll .\love
        move .\CCloader.dll .\love
        python .\.github\workflows\updateVersion.py -T Windows -N ${{ inputs.version }}
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action delete -mask ICONGROUP,,'
        cmd /c '.\ResourceHacker.exe -open .\Techmino.rc -save .\Techmino.res -action compile'
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action addoverwrite -res ".\.github\build\Windows\icon_snapshot.ico" -mask ICONGROUP,1,'
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action addoverwrite -res ".\Techmino.res" -mask VERSIONINFO,1,'
