return{
	{"xinren new noob readme",	"help","新人须知","给想入圈的新人:\n两大根本原则:\n1.选手感好的版本(top/jstris/tetrjs/tech),别用编程练习渣版本\n2.踏实打好基础(next预判稳定消四),别只想着炫酷T旋\n两大主要技巧:\n1.熟悉初始位置以及到各个位置的初始操作\n2.提前计算好下一块能放哪\n(推荐阅读)一位块圈dalao给新人的话:www.bilibili.com/read/cv2352939"},
	{"harddrop hd",				"help","HardDrop","harddrop.com/\n全球俄罗斯方块社区"},
	{"harddrop hd wiki",		"help","HardDrop wiki","harddrop.com/wiki/Tetris_Wiki\n全球俄罗斯方块社区的百科全书(英文)"},

	{"yanjiu study",			"other","研究群号","俄罗斯方块·[研究]群号112897780,“中国俄罗斯方块群”"},
	{"chafu study",				"other","茶服","茶服的添加方法、说明等关于茶服的一切:\n139.199.75.237/tos/home/"},
	{"github",					"other","Github仓库","github.com/MrZ626/Techmino\nTechmino的github仓库地址,欢迎star"},

	{"ttt",						"game","TTT","139.199.75.237/ttt\n现代方块特殊操作手把手教程【必须有键盘才能玩,建议用电脑】\n推荐能无hold纯消四完成40行挑战的人学习\n内含T-spin、极简、SRS、部分对战定式介绍等教程\n完全吃透了话就可以成为教练啦！！\n在群内可以提示,但请勿发答案,不然题目就没意义了"},
	{"ttpc",					"game","TTPC","139.199.75.237/ttpc\nSRSbag7方块开局PC教程【手机触屏玩不了】\n推荐完成了ttt的人学习(必须先学会SRS)\n【不包括六巧板等其它PC定式】"},
	{"nazo",					"game","NAZO","139.199.75.237/nazo\n各类SRS考试题【手机触屏玩不了】\n推荐能通过ttt的玩家尝试\n内含各种t-spin/all-spin题目,简单到极难题目都有"},

	{"kos kingofstackers",		"game","KOS","King of Stackers\nkingofstackers.com/games.php\n网页版回合制对战方块点击即玩(可能很卡)"},
	{"tetrjs",					"game","Tetr.js","farter.cn/t\n全平台网页版单机方块点击即玩,有对新人比较友好的全自定义(大多数常用功能),手机只能选几个默认按键组,不能自由摆放。别的都很好"},
	{"tl tetralegends",			"game","Tetra Legends","tetralegends.app\n电脑端网页版单机方块点击即玩(第一次加载可能很慢),除了手感不够舒适以外功能比较强大,动效很好看,还把很多别的游戏里不可见的机制可视化了,游戏体验很好\n注:包含节奏模式!"},
	{"js jstris",				"game","Jstris","jstris.jezevec10.com\n全平台网页对战方块点击即玩,(服务器在国外可能很卡)"},
	{"io tetrio",				"game","Tetr.io","tetr.io\n炫酷在线对战方块点击即玩(需要科学上网)"},
	{"wwc worldwidecombo",		"game","World Wide Combo","worldwidecombos.com\n网页全世界匹配制1对1方块点击即玩"},
	{"tf tetrisfriends",		"game","Tetris Friends","一个已经关服了的网页版方块,曾经是一个不错的对战平台"},

	{"t99 tetris99",			"game","Tetris99","NS端方块,主玩99人混战的吃鸡模式,战术比重比较大,胜率不只由玩家在平时1v1时的水平决定。也有一些常用单机模式如马拉松等"},
	{"ppt puyopuyotetris",		"game","Puyopuyo Tetris","NS端方块(有steamPC版但是手感,网络等都不太好),将tetris和puyopuyo两个下落消除游戏放到一个游戏里,二者可以对战,联机单机模式都很多,很有趣"},

	{"tgm tetrisgrandmaster",	"game","TGM","一个街机平台方块系列,S13/GM等称号出自该系列,可以在win平台运行"},
	{"dtet",					"game","DTET","一个Win平台方块,基于经典规则加入了20G和一个很强大的旋转系统,手感非常好,但是除了键位都不可自定义,能习惯经典出块方向的玩家可以玩"},
	{"hb heboris",				"game","Heboris","一个Win平台方块,仿街机,可以模拟多个方块游戏的部分模式"},
	{"txm textmaster",			"game","Textmaster","一个Win平台方块,包含TGM的所有模式,可以用来练习TGM,手感比真版较好,不足的是world规则不完全一样(如软降到底无锁延,踢墙表有细节不同等)"},

	{"top tetris online study",	"game","Tetris Online","一个Win平台方块,主要用来6人内对战/单挑/刷每日40L榜/挖掘模式/打机器人。支持自定义das/arr但都不能到0,有一点输入延迟但问题不大,是新人入块圈不错的选择"},
	{"te tetriseffect",			"game","Tetris Effect","一个Win/ns/ps4平台方块,特效方块游戏,只有单机模式,手感不算太好,想看特效的可以一试,只是去玩方块的不是很建议"},
	{"techmino",				"game","Techmino","一个Win/安卓/linux/macOS方块,只有单机,但是模式和各种设置都很齐全,适合有一定基础的新人,输入延迟很小,手感很好"},
	{"c2 cultris2 cultrisii",	"game","Cultris II","一个Win/Linux/macOS平台方块,基于经典规则,但支持自定义das/arr,主玩对战,打法是基于时间的连击,考验玩家速度/wide打法/挖掘"},
	{"np nullpomino",			"game","Nullpomino","一个Win平台方块,整个游戏自定义程度极高,几乎任何参数都可以自己设置,是一个专业级方块,不太适合新人上手,连菜单都不太好搞清楚"},
	{"touhoumino",				"game","Touhoumino","块圈玩家自制win平台方块,其实就是一个nullpomino的自带资源包的改版,将东方project元素结合到俄罗斯方块的游戏,好玩但是难度较大,适合有方块基础并且各项能力都较强的玩家游玩(不然都不知道自己怎么死的)"},
	{"misamino",				"game","Misamino","块圈玩家自制win平台方块,单机1v1,主玩回合制模式,可以自定义ai(自己写的话需要了解接口)"},
	{"jj gougou",				"game","JJ块","jj棋牌平台下一个休闲游戏,安卓百度“JJ比赛”官网下载平台后可以找到(找不到的话是你没在官网下载或者你是ios系统)。竖屏,输入延迟很小超流畅,可自定义das/arr/20G软降,简单自定义键位,无hold,没有b2b,无攻击缓冲不可抵消,每次攻击上限为4,连击较强,其他同现代方块"},
	{"huopin",					"game","火拼俄罗斯","腾讯游戏大厅的方块,场地12列,打字的das和arr,1next,无hold,攻击途径只有 消4打3 消3打2,垃圾行为国际象棋棋盘式,几乎不可能挖掘"},



	{"lpm sudu",				"term","LPM","Line per Minute,行每分,体现玩家下块速度(TOP中的lpm是用pps换算的,不是字面意思)"},
	{"pps sudu",				"term","PPS","Piece per Second,块每秒,体现玩家下块速度"},
	{"bpm sudu",				"term","BPM","Block per Minute,块每分,体现玩家下块速度,别问为什么不是PPM,问就是不知道"},
	{"apm gongji",				"term","APM","Attack per Minute,攻击每分,玩家每分钟打出的垃圾行数,一定程度体现玩家攻击力"},
	{"kpm sudu",				"term","KPM","Key per Minute,按键每分,体现玩家按键速度"},
	{"kpp",						"term","KPP","Key per Piece,按键每块,体现玩家操作是否繁琐,学会极简提升操作效率以减少此数字"},
	{"apl xiaolv",				"term","APL","Attack per Line,攻击每行,也叫效率,体现玩家攻击的的行利用率"},

	{"pc perfectclear",			"term","PC","Perfect Clear(全消),消除场地上所有的方块"},
	{"hpc",						"term","HPC","PC(全消)的外延,如果去掉消除部分之下的场地后上面部分是一个PC,那么这个消除就是半PC,打出一些攻击(仅Tech中有)"},
	{"tss t1",					"term","TSS","指T方块spin消1行"},
	{"tsd t2",					"term","TSD","指T方块spin消2行"},
	{"tst t3",					"term","TST","指T方块spin消3行"},
	{"mtss",					"term","MTSS","指T方块mini spin消1行(不同游戏判定不一样)"},
	{"mtsd",					"term","MTSD","指T方块mini spin消2行(仅部分游戏内存在且判定不一样)"},
	{"single",					"term","Single","一次消了一行的意思"},
	{"double",					"term","Double","一次消了两行的意思"},
	{"triple",					"term","Triple","一次消了三行的意思"},
	{"techrash xiaosi",			"term","Techrash","一次消了四行的意思(Tech限定)"},
	{"tetris xiaosi",			"term","Tetris","商标,Tetris游戏名,同时也是别的方块游戏里消四的名字。含义是Tetra(古希腊语 四)+Tennis(作者喜欢的运动)"},

	{"srs",						"term","SRS","Super Rotation System,现代方块最常用的旋转系统,每个方块都有一个旋转中心,旋转后如果和场地有重合,会根据旋转的方向进行一些偏移测试,可以让方块钻进入一些特定形状的洞"},
	{"nrs",						"term","NRS","Nintendo Rotation System"},
	{"ars",						"term","ARS","Arika/Atari Rotation System"},
	{"drs",						"term","DRS","DTET Rotation System"},
	{"trs",						"term","TRS","Techmino Rotation System"},

	{"spin",					"term","Spin","(部分游戏中)使用旋转将方块卡进不能直接移动进入的位置,在一些规则下有攻击加成"},
	{"allspin",					"term","Allspin","一种规则,指所有方块的spin都有攻击力,而不止是Tspin才有攻击(Tspin only)"},
	{"tspin",					"term","Tspin","在官方规则中,当T方块在锁定前的最后一个操作是旋转,并且锁定后旋转中心对应的四个斜角位置有三个不是空气,那么这就是一个Tspin。PS:如果满足一些额外条件会被打上mini标签减少攻击力"},

	{"irs initialrotatesystem",	"term","IRS","Initial Rotation System,提前旋转系统,提前按下旋转后方块出现就是转好的形状,有时可以避免死亡"},
	{"ihs initialholdsystem",	"term","IHS","Initial Hold System,提前Hold系统,提前按下hold后直接出现hold里的方块,有时可以避免死亡"},
	{"ims initialmovesystem",	"term","IMS","Initial Move System,提前移动系统,提前按下移动后方块出现在移动好的位置,有时可以避免死亡"},

	{"next",					"term","Next","预览功能,指示后边几个块的顺序,思考这块怎么摆可以让后面轻松"},
	{"hold",					"term","Hold","暂存功能,将手里的方块和hold槽中的交换,用来调整块序,不能连续使用,更容易摆出你想要的形状"},

	{"md misdrop",				"term","Misdrop","误放,就是不小心放错了地方"},
	{"mh mishold",				"term","Mishold","误hold,就是不小心按到hold导致失去pc机会等"},

	{"sub",						"term","sub","在…之下,用于表示成绩,单位一般可不写,比如40行成绩sub30是秒,1000行sub15是分钟,不写项目默认是40L"},
	{"mini",					"term","mini","附加mini的spin攻击会被弱化,用于平衡不同难易度的tspin攻击,判定在不同游戏都不一样,而且大多数很不好理解,建议只记住常见形状即可"},
	{"b2b2b b3b",				"term","b2b2b","b2b的加强版,缩写b3b,大量b2b后连续b2b会变成b2b2b(b3b),提供更强的攻击(仅Tech中有)"},
	{"b2b btb backtoback",		"term","b2b","Back to Back,连续打出两次特殊消行(spin和消四),中间不夹杂普通消行,可以提供额外的攻击(在tech中b2b为满贯,大满贯是b3b)"},
	{"fin neo iso",				"term","Fin/Neo/Iso","一种特殊T2的名字,不同的游戏内的攻击可能不一样,没有特殊价值,可以不详细了解"},
	{"donate juanzeng",			"term","Donate","捐赠,指刻意临时盖住洞去做tspin等操作来实现不断b2b的一类技巧"},
	{"gongshou",				"term","攻守","通过消除给对手发送垃圾行=攻击\n别人打过来攻击之后用攻击抵消=防御(相杀)\n抵消/吃下所有攻击后打出攻击=反击\n注:大多游戏的攻防是1:1的,4行攻击抵消对手的4行攻击"},
	{"s2w",						"term","S2W","Side 2 Wide,旁边空2列"},
	{"s1w",						"term","S1W","Side 1 Wide,旁边空1列"},
	{"s3w",						"term","S3W","Side 3 Wide,旁边空3列"},
	{"c1w",						"term","C1W","Center 1 Wide,中间空1列"},
	{"c2w",						"term","C2W","Center 2 Wide,中间空2列"},
	{"c3w",						"term","C3W","Center 3 Wide,中间空3列"},
	{"s4w",						"term","S4W","Side 4 Wide,旁边空四列,连击打法的一种,没有c4w那么不平衡,但是也减少很多游戏乐趣"},
	{"c4w",						"term","C4W","Center 4 Wide,中间空四列,连击打法的一种,是一种利用游戏机制的不平衡策略（尤其在开局时）,可以以弱胜强(所以很不光彩,请自觉不要天天用)"},

	{"dt bt qt mt wolfmoon wm dtpc ddpc btpc stsd stmb cspin asc sewer tki god spin lst 狼月 千鸟格子 皇家十字 皇十 雨宫炮 汉堡包 汉堡肉 六巧板 信天翁 鹈鹕 绯红之王",					"term","一种定式","详细请到harddrop查询"},
	{"setup dingshi",			"term","定式","能称为定式的要尽量满足以下至少2~3条:\n能适应大多数块序\n输出高,尽量不浪费T块\n很多方块无需软降,极简操作数少\n有明确后续,分支尽量少"},
	{"63",						"term","6-3堆叠法","指左边6列右边3列的堆叠方式。在玩家有足够的计算能力后可以减少堆叠所用的按键数(反之可能甚至会增加),是主流的用于减少操作数的高端40L堆叠方式,原理跟出块位置是中间偏左有关。"},
	{"ren combo",				"term","连击","从第二次消除起叫1ren/combo"},
	{"20g",						"term","20G","现代方块的最高下落速度,表观就是方块瞬间到底,不存在中间的下落过程,会让方块无法跨越壕沟/从山谷爬出"},
	{"die death siwang",		"term","死亡判定","现代方块的死亡判定:\n1.新出现的方块和场地方块有重叠（窒息）（c4w比s4w强的原因,因为被打进18行都不会窒息）\n2.方块锁定时完全在场地的外面\n3.所有东西的总高度超出40"},
	{"drop speed",				"term","下落速度","一般用?G表示方块的下落速度,意思是每一帧方块往下移动多少格子,一秒下落一格就是1/60G(默认60fps),故G是一个很大的单位,20G即为上限"},
	{"lock delay",				"term","锁延","锁定延迟,方块\"碰到地面→锁定\"之间的时间。经典块仅方块下落一格时刷新倒计时,而现代方块中往往任何操作都将重置该倒计时,所以连续移动和操作可以让方块不马上锁定,拖一会时间(重置次数有限,一般是15)"},
	{"finesse",					"term","Finesse","极简操作,用最少的按键数将方块移到想去的位置的技术,节约时间和减少misdrop。练习可用jstris的极简错误重开或者techmino中打开极简错误提示,多玩就可以"},
	{"das",						"term","DAS","das是从\"按下移动键时动了一格\"到\"开始自动移动\"之间的时间\narr是\"每次自动移动\"之间的时间\n单位都是 帧,也就是1/60秒\n新人推荐用das=8~10,arr=1~2\n有一定水平想提速用das=4~6,arr=0~1"},
	{"das",						"term","DAS通俗","打字时按住o,你会看到:Ooooooooooo\n在时间轴上:O-----------o-o-o-o-o-o-o-o-o-o\n-----------就是das长度,-就是arr长度"},
	{"arr",						"term","ARR","详见das词条"},
	{"bag7 7bag",				"term","bag7","bag7,一种现代方块的出块方式,开局起每7个块是7种形状各出现一次,如:1234567 1357246 7654321"},
	{"his",						"term","His出块","一种出块方式,例如his 4 roll 6 (h4r6)就是在随机生成新的next的时候,随机一个跟最后4次生成的next中有一样的,就重新随机,直到已经尝试6次或和那4个都不一样。"},
	{"ospin",					"term","Ospin","由于O方块旋转后形状不变,只能左右移动,所以经常被卡住,于是方块圈就有了ospin的梗:\n有人做过T99/TF中的O变形的特效视频且广为流传；\nT-ex设计的旋转系统可以用spin使O传送进坑；\nTech设计的变形系统中可以旋转O来变形/传送进入一些特定形状的洞。"},
	{"ospin",					"term","Ospin操作表","{111,5,2, 0,-1,0},{111,5,2,-1,-1,0},{111,5,0,-1, 0,0},//T\n{333,5,2,-1,-1,0},{333,5,2, 0,-1,0},{333,5,0, 0, 0,0},//T\n{313,1,2,-1, 0,0},{313,1,2, 0,-1,0},{313,1,2, 0, 0,0},//Z\n{131,2,2, 0, 0,0},{131,2,2,-1,-1,0},{131,2,2,-1, 0,0},//S\n{113,3,2,-1,-1,0},{331,3,0,-1, 0,0},{331,3,2, 0, 0,0},//L\n{331,4,2, 0,-1,0},{113,4,0, 0, 0,0},{113,4,2,-1, 0,0},//J\n{222,7,2,-1, 0,1},{222,7,2,-2, 0,1},{222,7,2, 0, 0,1},//I\n{121,6,0, 1,-1,1},{112,6,0, 2,-1,2},{122,6,0, 1,-2,2},//O\n{323,6,0,-1,-1,2},{332,6,0,-2,-1,2},{322,6,0,-1,-2,2},//O\n//key,id,dir,dx,dy,freeLv(0=unmovable,1=?Unmvb,2=free)"},
	{"hypertap",				"term","hypertap","快速震动手指,实现比长按更快速+灵活的高速单点移动"},
	{"top attack",				"term","TOP攻击表","消1/2/3/4打0/1/2/4\nTspin攻击为消行数*2,如果符合mini条件则/2\n连击攻击:001122334445+\nb2b攻击+1(如果是T3则+2)\npc攻击+6(该部分攻击aoe直接打出到所有对手,不抵消缓冲槽中的攻击)"},
	{"tech attack",				"term","Techmino攻击表","攻击系统:\n      普通消除:\n            消<4行打出[消行数-0.5]攻击\n      特殊消除:\n            如果是spin,打出[2*消行数]攻击,\n                  B2B攻击+[1/1/2/4/8(spin1~5)]\n                  B3B攻击在B2B基础上+消行数*0.5,+1额外抵挡\n                  mini减至25%\n            不是spin但是单次消>=4行,打出[消行数]攻击,\n                  B2B攻击+1\n                  B3B攻击+50%,+1额外抵挡\n      特殊消除会增加B2B点数,让之后的特殊消除获得B2B(B3B)增益(详细说明见下文)\n      半全消(\"下方有剩余方块\"的全消,如果是I消1行则必须不剩余玩家放置的方块):伤害+2,额外抵挡+2\n      全消:将上述伤害之和减半,再+8~20(本局内递增2),+2额外抵挡(注:本局消行数>4时会将B2B点数拉满)\n      连击:每次连击给予上述攻击[连击数*25%(如果只消一行就是15%)]的加成,12combo达到上限,连击>=3次时再额外加1攻击\n      根据上述规则计算后,向下取整,攻击打出"},
	{"c2",						"term","C2序列","七个块初始权重0\n全体乘2再加0~1的随机数,选数字最大的块出,然后将其权重除以3.5,循环"},
	{"c2",						"term","C2踢墙","左,右,下,左下,右下,左2,右2\n(任何方块的任何旋转都使用这个表)"},
	{"duidie stack",			"term","堆叠","将方块无缝隙地堆起来"},
	{"shuangxuan",				"term","双旋","指能够使用顺时针+逆时针两个旋转键的技术,原来要转三下的情况可以反向转一下就够,减少烦琐操作。\n双旋也是学习finesse的必要前提\n另见 三旋"},
	{"sanxuan",					"term","三旋","指能够使用顺+逆时针+180度旋转三个旋转键的技术,任何方块只需要旋转一次即可。但由于只有部分游戏有180度旋转所以并不通用,而且对速度提升的效果不如双旋显著,不是追求极限速度的玩家可不学"},
	{"input delay",				"term","输入延迟","所有的操作都会晚一点到达游戏,top、te等游戏比较明显,一般来说不可设置,电脑开启性能模式可能会好一点。效果类似于你拿qq远程控制打fps游戏"},
	{"cc coldclear",			"term","Cold Clear","一个ai的名字(就跟alphaGo一样)"},
	{"zzzbot",					"term","ZZZbot","一个ai的名字(就跟alphaGo一样)"},

	{"hebomai hbm",				"name","吉备宏纯","一流玩家(在最强大脑上以3:0击败模电)"},
	{"amemiya taiyou yugong",	"name","雨宫太阳","一流玩家,曾获得PPT的swap模式冠军"},
	{"fst firestorm",			"name","Firestorm","一流玩家,得过jscup冠军"},
	{"wumbo wangbo",			"name","Wumbo","一流玩家,有名的爱在对战用c4w"},
	{"ajb ajanba",				"name","Ajanba","一流玩家,得过jscup冠军"},
	{"blink",					"name","Blink","一流玩家"},
	{"doremy",					"name","Doremy","一流玩家,雨宫说他是世界第二"},
	{"furea",					"name","Furea","一流玩家,ppt的40L WR保持者+ultra WR保持者"},
	{"iljain yijianlian",		"name","Iljain","一流玩家,得过C2 rank1"},
	{"kazu",					"name","Kazu","一流玩家,以熟练md转捐赠闻名"},
	{"microblizz",				"name","Microblizz","一流玩家,曾经的世界40L WR"},
	{"vincehd",					"name","Vince","一流玩家,现任世界最速保持者(无延迟方块)"},
	{"yakine",					"name","Yakine","一流玩家,捐T如喝水,20TSD比你40行还快"},
	{"jonas",					"name","Jonas","经典块一流玩家,曾经的经典块第一,CTWC4连冠"},
	{"joseph",					"name","Joseph","经典块一流玩家,CTWC连冠,多项任天堂方块记录保持者"},
	{"z xiaoz 626",				"name","","这个百科的名字!"},
	{"mrz zjiang 026 ddd",		"name","MrZ","这个游戏的作者!"},
	{"farteryhr pidaye TTT 000","name","Farter","群友,CN块圈元老之一,屁块作者"},
	{"electric modian 283",		"name","吴淞昊","群友,国内一流高端隐形方块玩家,上过最强大脑"},
	{"diao 872",				"name","Diao","群友,一流对战选手,得过jscup亚军,ttt冠军,HDO XII冠军"},
	{"ditoly icrem kuimei 3055","name","葵妹","群友,被清华劝退现于北大的打块天才jk"},
	{"gggf 127",				"name","gggf","群友,20G规则国内一流玩家"},
	{"miya miaotianmiye",		"name","喵田弥夜","群友,vup,喜欢打块的猫猫(Z酱单推),techmino配音之一"},
	{"naki anyingnaimu",		"name","安樱奈莯","群友,vup,喜欢打块的幽灵,techmino配音之一"},
	{"sniraite shege",			"name","Snirate","群友,国内一流方块玩家"},
	{"mifu swl",				"name","Mifu","群友,vup,miya的方块教练"},
	{"ttb teatube chanaiye 022","name","四方茶叶","群友,vup,CN块圈发展重要人物"},
	{"ykzl yunkongzhiling 196",	"name","蕴空之灵","群友,vup,效率之光"},
	{"zzz zouzhizhang",			"name","奏之章","群友,zzzbot的作者,CN块圈人工智能技术发展重要人物之一"},
	{"tty tatianyi 512",		"name","他天一","群友,zzz大爷的c2AI贡献者,打块水平国内前列"},
	{"wdk windkey fengyaoshi",	"name","Windkey","曾经是群友,对战基本只会开局c4w导致风评很差,要学c4w可以看他"},
	{"xb 043",					"name","","群友,研究群赛事主要主办人"},
	{"zxc thtsod guage 655",	"name","ZXC","群友,高技术力"},
	{"tinko 665",				"name","Tinko","群友,高技术力"},
	{"koishi zixin",			"name","子心","群友,vup,T99国内一流战术型玩家"},
	{"mars huoxingge 608",		"name","Mars608","群友,拿过ns ppt国区榜首"},
	{"xingjiehuixing",			"name","星街彗星","vtb,40L单旋sub40"},
	{"quanshanyuji",			"name","犬山玉姬","vtb,憋〇俄罗斯方块企划的发起人,掀起V圈打块潮流的Vtb"},
	{"xiaseji",					"name","夏色祭","vtb,憋〇企划的金字塔顶尖"},
}