name: 'update version'
description: 'common update logic for snapshot and release'
inputs:
  commit:
    required: false
  type:
    required: true
runs:
  using: "composite"
  steps:
    - shell: python
      name: update snapshot saving folder
      run: |
        from io import open
        if '${{ inputs.type }}'.lower() != 'snapshot':
          exit(0)
        with open('conf.lua', 'r+', encoding='utf-8') as file:
          data = file.read()
          data = data.replace("t.identity='Techmino'--Saving folder", "t.identity='Techmino_Snapshot'--Saving folder")
          file.seek(0)
          file.truncate()
          file.flush()
          file.write(data)
    - shell: python
      run: |
        from io import open
        with open('version.lua', 'r+', encoding='utf-8') as file:
          data = file.read()
          data = data.replace('@DEV', '@${{ inputs.commit }}'[0:4] if '${{ inputs.commit }}' != '' else '')
          file.seek(0)
          file.truncate()
          file.flush()
          file.write(data)
