return{
    env={
        drop=60,lock=60,
        wait=0,fall=50,
        garbageSpeed=30,
        highCam=false,
        seqData={1,2,3,4,5,6,7},
        eventSet='stack_e',
        bg='blockrain',bgm='there',
    },
}
