return{
	das=10,
	arr=2,
	dascut=0,
	sddas=2,
	sdarr=2,
	ihs=true,
	irs=true,
	ims=true,
	swap=true,

	ghost=.3,center=1,
	smooth=false,grid=.16,
	upEdge=true,
	bagLine=true,
	text=true,
	score=true,
	lockFX=2,
	dropFX=2,
	moveFX=2,
	clearFX=2,
	splashFX=2,
	shakeFX=2,
	atkFX=2,

	highCam=false,
	nextPos=false,
	hideBoard=false,
	flipBoard=false,

	drop=60,lock=60,
	wait=0,fall=0,
	bone=false,
	fieldH=20,
	nextCount=6,nextStartPos=1,
	holdCount=1,infHold=false,phyHold=false,
	ospin=true,deepDrop=false,
	RS="TRS",
	sequence="bag",
	freshMethod=NULL,
	bag={1,2,3,4,5,6,7},
	face=NULL,skin=NULL,
	mission=NULL,

	life=0,
	garbageSpeed=1,
	pushSpeed=3,
	block=true,
	noTele=false,
	visible="show",
	freshLimit=1e99,easyFresh=true,

	fkey1=false,
	keyCancel={},
	fine=false,fineKill=false,
	b2bKill=false,
	missionKill=false,
	target=1e99,dropPiece=NULL,
	mindas=0,minarr=0,minsdarr=0,

	bg="none",bgm="race",
	noMod=false,
}