name: Techmino CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download AppImageKit
      run: curl -OL https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
    - name: Unpack and Repack
      run: |
        curl -OL https://github.com/26F-Studio/Techmino/releases/download/v0.15.1/Techmino.AppImage
        chmod +x Techmino.AppImage appimagetool-x86_64.AppImage
        ./Techmino.AppImage --appimage-extract
        rm Techmino.AppImage
        cd squashfs-root/usr/share/Techmino
        rm -rf document media parts Zframework conf.lua font.ttf main.lua
        cd ../../../..
        cp -r document media parts Zframework conf.lua font.ttf main.lua squashfs-root/usr/share/Techmino
        ./appimagetool-x86_64.AppImage squashfs-root Techmino.AppImage
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: Techmino.AppImage

  build-android:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download Apktool
      run: curl -OL https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar
    - name: Unpack and Repack
      run: |
        curl -OL https://github.com/26F-Studio/Techmino/releases/download/v0.15.1/Techmino.apk
        java -jar apktool_2.5.0.jar d -s -o apk Techmino.apk
        7z x -o. apk/assets/game.love libAndroid
        rm apk/assets/game.love Techmino.apk
        7z a -tzip apk/assets/game.love document libAndroid media parts Zframework conf.lua font.ttf main.lua
        python3 .github/workflows/updateVersion.py
        java -jar apktool_2.5.0.jar b -o Techmino.apk apk
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Android
        path: Techmino.apk
