name: Techmino CI

on:
  push:
    branches: [ main, ci ]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Install lua and downgrade Java
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install lua5.3 -y
    - name: Get CommitID
      run: |
        CommitID=$(git rev-parse --short "${{ GITHUB.SHA }}")
        echo "CommitID=${CommitID}" >> $GITHUB_ENV
    - name: Get Version
      run: |
        Version=$(lua ./.github/workflows/getVersion.lua -string)
        echo "Version=${Version}" >> $GITHUB_ENV
    - name: Update Conf Version
      run: |
        python3 .github/workflows/updateConfVersion.py -H ${{ env.CommitID }}
    - name: Prepare Love, SDK and NDK
      run: |
        git clone --recurse-submodules https://github.com/Trebor-Huang/love-android.git
        cd love-android
        git checkout --recurse-submodules Techmino
        wget -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools.zip
        yes | ./cmdline-tools/bin/sdkmanager --sdk_root=. --install "platforms;android-30"
        yes | ./cmdline-tools/bin/sdkmanager --sdk_root=. --install "ndk;21.3.6528147"
        export ANDROID_HOME=$(pwd)
    - name: Pack Techmino
      run: |
        zip -r game.love document media parts Zframework conf.lua font.ttf main.lua version.lua
        cd love-android/app/src/main
        mkdir assets
        cd ../../../..
        cp game.love love-android/app/src/main/assets/
        python3 .github/workflows/updateAndroidVersion.py -C $(lua ./.github/workflows/getVersion.lua -code) -N $(lua ./.github/workflows/getVersion.lua -string)
    - name: Build
      run: |
        chmod +x ./love-android/gradlew
        cd ./love-android/
        ./gradlew assembleRelease
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Techmino_${{ env.Version }}_${{ GITHUB.RUN_NUMBER }}_${{ env.CommitID }}_Android
        path: love-android/app/build/outputs/apk/release/app-release-unsigned.apk