name: Techmino CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Download love
      run: |
        curl -LO https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
        7z x love-11.3-win64.zip
    - name: Download ColdClear
      run: |
        curl -LO https://github.com/26F-Studio/Techmino/releases/download/coldclear/coldclear.zip
        7z x coldclear.zip -ocoldclear
        move coldclear\win64\cold_clear.dll love-11.3-win64
        move coldclear\win64\CCloader.dll love-11.3-win64
    - name: Pack Techmino
      shell: cmd
      run: |
        7z a game.zip BGM document image modes parts SFX VOICE Zframework conf.lua font.ttf main.lua
        move game.zip game.love
        copy /b love-11.3-win64\love.exe + game.love love-11.3-win64\Techmino.exe
        del love-11.3-win64\love.exe
        del love-11.3-win64\lovec.exe
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Techmino_win64
        path: love-11.3-win64
